// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Diagnostics;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Haitch.Roslyn.Generators;

/// <summary>Reads additional files (for example <c>.json</c> or <c>.resx</c>) into equatable models.</summary>
internal static class AdditionalFileExtensions
{
    /// <summary>
    /// Yields one result per additional file whose path matches: the file's text and the requested
    /// <c>build_metadata.AdditionalFiles.&lt;Name&gt;</c> values (trimmed; blank ones are null), or a failure
    /// when the text cannot be read.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    /// <param name="pathPredicate">Selects files by path; runs before the text is read, so skipped files cost nothing.</param>
    /// <param name="unreadable">
    /// Reported when a matching file's text is unavailable. Its message receives the file path as <c>{0}</c>,
    /// and the diagnostic is located at that file.
    /// </param>
    /// <param name="metadataNames">
    /// The metadata to read per file; the project must list each in <c>CompilerVisibleItemMetadata</c>
    /// for <c>AdditionalFiles</c> to expose it.
    /// </param>
    public static IncrementalValuesProvider<Result<AdditionalFileModel>> ForAdditionalFiles(
        this IncrementalGeneratorInitializationContext context,
        Func<string, bool> pathPredicate,
        DiagnosticDescriptor unreadable,
        params string[] metadataNames)
    {
        // Copied so a caller mutating its array later cannot change what the pipeline captured.
        var captured = (string[])metadataNames.Clone();

        // Filtering before the combine keeps the options provider from being consulted, or the text
        // read, for files the generator does not want.
        return context.AdditionalTextsProvider
            .Where(text => pathPredicate(text.Path))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, ct) => Read(pair.Left, pair.Right, unreadable, captured, ct));
    }

    private static Result<AdditionalFileModel> Read(
        AdditionalText text,
        AnalyzerConfigOptionsProvider options,
        DiagnosticDescriptor unreadable,
        string[] metadataNames,
        System.Threading.CancellationToken cancellationToken)
    {
        var content = text.GetText(cancellationToken);

        if (content is null)
        {
            // An empty span: the file has no meaningful position, but the path still lets the IDE group
            // the diagnostic under the file.
            var location = new LocationInfo(text.Path, default, default);

            return Result<AdditionalFileModel>.Failure(new DiagnosticInfo(unreadable, location, text.Path));
        }

        var fileOptions = options.GetOptions(text);
        var items = new BuildProperty[metadataNames.Length];

        for (int i = 0; i < metadataNames.Length; i++)
        {
            fileOptions.TryGetValue("build_metadata.AdditionalFiles." + metadataNames[i], out var value);
            var trimmed = value?.Trim();
            items[i] = new BuildProperty(metadataNames[i], string.IsNullOrEmpty(trimmed) ? null : trimmed);
        }

        return Result<AdditionalFileModel>.Success(
            new AdditionalFileModel(text.Path, content.ToString(), items.ToEquatableArray()));
    }
}
