// <auto-generated/>
#nullable enable

using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Haitch.Roslyn.Generators;

/// <summary>
/// Reads MSBuild build properties from <c>AnalyzerConfigOptionsProvider.GlobalOptions</c>. A
/// property only reaches the generator when the project lists it in
/// <c>CompilerVisibleProperty</c>.
/// </summary>
internal static class AnalyzerConfigOptionsProviderExtensions
{
    /// <summary>Reads one build property, trimmed; a missing, empty or whitespace value is null.</summary>
    /// <param name="provider">The analyzer config options provider.</param>
    /// <param name="name">The property name, which the project must expose through <c>CompilerVisibleProperty</c>.</param>
    public static IncrementalValueProvider<string?> ForBuildProperty(
        this IncrementalValueProvider<AnalyzerConfigOptionsProvider> provider,
        string name)
    {
        return provider.Select((options, _) => Read(options, name));
    }

    /// <summary>Reads several build properties at once, each trimmed; blank values are null.</summary>
    /// <param name="provider">The analyzer config options provider.</param>
    /// <param name="names">The property names, which the project must expose through <c>CompilerVisibleProperty</c>.</param>
    public static IncrementalValueProvider<BuildProperties> ForBuildProperties(
        this IncrementalValueProvider<AnalyzerConfigOptionsProvider> provider,
        params string[] names)
    {
        // Copied so a caller mutating its array later cannot change what the pipeline captured.
        var captured = (string[])names.Clone();

        return provider.Select(
            (options, _) =>
            {
                var items = new BuildProperty[captured.Length];

                for (int i = 0; i < captured.Length; i++)
                {
                    items[i] = new BuildProperty(captured[i], Read(options, captured[i]));
                }

                return new BuildProperties(items.ToEquatableArray());
            });
    }

    private static string? Read(AnalyzerConfigOptionsProvider options, string name)
    {
        options.GlobalOptions.TryGetValue("build_property." + name, out var value);

        var trimmed = value?.Trim();

        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }
}
