// <auto-generated/>
#nullable enable

using System;
using System.Globalization;
using System.Text;
using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Generators;

/// <summary>
/// Builds hint names for <c>AddSource</c> that are unique per type.
/// </summary>
internal static class HintName
{
    /// <summary>
    /// Returns <c>{Namespace.}{Outer+}*{Name}{`N if generic}.{suffix}.g.cs</c>. Nesting is joined with
    /// <c>+</c> (the CLR metadata separator) so a nested type <c>A.B+X</c> never collides with a type
    /// <c>X</c> in namespace <c>A.B</c>; generic arity is appended as <c>`N</c> so <c>Foo</c> and
    /// <c>Foo&lt;T&gt;</c> differ.
    /// Roslyn compares hint names case-insensitively, so types whose names differ only in case
    /// (<c>Foo</c> and <c>foo</c> in one namespace) produce colliding names unless
    /// <paramref name="disambiguateCase"/> is set, which inserts an 8-hex-char FNV-1a hash before the
    /// suffix (<c>Ns.Foo.a1b2c3d4.Suffix.g.cs</c>). The hash covers the case-sensitive hint-name stem
    /// (namespace, containing types joined with <c>+</c>, arity) and excludes the suffix. It is opt-in
    /// so existing generators keep their output file names.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="suffix"/> is empty, ends in <c>.cs</c>, starts or ends with <c>.</c>, contains
    /// <c>..</c>, or contains characters other than ASCII letters, digits, <c>.</c>, <c>_</c> and <c>-</c>.
    /// </exception>
    public static string For(TypeModel type, string suffix, bool disambiguateCase = false)
    {
        ValidateSuffix(suffix);

        var builder = new StringBuilder();

        if (type.Namespace is { Length: > 0 } @namespace)
        {
            builder.Append(@namespace).Append('.');
        }

        foreach (var containing in type.ContainingTypes)
        {
            builder.Append(containing.Name);
            AppendArity(builder, containing.TypeParameters.Count);
            builder.Append('+');
        }

        builder.Append(type.Name);
        AppendArity(builder, type.TypeParameters.Count);

        if (disambiguateCase)
        {
            var hash = Fnv1a(builder).ToString("x8", CultureInfo.InvariantCulture);
            builder.Append('.').Append(hash);
        }

        return builder.Append('.').Append(suffix).Append(".g.cs").ToString();
    }

    // Hand-rolled because string.GetHashCode is randomised per process and System.HashCode is absent
    // on netstandard2.0; the hash must be identical across runs for stable file names.
    private static uint Fnv1a(StringBuilder value)
    {
        var hash = 2166136261u;
        for (var i = 0; i < value.Length; i++)
        {
            hash = unchecked((hash ^ value[i]) * 16777619u);
        }

        return hash;
    }

    private static void AppendArity(StringBuilder builder, int arity)
    {
        if (arity > 0)
        {
            builder.Append('`').Append(arity);
        }
    }

    private static void ValidateSuffix(string? suffix)
    {
        if (string.IsNullOrEmpty(suffix))
        {
            throw new ArgumentException("The hint name suffix must not be null or empty.", nameof(suffix));
        }

        if (suffix!.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException("The hint name suffix must not end in '.cs'.", nameof(suffix));
        }

        if (suffix.StartsWith('.') || suffix.EndsWith('.') || suffix.Contains(".."))
        {
            throw new ArgumentException(
                "The hint name suffix must not start or end with '.' or contain '..'.",
                nameof(suffix));
        }

        foreach (var character in suffix)
        {
            var allowed = character is >= 'a' and <= 'z'
                or >= 'A' and <= 'Z'
                or >= '0' and <= '9'
                or '.'
                or '_'
                or '-';

            if (!allowed)
            {
                throw new ArgumentException(
                    $"The hint name suffix contains '{character}'; only ASCII letters, digits, '.', '_' and '-' are allowed.",
                    nameof(suffix));
            }
        }
    }
}
