// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Text;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.Generators;

/// <summary>
/// Post-initialisation helpers for emitting marker attributes that stay collision-free when
/// referenced from more than one assembly: the attribute type is <c>internal</c> and marked
/// <c>[global::Microsoft.CodeAnalysis.EmbeddedAttribute]</c>, which the C# compiler treats as
/// an implementation detail, so two assemblies that each emit their own private copy of the
/// same attribute name never collide with <c>CS0436</c> when referenced together.
/// </summary>
internal static class PostInitializationExtensions
{
    /// <summary>
    /// Adds the <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> definition. Roslyn 4.8 has no
    /// built-in <c>AddEmbeddedAttributeDefinition</c> helper, so this emits the same shape by
    /// hand: <c>internal sealed partial class EmbeddedAttribute : global::System.Attribute</c>,
    /// with no attribute lists. The type is <c>partial</c> and carries no
    /// <c>[AttributeUsage]</c> so that when more than one generator in the same project calls
    /// this method, the duplicate declarations merge into one partial type instead of raising
    /// <c>CS0101</c> (duplicate type) or <c>CS0579</c> (duplicate attribute). Call once per
    /// generator, before any <see cref="AddMarkerAttribute"/> call.
    /// </summary>
    public static void AddEmbeddedAttributeDefinition(
        this IncrementalGeneratorPostInitializationContext context,
        string hintName = "Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs")
    {
        var writer = new SourceWriter();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("namespace Microsoft.CodeAnalysis");

        using (writer.Block())
        {
            writer.WriteLine("internal sealed partial class EmbeddedAttribute : global::System.Attribute");

            using (writer.Block())
            {
            }
        }

        context.AddSource(hintName, writer.ToSourceText());
    }

    /// <summary>
    /// Adds an internal marker attribute source, decorated with the well-known embedded
    /// attribute so a consumer can reference two assemblies that each emit their own private
    /// copy of the same attribute name without a <c>CS0436</c> conflict.
    /// <paramref name="namespace"/> and <paramref name="attributeName"/> must be valid C#
    /// identifiers (dotted segments for the namespace); each property name must be a valid
    /// identifier and each property type must either start with <c>global::</c> or be a C#
    /// predefined type keyword (such as <c>string</c>, <c>int</c> or <c>bool</c>), optionally
    /// suffixed with <c>?</c>. <paramref name="targets"/> must be a non-zero combination of
    /// defined <see cref="AttributeTargets"/> values. Invalid input throws
    /// <see cref="ArgumentException"/>. Every non-nullable reference-type property is rendered
    /// with a <c>= default!;</c> initializer so the generated source compiles cleanly under
    /// <c>#nullable enable</c> (otherwise it would raise <c>CS8618</c>).
    /// </summary>
    public static void AddMarkerAttribute(
        this IncrementalGeneratorPostInitializationContext context,
        string hintName,
        string @namespace,
        string attributeName,
        AttributeTargets targets,
        bool allowMultiple = false,
        bool inherited = false,
        IReadOnlyList<(string Type, string Name)>? properties = null)
    {
        properties ??= Array.Empty<(string Type, string Name)>();

        ValidateNamespace(@namespace);
        ValidateIdentifier(attributeName, nameof(attributeName));
        ValidateTargets(targets);

        for (int i = 0; i < properties.Count; i++)
        {
            (string type, string name) = properties[i];
            ValidatePropertyType(type);
            ValidateIdentifier(name, nameof(properties));
        }

        var writer = new SourceWriter();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine($"namespace {@namespace}");

        using (writer.Block())
        {
            writer.WriteLine(
                $"[global::System.AttributeUsage({BuildTargetsExpression(targets)}, AllowMultiple = {ToLiteral(allowMultiple)}, Inherited = {ToLiteral(inherited)})]");
            writer.WriteLine("[global::Microsoft.CodeAnalysis.EmbeddedAttribute]");
            writer.WriteLine($"internal sealed class {attributeName} : global::System.Attribute");

            using (writer.Block())
            {
                for (int i = 0; i < properties.Count; i++)
                {
                    (string type, string name) = properties[i];
                    writer.WriteLine(RequiresNullSuppression(type)
                        ? $"public {type} {name} {{ get; set; }} = default!;"
                        : $"public {type} {name} {{ get; set; }}");
                }
            }
        }

        context.AddSource(hintName, writer.ToSourceText());
    }

    private static void ValidateNamespace(string @namespace)
    {
        if (string.IsNullOrEmpty(@namespace))
        {
            throw new ArgumentException("Namespace must not be null or empty.", nameof(@namespace));
        }

        string[] segments = @namespace.Split('.');

        for (int i = 0; i < segments.Length; i++)
        {
            if (!SyntaxFacts.IsValidIdentifier(segments[i]))
            {
                throw new ArgumentException($"'{@namespace}' is not a valid namespace.", nameof(@namespace));
            }
        }
    }

    private static void ValidateIdentifier(string value, string paramName)
    {
        if (!SyntaxFacts.IsValidIdentifier(value))
        {
            throw new ArgumentException($"'{value}' is not a valid identifier.", paramName);
        }
    }

    private static void ValidateTargets(AttributeTargets targets)
    {
        if (targets == 0 || (targets & ~AttributeTargets.All) != 0)
        {
            throw new ArgumentException(
                "Targets must be a non-zero combination of defined AttributeTargets values.",
                nameof(targets));
        }
    }

    private static void ValidatePropertyType(string type)
    {
        string coreType = type.EndsWith("?", StringComparison.Ordinal)
            ? type.Substring(0, type.Length - 1)
            : type;

        if (coreType.StartsWith("global::", StringComparison.Ordinal) || IsPredefinedTypeKeyword(coreType))
        {
            return;
        }

        throw new ArgumentException(
            $"Property type '{type}' must start with 'global::' or be a C# keyword type.",
            "properties");
    }

    private static bool RequiresNullSuppression(string type)
    {
        if (type.EndsWith("?", StringComparison.Ordinal))
        {
            return false;
        }

        return !IsValueTypeKeyword(type);
    }

    private static bool IsPredefinedTypeKeyword(string type)
    {
        SyntaxKind kind = SyntaxFacts.GetKeywordKind(type);

        return kind != SyntaxKind.VoidKeyword && SyntaxFacts.IsPredefinedType(kind);
    }

    private static bool IsValueTypeKeyword(string type)
    {
        return SyntaxFacts.GetKeywordKind(type) switch
        {
            SyntaxKind.BoolKeyword or SyntaxKind.ByteKeyword or SyntaxKind.SByteKeyword or
                SyntaxKind.CharKeyword or SyntaxKind.DecimalKeyword or SyntaxKind.DoubleKeyword or
                SyntaxKind.FloatKeyword or SyntaxKind.IntKeyword or SyntaxKind.UIntKeyword or
                SyntaxKind.LongKeyword or SyntaxKind.ULongKeyword or SyntaxKind.ShortKeyword or
                SyntaxKind.UShortKeyword => true,
            _ => false,
        };
    }

    private static string BuildTargetsExpression(AttributeTargets targets)
    {
        string[] names = targets.ToString().Split(',');
        var builder = new StringBuilder();

        for (int i = 0; i < names.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(" | ");
            }

            builder.Append("global::System.AttributeTargets.").Append(names[i].Trim());
        }

        return builder.ToString();
    }

    private static string ToLiteral(bool value)
    {
        return value ? "true" : "false";
    }
}
