// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Generators;

// Wraps ForAttributeWithMetadataName (Roslyn 4.3+) for the common case of finding types marked
// with a specific attribute. The predicate filters to TypeDeclarationSyntax: methods and
// properties are out of scope for this provider, and enums are never TypeDeclarationSyntax so
// they never match. The transform turns the matched node into value-equal models (TypeModel,
// SyntaxInfo, AttributeModel) that carry no live Roslyn objects, so the incremental cache can
// compare outputs across runs instead of always recomputing.
internal static class SyntaxValueProviderExtensions
{
    // ForAttributeWithMetadataName already matched by attribute name, so an unresolved
    // AttributeModel here would mean an error type despite that match (e.g. a broken
    // declaration); such entries are skipped rather than reported, matching TypeModel.From's
    // handling of its own incidental attribute list. Diagnostics for a bad match (e.g. an
    // unresolved attribute, or IsPartial being false) are the caller's decision, not this
    // provider's.
    //
    // A partial type marked on several declarations yields one item: ForAttributeWithMetadataName
    // runs the transform once per marked declaration, so each run keeps its result only when its
    // node is the first marked declaration (compilation tree order, then span start) and drops it
    // otherwise. No Collect() is involved, so unrelated edits still leave the step cached. The
    // attributes are the symbol's, i.e. those of every part.
    //
    // includeMembers fills TypeModel's Fields, Properties, Methods, Events and MemberNames from the symbol
    // (every part contributes). It ties the item's equality to every member edit, so an edit to any member of
    // the type recomputes downstream steps; leave it off unless the generator reads members.
    /// <summary>Finds types marked with the attribute.</summary>
    /// <param name="provider">The syntax provider.</param>
    /// <param name="fullyQualifiedMetadataName">The attribute's fully qualified metadata name.</param>
    /// <param name="trackingName">The tracking name of the resulting step.</param>
    /// <param name="includeMembers">Whether to fill the type model's members.</param>
    /// <param name="predicate">
    /// Optional extra filter. It runs in the syntax phase on every edit, after the built-in kind check,
    /// so it only receives type declarations. It must be cheap and syntax-only, and must not capture state.
    /// </param>
    public static IncrementalValuesProvider<(TypeModel Type, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForTypesWithAttribute(
            this SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            bool includeMembers = false,
            Func<SyntaxNode, CancellationToken, bool>? predicate = null)
    {
        return provider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName,
                predicate: WithKindCheck(static (node, _) => node is TypeDeclarationSyntax, predicate),
                transform: (context, cancellationToken) => Transform(context, includeMembers, cancellationToken))
            .Where(static item => item is not null)
            .Select(static (item, _) => item!.Value)
            .WithTrackingName(trackingName);
    }

    // Method counterpart of ForTypesWithAttribute. The predicate admits only method declarations, so
    // local functions, lambdas, accessors and constructors never reach the transform. The containing
    // type is captured without members by default: that ties the item's equality to the method's own
    // shape only. includeContainingTypeMembers fills its members as includeMembers does for types.
    //
    // A partial method yields one item, built from the definition part. When both parts carry the
    // attribute the transform runs for each; the implementation part's run drops out whenever another
    // marked declaration exists, since that one is necessarily the definition. A part marked alone is
    // kept either way. The attributes are the definition symbol's, which Roslyn merges across parts.
    //
    // Syntax is described by the method declaration rather than the containing type: IsPartial is the
    // method's, AreContainingTypesPartial covers the whole containing chain, and Location is the
    // method identifier.
    /// <summary>Finds methods marked with the attribute.</summary>
    /// <param name="provider">The syntax provider.</param>
    /// <param name="fullyQualifiedMetadataName">The attribute's fully qualified metadata name.</param>
    /// <param name="trackingName">The tracking name of the resulting step.</param>
    /// <param name="includeContainingTypeMembers">
    /// Whether to fill the containing type's fields, properties, methods, events and member names. It ties the step's equality
    /// to every member edit of the containing type, so leave it off unless the generator reads sibling members.
    /// </param>
    /// <param name="predicate">
    /// Optional extra filter. It runs in the syntax phase on every edit, after the built-in kind check,
    /// so it only receives method declarations. It must be cheap and syntax-only, and must not capture state.
    /// </param>
    public static IncrementalValuesProvider<(MethodModel Method, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForMethodsWithAttribute(
            this SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            bool includeContainingTypeMembers = false,
            Func<SyntaxNode, CancellationToken, bool>? predicate = null)
    {
        return ForMembersWithAttribute(
            provider,
            fullyQualifiedMetadataName,
            trackingName,
            static (node, _) => node is MethodDeclarationSyntax,
            predicate,
            includeContainingTypeMembers,
            static (context, includeContainingTypeMembers, cancellationToken) =>
            {
                var method = (IMethodSymbol)context.TargetSymbol;
                var definition = method.PartialDefinitionPart ?? method;

                return TransformMember(
                    context,
                    definition,
                    isImplementationPart: method.PartialDefinitionPart is not null,
                    MethodModel.From(definition, cancellationToken),
                    includeContainingTypeMembers,
                    cancellationToken);
            });
    }

    // Property counterpart of ForMethodsWithAttribute, with the same partial handling (one item,
    // model and attributes from the definition part). The predicate admits PropertyDeclarationSyntax
    // only, so indexers and events never match. A field-targeted attribute ([field: Mark]) is not on
    // the property symbol, so it never matches either.
    /// <summary>Finds properties marked with the attribute.</summary>
    /// <param name="provider">The syntax provider.</param>
    /// <param name="fullyQualifiedMetadataName">The attribute's fully qualified metadata name.</param>
    /// <param name="trackingName">The tracking name of the resulting step.</param>
    /// <param name="includeContainingTypeMembers">
    /// Whether to fill the containing type's fields, properties, methods, events and member names. It ties the step's equality
    /// to every member edit of the containing type, so leave it off unless the generator reads sibling members.
    /// </param>
    /// <param name="predicate">
    /// Optional extra filter. It runs in the syntax phase on every edit, after the built-in kind check,
    /// so it only receives property declarations. It must be cheap and syntax-only, and must not capture state.
    /// </param>
    public static IncrementalValuesProvider<(PropertyModel Property, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForPropertiesWithAttribute(
            this SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            bool includeContainingTypeMembers = false,
            Func<SyntaxNode, CancellationToken, bool>? predicate = null)
    {
        return ForMembersWithAttribute(
            provider,
            fullyQualifiedMetadataName,
            trackingName,
            static (node, _) => node is PropertyDeclarationSyntax,
            predicate,
            includeContainingTypeMembers,
            static (context, includeContainingTypeMembers, cancellationToken) =>
            {
                var property = (IPropertySymbol)context.TargetSymbol;
                var definition = property.PartialDefinitionPart ?? property;

                return TransformMember(
                    context,
                    definition,
                    isImplementationPart: property.PartialDefinitionPart is not null,
                    PropertyModel.From(definition),
                    includeContainingTypeMembers,
                    cancellationToken);
            });
    }

    // Field counterpart. ForAttributeWithMetadataName reports the VariableDeclaratorSyntax of a field
    // declaration, so `[Mark] int a, b;` yields one item per declarator. Fields cannot be partial.
    /// <summary>Finds fields marked with the attribute.</summary>
    /// <param name="provider">The syntax provider.</param>
    /// <param name="fullyQualifiedMetadataName">The attribute's fully qualified metadata name.</param>
    /// <param name="trackingName">The tracking name of the resulting step.</param>
    /// <param name="includeContainingTypeMembers">
    /// Whether to fill the containing type's fields, properties, methods, events and member names. It ties the step's equality
    /// to every member edit of the containing type, so leave it off unless the generator reads sibling members.
    /// </param>
    /// <param name="predicate">
    /// Optional extra filter. It runs in the syntax phase on every edit, after the built-in kind check,
    /// so it only receives field variable declarators. It must be cheap and syntax-only, and must not capture state.
    /// </param>
    public static IncrementalValuesProvider<(FieldModel Field, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForFieldsWithAttribute(
            this SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            bool includeContainingTypeMembers = false,
            Func<SyntaxNode, CancellationToken, bool>? predicate = null)
    {
        return ForMembersWithAttribute(
            provider,
            fullyQualifiedMetadataName,
            trackingName,
            static (node, _) => node is VariableDeclaratorSyntax { Parent.Parent: FieldDeclarationSyntax },
            predicate,
            includeContainingTypeMembers,
            static (context, includeContainingTypeMembers, cancellationToken) =>
            {
                var field = (IFieldSymbol)context.TargetSymbol;

                return TransformMember(
                    context,
                    field,
                    isImplementationPart: false,
                    FieldModel.From(field),
                    includeContainingTypeMembers,
                    cancellationToken);
            });
    }

    // The kind check goes first so a caller's predicate only ever sees nodes of the discovery kind
    // and can cast without testing. Null returns the kind check itself, keeping the unfiltered
    // path allocation-free.
    private static Func<SyntaxNode, CancellationToken, bool> WithKindCheck(
        Func<SyntaxNode, CancellationToken, bool> kindCheck,
        Func<SyntaxNode, CancellationToken, bool>? predicate)
    {
        if (predicate is null)
        {
            return kindCheck;
        }

        return (node, cancellationToken) => kindCheck(node, cancellationToken) && predicate(node, cancellationToken);
    }

    private static IncrementalValuesProvider<(TModel Member, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForMembersWithAttribute<TModel>(
            SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            Func<SyntaxNode, CancellationToken, bool> kindPredicate,
            Func<SyntaxNode, CancellationToken, bool>? userPredicate,
            bool includeContainingTypeMembers,
            Func<GeneratorAttributeSyntaxContext, bool, CancellationToken, (TModel Member, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)?> transform)
    {
        return provider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName,
                WithKindCheck(kindPredicate, userPredicate),
                (context, cancellationToken) => transform(context, includeContainingTypeMembers, cancellationToken))
            .Where(static item => item is not null)
            .Select(static (item, _) => item!.Value)
            .WithTrackingName(trackingName);
    }

    // definition is the symbol the model and attributes come from: the definition part for a partial
    // member, the target itself otherwise. The implementation part's run drops out when another
    // declaration carries the attribute, since that one is necessarily the definition.
    private static (TModel Member, TypeModel ContainingType, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)?
        TransformMember<TModel>(
            GeneratorAttributeSyntaxContext context,
            ISymbol definition,
            bool isImplementationPart,
            TModel model,
            bool includeContainingTypeMembers,
            CancellationToken cancellationToken)
    {
        var markedAttributes = GetMarkedAttributes(definition, context);

        if (isImplementationPart && HasMarkedDeclarationOtherThan(markedAttributes, context.TargetNode))
        {
            return null;
        }

        var containingType = TypeModel.From(definition.ContainingType, includeContainingTypeMembers, cancellationToken);
        var syntaxInfo = SyntaxInfo.From(context.TargetNode);

        return (model, containingType, syntaxInfo, ToAttributeModels(markedAttributes));
    }

    // context.Attributes only holds the current node's applications; the other parts' come from the
    // symbol, filtered to the same attribute class.
    // OriginalDefinition so Mark<int> and Mark<string> on different parts count as one attribute.
    private static List<AttributeData> GetMarkedAttributes(ISymbol symbol, GeneratorAttributeSyntaxContext context)
    {
        var attributeClass = context.Attributes[0].AttributeClass?.OriginalDefinition;

        return symbol.GetAttributes()
            .Where(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass?.OriginalDefinition, attributeClass))
            .ToList();
    }

    private static EquatableArray<AttributeModel> ToAttributeModels(List<AttributeData> markedAttributes)
    {
        return markedAttributes
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();
    }

    private static bool HasMarkedDeclarationOtherThan(
        List<AttributeData> markedAttributes,
        SyntaxNode current)
    {
        foreach (var attribute in markedAttributes)
        {
            if (attribute.ApplicationSyntaxReference?.GetSyntax() is AttributeSyntax { Parent.Parent: { } declaration }
                && declaration != current)
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsFirstMarkedDeclaration(
        Compilation compilation,
        List<AttributeData> markedAttributes,
        TypeDeclarationSyntax current)
    {
        SyntaxTree? firstTree = null;
        var firstStart = 0;
        var firstOrdinal = int.MaxValue;

        foreach (var attribute in markedAttributes)
        {
            if (attribute.ApplicationSyntaxReference?.GetSyntax() is not AttributeSyntax { Parent.Parent: TypeDeclarationSyntax declaration })
            {
                continue;
            }

            var ordinal = OrdinalOf(compilation, declaration.SyntaxTree);
            var start = declaration.SpanStart;

            if (ordinal < firstOrdinal || (ordinal == firstOrdinal && start < firstStart))
            {
                firstTree = declaration.SyntaxTree;
                firstStart = start;
                firstOrdinal = ordinal;
            }
        }

        return firstTree is null
            || (firstTree == current.SyntaxTree && firstStart == current.SpanStart);
    }

    private static int OrdinalOf(Compilation compilation, SyntaxTree tree)
    {
        var ordinal = 0;

        foreach (var candidate in compilation.SyntaxTrees)
        {
            if (candidate == tree)
            {
                return ordinal;
            }

            ordinal++;
        }

        return int.MaxValue;
    }

    private static (TypeModel Type, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)? Transform(
        GeneratorAttributeSyntaxContext context,
        bool includeMembers,
        CancellationToken cancellationToken)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.TargetNode;
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        var markedAttributes = GetMarkedAttributes(typeSymbol, context);

        if (!IsFirstMarkedDeclaration(context.SemanticModel.Compilation, markedAttributes, typeDeclaration))
        {
            return null;
        }

        var typeModel = TypeModel.From(typeSymbol, includeMembers, cancellationToken);
        var syntaxInfo = SyntaxInfo.From(typeDeclaration);

        return (typeModel, syntaxInfo, ToAttributeModels(markedAttributes));
    }
}
