// <auto-generated/>
#nullable enable

using System.Collections.Generic;
using System.Linq;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Generators;

// Wraps ForAttributeWithMetadataName (Roslyn 4.3+) for the common case of finding types marked
// with a specific attribute. The predicate filters to TypeDeclarationSyntax: methods and
// properties are out of scope for this provider, and enums are never TypeDeclarationSyntax so
// they never match. The transform turns the matched node into value-equal models (TypeModel,
// SyntaxInfo, AttributeModel) that carry no live Roslyn objects, so the incremental cache can
// compare outputs across runs instead of always recomputing.
internal static class SyntaxValueProviderExtensions
{
    // ForAttributeWithMetadataName already matched by attribute name, so an unresolved
    // AttributeModel here would mean an error type despite that match (e.g. a broken
    // declaration); such entries are skipped rather than reported, matching TypeModel.From's
    // handling of its own incidental attribute list. Diagnostics for a bad match (e.g. an
    // unresolved attribute, or IsPartial being false) are the caller's decision, not this
    // provider's.
    //
    // A partial type marked on several declarations yields one item: ForAttributeWithMetadataName
    // runs the transform once per marked declaration, so each run keeps its result only when its
    // node is the first marked declaration (compilation tree order, then span start) and drops it
    // otherwise. No Collect() is involved, so unrelated edits still leave the step cached. The
    // attributes are the symbol's, i.e. those of every part.
    //
    // includeMembers fills TypeModel's Fields, Properties and Methods from the symbol (every part
    // contributes). It ties the item's equality to every member edit, so an edit to any member of
    // the type recomputes downstream steps; leave it off unless the generator reads members.
    public static IncrementalValuesProvider<(TypeModel Type, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)>
        ForTypesWithAttribute(
            this SyntaxValueProvider provider,
            string fullyQualifiedMetadataName,
            string trackingName,
            bool includeMembers = false)
    {
        return provider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: (context, _) => Transform(context, includeMembers))
            .Where(static item => item is not null)
            .Select(static (item, _) => item!.Value)
            .WithTrackingName(trackingName);
    }

    private static bool IsFirstMarkedDeclaration(
        Compilation compilation,
        List<AttributeData> markedAttributes,
        TypeDeclarationSyntax current)
    {
        SyntaxTree? firstTree = null;
        var firstStart = 0;
        var firstOrdinal = int.MaxValue;

        foreach (var attribute in markedAttributes)
        {
            if (attribute.ApplicationSyntaxReference?.GetSyntax() is not AttributeSyntax { Parent.Parent: TypeDeclarationSyntax declaration })
            {
                continue;
            }

            var ordinal = OrdinalOf(compilation, declaration.SyntaxTree);
            var start = declaration.SpanStart;

            if (ordinal < firstOrdinal || (ordinal == firstOrdinal && start < firstStart))
            {
                firstTree = declaration.SyntaxTree;
                firstStart = start;
                firstOrdinal = ordinal;
            }
        }

        return firstTree is null
            || (firstTree == current.SyntaxTree && firstStart == current.SpanStart);
    }

    private static int OrdinalOf(Compilation compilation, SyntaxTree tree)
    {
        var ordinal = 0;

        foreach (var candidate in compilation.SyntaxTrees)
        {
            if (candidate == tree)
            {
                return ordinal;
            }

            ordinal++;
        }

        return int.MaxValue;
    }

    private static (TypeModel Type, SyntaxInfo Syntax, EquatableArray<AttributeModel> Attributes)? Transform(
        GeneratorAttributeSyntaxContext context,
        bool includeMembers)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.TargetNode;
        var typeSymbol = (INamedTypeSymbol)context.TargetSymbol;

        // context.Attributes only holds the current node's applications; the other parts' come
        // from the symbol, filtered to the same attribute class.
        // OriginalDefinition so Mark<int> and Mark<string> on different parts count as one attribute.
        var attributeClass = context.Attributes[0].AttributeClass?.OriginalDefinition;
        var markedAttributes = typeSymbol.GetAttributes()
            .Where(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass?.OriginalDefinition, attributeClass))
            .ToList();

        if (!IsFirstMarkedDeclaration(context.SemanticModel.Compilation, markedAttributes, typeDeclaration))
        {
            return null;
        }

        var attributes = markedAttributes
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        var typeModel = TypeModel.From(typeSymbol, includeMembers);
        var syntaxInfo = SyntaxInfo.From(typeDeclaration);

        return (typeModel, syntaxInfo, attributes);
    }
}
