// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Types;

namespace Haitch.Roslyn.Models;

/// <summary>
/// An additional file with its text and the per-file metadata the generator asked for. Equatable
/// so the incremental pipeline stays cached while path, content and metadata are unchanged.
/// </summary>
/// <param name="Path">The file path as the compiler reports it.</param>
/// <param name="Content">The file text.</param>
/// <param name="Metadata">The requested <c>build_metadata.AdditionalFiles.*</c> values; unset or empty ones are null.</param>
internal sealed record AdditionalFileModel(
    string Path,
    string Content,
    EquatableArray<BuildProperty> Metadata
)
{
    /// <summary>Looks up a requested metadata value by name, ignoring case like the analyzer config does.</summary>
    /// <param name="name">The metadata name, without the <c>build_metadata.AdditionalFiles.</c> prefix.</param>
    /// <param name="value">The value, or null when the name was not requested or the value is empty.</param>
    /// <returns>True when the name was requested and has a non-empty value.</returns>
    public bool TryGetMetadata(string name, out string? value)
    {
        foreach (var item in Metadata)
        {
            if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                value = item.Value;
                return value is not null;
            }
        }

        value = null;
        return false;
    }

    /// <summary>Gets a requested metadata value, or null for an unrequested or empty one.</summary>
    /// <param name="name">The metadata name, without the <c>build_metadata.AdditionalFiles.</c> prefix.</param>
    public string? this[string name] => TryGetMetadata(name, out var value) ? value : null;
}
