// <auto-generated/>
#nullable enable

using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal sealed record NamedArgument(string Name, ConstantValue Value);

internal sealed record AttributeModel(
    TypeRef AttributeType,
    EquatableArray<ConstantValue> ConstructorArguments,
    EquatableArray<NamedArgument> NamedArguments)
{
    public static AttributeModel? From(AttributeData attributeData)
    {
        INamedTypeSymbol? attributeClass = attributeData.AttributeClass;

        if (attributeClass is null || attributeClass.TypeKind == TypeKind.Error)
        {
            return null;
        }

        var attributeType = TypeRef.From(attributeClass);

        var constructorArguments = attributeData.ConstructorArguments
            .Select(ConstantValue.From)
            .ToEquatableArray();

        var namedArguments = attributeData.NamedArguments
            .Select(pair => new NamedArgument(pair.Key, ConstantValue.From(pair.Value)))
            .ToEquatableArray();

        return new AttributeModel(attributeType, constructorArguments, namedArguments);
    }
}
