// <auto-generated/>
#nullable enable

using Haitch.Roslyn.Types;

namespace Haitch.Roslyn.Models;

internal static class AttributeModelExtensions
{
    /// <summary>
    /// Finds the attribute whose <see cref="AttributeModel.MetadataName"/> equals
    /// <paramref name="fullyQualifiedMetadataName"/> ordinally, or null.
    /// </summary>
    public static AttributeModel? Find(
        this EquatableArray<AttributeModel> attributes,
        string fullyQualifiedMetadataName)
    {
        foreach (var attribute in attributes)
        {
            if (string.Equals(attribute.MetadataName, fullyQualifiedMetadataName, System.StringComparison.Ordinal))
            {
                return attribute;
            }
        }

        return null;
    }
}
