// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Types;

namespace Haitch.Roslyn.Models;

/// <summary>A single MSBuild build property read from the analyzer config, with a null value when it is unset or blank.</summary>
internal sealed record BuildProperty(string Name, string? Value);

/// <summary>
/// A set of MSBuild build properties read together. Equatable so the incremental pipeline stays
/// cached while the values are unchanged.
/// </summary>
internal sealed record BuildProperties(EquatableArray<BuildProperty> Items)
{
    /// <summary>Looks up a property by name, ignoring case like the analyzer config does.</summary>
    /// <param name="name">The property name, without the <c>build_property.</c> prefix.</param>
    /// <param name="value">The value, or null when the name is unknown or the property is blank.</param>
    /// <returns>True when the name was requested and has a non-blank value.</returns>
    public bool TryGet(string name, out string? value)
    {
        foreach (var item in Items)
        {
            if (string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                value = item.Value;
                return value is not null;
            }
        }

        value = null;
        return false;
    }

    /// <summary>Gets the value of <paramref name="name"/>, or null for an unknown or blank property.</summary>
    /// <param name="name">The property name, without the <c>build_property.</c> prefix.</param>
    public string? this[string name] => TryGet(name, out var value) ? value : null;
}
