// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal enum ConstantValueKind
{
    Null,
    Primitive,
    String,
    Enum,
    Type,
    Array,
    Error
}

internal sealed record ConstantValue
{
    public static readonly ConstantValue Error = new(ConstantValueKind.Error, null, null, default, null);

    private ConstantValue(
        ConstantValueKind kind,
        object? value,
        TypeRef? type,
        EquatableArray<ConstantValue> elements,
        string? enumMemberName)
    {
        Kind = kind;
        Value = value;
        Type = type;
        Elements = elements;
        EnumMemberName = enumMemberName;
    }

    public ConstantValueKind Kind { get; }

    public object? Value { get; }

    public TypeRef? Type { get; }

    public EquatableArray<ConstantValue> Elements { get; }

    /// <summary>
    /// For an enum constant, the name of the single declared member with this value; <see langword="null"/>
    /// for flag combinations, undefined values and aliased values.
    /// </summary>
    public string? EnumMemberName { get; }

    public bool IsNull => Kind == ConstantValueKind.Null;

    public bool TryGetString(out string value)
    {
        if (Kind == ConstantValueKind.String && Value is string text)
        {
            value = text;
            return true;
        }

        value = "";
        return false;
    }

    public bool TryGetBoolean(out bool value)
    {
        return TryGetPrimitive(out value);
    }

    public bool TryGetInt32(out int value)
    {
        return TryGetPrimitive(out value);
    }

    public bool TryGetInt64(out long value)
    {
        return TryGetPrimitive(out value);
    }

    public bool TryGetDouble(out double value)
    {
        return TryGetPrimitive(out value);
    }

    public bool TryGetEnum<TEnum>(out TEnum value)
        where TEnum : struct, Enum
    {
        // Roslyn only reports integral underlying values, but a hand-built ForEnum can hold anything,
        // and Enum.ToObject throws on those.
        if (
            Kind == ConstantValueKind.Enum
            && Value is not null
            && System.Type.GetTypeCode(Value.GetType())
                is System.TypeCode.SByte
                    or System.TypeCode.Byte
                    or System.TypeCode.Int16
                    or System.TypeCode.UInt16
                    or System.TypeCode.Int32
                    or System.TypeCode.UInt32
                    or System.TypeCode.Int64
                    or System.TypeCode.UInt64
        )
        {
            value = (TEnum)Enum.ToObject(typeof(TEnum), Value);
            return true;
        }

        value = default;
        return false;
    }

    public bool TryGetType(out TypeRef value)
    {
        if (Kind == ConstantValueKind.Type && Type is not null)
        {
            value = Type;
            return true;
        }

        value = null!;
        return false;
    }

    public bool TryGetArray(out EquatableArray<ConstantValue> value)
    {
        value = Elements;
        return Kind == ConstantValueKind.Array;
    }

    public bool TryGetStringArray(out EquatableArray<string?> value)
    {
        value = default;

        if (Kind != ConstantValueKind.Array)
        {
            return false;
        }

        var items = new string?[Elements.Count];

        for (var i = 0; i < items.Length; i++)
        {
            ConstantValue element = Elements[i];

            if (element.Kind == ConstantValueKind.String)
            {
                items[i] = (string)element.Value!;
            }
            else if (element.Kind != ConstantValueKind.Null)
            {
                return false;
            }
        }

        value = new EquatableArray<string?>(items);
        return true;
    }

    // Exact CLR type match on purpose: a long argument must not satisfy TryGetInt32.
    private bool TryGetPrimitive<T>(out T value)
        where T : struct
    {
        if (Kind == ConstantValueKind.Primitive && Value is T typed)
        {
            value = typed;
            return true;
        }

        value = default;
        return false;
    }

    public static ConstantValue ForNull(TypeRef? type)
    {
        return new ConstantValue(ConstantValueKind.Null, null, type, default, null);
    }

    public static ConstantValue ForPrimitive(object value)
    {
        return new ConstantValue(ConstantValueKind.Primitive, value, null, default, null);
    }

    public static ConstantValue ForString(string value)
    {
        return new ConstantValue(ConstantValueKind.String, value, null, default, null);
    }

    public static ConstantValue ForEnum(TypeRef type, object underlyingValue, string? memberName = null)
    {
        return new ConstantValue(ConstantValueKind.Enum, underlyingValue, type, default, memberName);
    }

    public static ConstantValue ForType(TypeRef type)
    {
        return new ConstantValue(ConstantValueKind.Type, null, type, default, null);
    }

    public static ConstantValue ForArray(TypeRef? type, EquatableArray<ConstantValue> elements)
    {
        return new ConstantValue(ConstantValueKind.Array, null, type, elements, null);
    }

    public static ConstantValue From(TypedConstant constant)
    {
        // A bad argument expression (e.g. a typo) yields Kind.Error; constant.Value and
        // constant.IsNull are not safe to read for it, so it is handled before anything else.
        if (constant.Kind == TypedConstantKind.Error)
        {
            return Error;
        }

        TypeRef? type = constant.Type is null ? null : TypeRef.From(constant.Type);

        if (constant.IsNull)
        {
            return ForNull(type);
        }

        return constant.Kind switch
        {
            TypedConstantKind.Primitive when constant.Value is string stringValue => ForString(stringValue),
            TypedConstantKind.Primitive => ForPrimitive(constant.Value!),
            TypedConstantKind.Enum => ForEnum(type!, constant.Value!, FindEnumMemberName(constant)),
            TypedConstantKind.Type => ForType(TypeRef.From((ITypeSymbol)constant.Value!)),
            TypedConstantKind.Array => ForArray(type, constant.Values.Select(From).ToEquatableArray()),
            _ => throw new ArgumentOutOfRangeException(nameof(constant), constant.Kind, "Unsupported typed constant kind."),
        };
    }

    private static string? FindEnumMemberName(TypedConstant constant)
    {
        if (constant.Type is not INamedTypeSymbol enumType)
        {
            return null;
        }

        string? name = null;

        foreach (ISymbol member in enumType.GetMembers())
        {
            if (member is not IFieldSymbol { IsConst: true, HasConstantValue: true } field
                || !Equals(field.ConstantValue, constant.Value))
            {
                continue;
            }

            if (name is not null)
            {
                return null;
            }

            name = field.Name;
        }

        return name;
    }
}
