// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal enum ConstantValueKind
{
    Null,
    Primitive,
    String,
    Enum,
    Type,
    Array,
    Error
}

internal sealed record ConstantValue
{
    public static readonly ConstantValue Error = new(ConstantValueKind.Error, null, null, default, null);

    private ConstantValue(
        ConstantValueKind kind,
        object? value,
        TypeRef? type,
        EquatableArray<ConstantValue> elements,
        string? enumMemberName)
    {
        Kind = kind;
        Value = value;
        Type = type;
        Elements = elements;
        EnumMemberName = enumMemberName;
    }

    public ConstantValueKind Kind { get; }

    public object? Value { get; }

    public TypeRef? Type { get; }

    public EquatableArray<ConstantValue> Elements { get; }

    /// <summary>
    /// For an enum constant, the name of the single declared member with this value; <see langword="null"/>
    /// for flag combinations, undefined values and aliased values.
    /// </summary>
    public string? EnumMemberName { get; }

    public static ConstantValue ForNull(TypeRef? type)
    {
        return new ConstantValue(ConstantValueKind.Null, null, type, default, null);
    }

    public static ConstantValue ForPrimitive(object value)
    {
        return new ConstantValue(ConstantValueKind.Primitive, value, null, default, null);
    }

    public static ConstantValue ForString(string value)
    {
        return new ConstantValue(ConstantValueKind.String, value, null, default, null);
    }

    public static ConstantValue ForEnum(TypeRef type, object underlyingValue, string? memberName = null)
    {
        return new ConstantValue(ConstantValueKind.Enum, underlyingValue, type, default, memberName);
    }

    public static ConstantValue ForType(TypeRef type)
    {
        return new ConstantValue(ConstantValueKind.Type, null, type, default, null);
    }

    public static ConstantValue ForArray(TypeRef? type, EquatableArray<ConstantValue> elements)
    {
        return new ConstantValue(ConstantValueKind.Array, null, type, elements, null);
    }

    public static ConstantValue From(TypedConstant constant)
    {
        // A bad argument expression (e.g. a typo) yields Kind.Error; constant.Value and
        // constant.IsNull are not safe to read for it, so it is handled before anything else.
        if (constant.Kind == TypedConstantKind.Error)
        {
            return Error;
        }

        TypeRef? type = constant.Type is null ? null : TypeRef.From(constant.Type);

        if (constant.IsNull)
        {
            return ForNull(type);
        }

        return constant.Kind switch
        {
            TypedConstantKind.Primitive when constant.Value is string stringValue => ForString(stringValue),
            TypedConstantKind.Primitive => ForPrimitive(constant.Value!),
            TypedConstantKind.Enum => ForEnum(type!, constant.Value!, FindEnumMemberName(constant)),
            TypedConstantKind.Type => ForType(TypeRef.From((ITypeSymbol)constant.Value!)),
            TypedConstantKind.Array => ForArray(type, constant.Values.Select(From).ToEquatableArray()),
            _ => throw new ArgumentOutOfRangeException(nameof(constant), constant.Kind, "Unsupported typed constant kind."),
        };
    }

    private static string? FindEnumMemberName(TypedConstant constant)
    {
        if (constant.Type is not INamedTypeSymbol enumType)
        {
            return null;
        }

        string? name = null;

        foreach (ISymbol member in enumType.GetMembers())
        {
            if (member is not IFieldSymbol { IsConst: true, HasConstantValue: true } field
                || !Equals(field.ConstantValue, constant.Value))
            {
                continue;
            }

            if (name is not null)
            {
                return null;
            }

            name = field.Name;
        }

        return name;
    }
}
