// <auto-generated/>
#nullable enable

using System.Linq;
using System.Threading;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Models;

/// <summary>
/// Captures an <see cref="IEventSymbol"/> declaration as value-equal data.
/// </summary>
/// <param name="Name">The event name; for an explicit implementation, the unqualified member name.</param>
/// <param name="Type">The delegate type, including its nullable annotation.</param>
/// <param name="Accessibility">The declared accessibility.</param>
/// <param name="IsStatic">True when the event is declared static.</param>
/// <param name="IsFieldLike">
/// True when the add and remove accessors are implicitly declared (<c>event EventHandler E;</c>), false
/// when the author wrote them out. Always false for an event read from metadata (a referenced assembly),
/// where accessors are never implicitly declared, so the two forms cannot be told apart. Always false for a
/// partial event (see <see cref="IsPartial"/>).
/// </param>
internal sealed record EventModel(
    string Name,
    TypeRef Type,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsFieldLike)
{
    /// <summary>
    /// The interface an explicit implementation (<c>event EventHandler IFoo.E { add; remove; }</c>)
    /// implements; null for every other event. <see cref="Name"/> stays the unqualified member name either way.
    /// </summary>
    public TypeRef? ExplicitInterface { get; init; }

    /// <summary>
    /// The implemented interface member's name; null unless <see cref="ExplicitInterface"/> is set.
    /// </summary>
    public string? ExplicitInterfaceMemberName { get; init; }

    public bool IsAbstract { get; init; }

    public bool IsVirtual { get; init; }

    public bool IsOverride { get; init; }

    public bool IsSealed { get; init; }

    /// <summary>
    /// True for a C# 14 partial event: the defining and implementing declarations together are one event,
    /// so a single model is produced and <see cref="IsFieldLike"/> is false (the implementation writes the
    /// accessors out).
    /// </summary>
    public bool IsPartial { get; init; }

    /// <summary>
    /// The attributes applied to the event itself; attributes targeting its accessors or backing field
    /// (<c>[field: ...]</c>) are not included.
    /// </summary>
    public EquatableArray<AttributeModel> Attributes { get; init; }

    /// <summary>
    /// Builds an <see cref="EventModel"/> from <paramref name="evt"/>.
    /// </summary>
    /// <param name="evt">The event to capture.</param>
    /// <param name="cancellationToken">
    /// Checked on entry; cancellation throws <see cref="System.OperationCanceledException"/>.
    /// </param>
    public static EventModel From(IEventSymbol evt, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var isPartial = IsPartialEvent(evt, cancellationToken);
        var explicitInterfaceEvent = evt.ExplicitInterfaceImplementations.FirstOrDefault();

        var attributes = evt.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        return new EventModel(
            // Roslyn names an explicit implementation "IFoo.E"; the model carries the interface separately.
            explicitInterfaceEvent?.Name ?? evt.Name,
            TypeRef.From(evt.Type),
            evt.DeclaredAccessibility,
            evt.IsStatic,
            // Field-like events get compiler-synthesized accessors; written-out ones do not. A partial event is
            // never field-like: Roslyn can hand back the defining part, whose accessors look synthesized, but
            // the implementing part always writes them out.
            !isPartial && (evt.AddMethod?.IsImplicitlyDeclared ?? false))
        {
            ExplicitInterface = explicitInterfaceEvent is null
                ? null
                : TypeRef.From(explicitInterfaceEvent.ContainingType),
            ExplicitInterfaceMemberName = explicitInterfaceEvent?.Name,
            IsAbstract = evt.IsAbstract,
            IsVirtual = evt.IsVirtual,
            IsOverride = evt.IsOverride,
            IsSealed = evt.IsSealed,
            IsPartial = isPartial,
            Attributes = attributes,
        };
    }

    // IEventSymbol.IsPartialDefinition and PartialImplementationPart arrived after Roslyn 4.12, so read the
    // modifier from syntax; a metadata event never has partial syntax.
    private static bool IsPartialEvent(IEventSymbol evt, CancellationToken cancellationToken)
    {
        foreach (var reference in evt.DeclaringSyntaxReferences)
        {
            var syntax = reference.GetSyntax(cancellationToken);

            // A field-like declaration (including a partial definition) is reported as its declarator.
            var declaration = syntax is VariableDeclaratorSyntax declarator ? declarator.Parent?.Parent : syntax;

            var modifiers = declaration switch
            {
                EventDeclarationSyntax accessorForm => accessorForm.Modifiers,
                EventFieldDeclarationSyntax fieldForm => fieldForm.Modifiers,
                _ => default,
            };

            if (modifiers.Any(SyntaxKind.PartialKeyword))
            {
                return true;
            }
        }

        return false;
    }
}
