// <auto-generated/>
#nullable enable

using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal sealed record FieldModel(
    string Name,
    TypeRef Type,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsReadOnly,
    bool IsConst,
    bool IsRequired,
    ConstantValue? ConstantValue,
    EquatableArray<AttributeModel> Attributes)
{
    /// <summary>
    /// Whether the field is declared <c>volatile</c>.
    /// </summary>
    public bool IsVolatile { get; init; }

    public static FieldModel From(IFieldSymbol field)
    {
        var attributes = field.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        return new FieldModel(
            field.Name,
            TypeRef.From(field.Type),
            field.DeclaredAccessibility,
            field.IsStatic,
            field.IsReadOnly,
            field.IsConst,
            field.IsRequired,
            GetConstantValue(field),
            attributes)
        {
            IsVolatile = field.IsVolatile,
        };
    }

    // Field constants are exposed as a raw CLR value (ConstantValue), not a TypedConstant,
    // so they are converted by hand instead of via Models.ConstantValue.From.
    private static Models.ConstantValue? GetConstantValue(IFieldSymbol field)
    {
        if (!field.HasConstantValue)
        {
            return null;
        }

        var value = field.ConstantValue;

        if (value is null)
        {
            return Models.ConstantValue.ForNull(TypeRef.From(field.Type));
        }

        if (field.Type.TypeKind == TypeKind.Enum)
        {
            return Models.ConstantValue.ForEnum(TypeRef.From(field.Type), value);
        }

        if (value is string stringValue)
        {
            return Models.ConstantValue.ForString(stringValue);
        }

        return Models.ConstantValue.ForPrimitive(value);
    }
}
