// <auto-generated/>
#nullable enable

using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Models;

internal enum ReturnRefKind
{
    None,
    Ref,
    RefReadOnly
}

internal sealed record MethodModel(
    string Name,
    MethodKind MethodKind,
    TypeRef ReturnType,
    ReturnRefKind ReturnRefKind,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsAbstract,
    bool IsVirtual,
    bool IsOverride,
    bool IsSealed,
    bool IsAsync,
    bool IsExtern,
    bool IsExtensionMethod,
    bool IsPartialDefinition,
    bool IsReadOnly,
    TypeRef? ExplicitInterface,
    string? ExplicitInterfaceMemberName,
    EquatableArray<TypeParameterModel> TypeParameters,
    EquatableArray<ParameterModel> Parameters,
    EquatableArray<AttributeModel> Attributes)
{
    /// <summary>
    /// Whether the declaring syntax names an access modifier. False only for a partial method written
    /// without one (for example <c>partial void OnX();</c>), whose implementation must also omit it
    /// even though Roslyn reports <see cref="Accessibility.Private"/>. True for every other method.
    /// </summary>
    public bool HasExplicitAccessibility { get; init; } = true;

    public static MethodModel From(IMethodSymbol method)
    {
        var returnRefKind = method.ReturnsByRefReadonly
            ? ReturnRefKind.RefReadOnly
            : method.ReturnsByRef
                ? ReturnRefKind.Ref
                : ReturnRefKind.None;

        var typeParameters = method.TypeParameters
            .Select(TypeParameterModel.From)
            .ToEquatableArray();

        var parameters = method.Parameters
            .Select(ParameterModel.From)
            .ToEquatableArray();

        var attributes = method.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        var explicitInterfaceMethod = method.ExplicitInterfaceImplementations.FirstOrDefault();

        return new MethodModel(
            method.Name,
            method.MethodKind,
            TypeRef.From(method.ReturnType),
            returnRefKind,
            method.DeclaredAccessibility,
            method.IsStatic,
            method.IsAbstract,
            method.IsVirtual,
            method.IsOverride,
            method.IsSealed,
            method.IsAsync,
            method.IsExtern,
            method.IsExtensionMethod,
            method.IsPartialDefinition,
            method.IsReadOnly,
            explicitInterfaceMethod is null ? null : TypeRef.From(explicitInterfaceMethod.ContainingType),
            explicitInterfaceMethod?.Name,
            typeParameters,
            parameters,
            attributes)
        {
            HasExplicitAccessibility = !IsPartial(method) || HasAccessModifier(method.PartialDefinitionPart ?? method),
        };
    }

    private static bool IsPartial(IMethodSymbol method)
    {
        return method.IsPartialDefinition || method.PartialDefinitionPart is not null;
    }

    private static bool HasAccessModifier(IMethodSymbol method)
    {
        foreach (var reference in method.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is not MethodDeclarationSyntax declaration)
            {
                continue;
            }

            return declaration.Modifiers.Any(m =>
                m.IsKind(SyntaxKind.PublicKeyword)
                || m.IsKind(SyntaxKind.PrivateKeyword)
                || m.IsKind(SyntaxKind.ProtectedKeyword)
                || m.IsKind(SyntaxKind.InternalKeyword));
        }

        return true;
    }
}
