// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Models;

internal enum PropertyAccessorKind
{
    Get,
    Set,
    Init
}

internal sealed record PropertyAccessorModel(PropertyAccessorKind Kind, Accessibility Accessibility)
{
    /// <summary>
    /// Whether the accessor itself carries the <c>readonly</c> modifier (for example <c>readonly get;</c>).
    /// A property-level <c>readonly</c> is <see cref="PropertyModel.IsReadOnly"/> instead.
    /// </summary>
    public bool IsReadOnly { get; init; }
}

internal sealed record PropertyModel(
    string Name,
    TypeRef Type,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsRequired,
    bool IsAbstract,
    bool IsVirtual,
    bool IsOverride,
    bool IsSealed,
    bool IsPartial,
    bool IsReadOnly,
    EquatableArray<PropertyAccessorModel> Accessors,
    EquatableArray<AttributeModel> Attributes)
{
    /// <summary>
    /// Whether the declaring syntax names an access modifier. False only for a partial property written
    /// without one (for example <c>partial string Y { get; }</c>), whose implementation must also omit it
    /// even though Roslyn reports <see cref="Accessibility.Private"/>. True for every other property.
    /// </summary>
    public bool HasExplicitAccessibility { get; init; } = true;

    /// <summary>
    /// The interface an explicit implementation (<c>int IFoo.Bar { get; }</c>) implements; null for every
    /// other property. <see cref="Name"/> stays the unqualified member name either way.
    /// </summary>
    public TypeRef? ExplicitInterface { get; init; }

    /// <summary>
    /// The implemented interface member's name; null unless <see cref="ExplicitInterface"/> is set.
    /// </summary>
    public string? ExplicitInterfaceMemberName { get; init; }

    /// <summary>
    /// How the property returns its value: <see cref="Models.ReturnRefKind.Ref"/> for <c>ref</c>,
    /// <see cref="Models.ReturnRefKind.RefReadOnly"/> for <c>ref readonly</c>, and
    /// <see cref="Models.ReturnRefKind.None"/> otherwise; the same enum <see cref="MethodModel"/> uses.
    /// </summary>
    public ReturnRefKind ReturnRefKind { get; init; }

    public static PropertyModel From(IPropertySymbol property)
    {
        if (property.IsIndexer)
        {
            throw new ArgumentException("PropertyModel does not support indexers.", nameof(property));
        }

        var accessors = new List<PropertyAccessorModel>(2);

        var isPartial = IsPartialProperty(property);
        var syntaxProperty = isPartial ? property.PartialDefinitionPart ?? property : property;

        if (property.GetMethod is { } getMethod)
        {
            accessors.Add(
                new PropertyAccessorModel(PropertyAccessorKind.Get, getMethod.DeclaredAccessibility)
                {
                    IsReadOnly = AccessorWritesReadOnly(syntaxProperty, SyntaxKind.GetKeyword),
                });
        }

        if (property.SetMethod is { } setMethod)
        {
            var kind = setMethod.IsInitOnly ? PropertyAccessorKind.Init : PropertyAccessorKind.Set;
            accessors.Add(
                new PropertyAccessorModel(kind, setMethod.DeclaredAccessibility)
                {
                    IsReadOnly = AccessorWritesReadOnly(
                        syntaxProperty,
                        setMethod.IsInitOnly ? SyntaxKind.InitKeyword : SyntaxKind.SetKeyword),
                });
        }

        var attributes = property.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        var explicitInterfaceProperty = property.ExplicitInterfaceImplementations.FirstOrDefault();

        return new PropertyModel(
            // Roslyn names an explicit implementation "IFoo.Bar"; the model carries the interface separately.
            explicitInterfaceProperty?.Name ?? property.Name,
            TypeRef.From(property.Type),
            property.DeclaredAccessibility,
            property.IsStatic,
            property.IsRequired,
            property.IsAbstract,
            property.IsVirtual,
            property.IsOverride,
            property.IsSealed,
            isPartial,
            IsReadOnlyMember(property, syntaxProperty, isPartial),
            accessors.ToEquatableArray(),
            attributes)
        {
            HasExplicitAccessibility = !isPartial || HasAccessModifier(syntaxProperty),
            ReturnRefKind = property.ReturnsByRefReadonly
                ? ReturnRefKind.RefReadOnly
                : property.ReturnsByRef
                    ? ReturnRefKind.Ref
                    : ReturnRefKind.None,
            ExplicitInterface = explicitInterfaceProperty is null
                ? null
                : TypeRef.From(explicitInterfaceProperty.ContainingType),
            ExplicitInterfaceMemberName = explicitInterfaceProperty?.Name,
        };
    }

    private static bool IsPartialProperty(IPropertySymbol property)
    {
        return property.IsPartialDefinition || property.PartialDefinitionPart is not null;
    }

    // IPropertySymbol.IsReadOnly means "has no setter", so the property-level readonly modifier is read from
    // syntax. Accessor-level readonly is PropertyAccessorModel.IsReadOnly. Without syntax (metadata) the
    // accessors are all that is left: readonly when every one is, unless a readonly struct implies it.
    private static bool IsReadOnlyMember(IPropertySymbol property, IPropertySymbol syntaxProperty, bool isPartial)
    {
        foreach (var reference in syntaxProperty.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is PropertyDeclarationSyntax declaration)
            {
                // A readonly struct implies readonly on its members, but a partial implementation must still
                // repeat a modifier the definition wrote.
                return declaration.Modifiers.Any(SyntaxKind.ReadOnlyKeyword)
                    && (isPartial || property.ContainingType is not { IsReadOnly: true });
            }
        }

        if (property.ContainingType is { IsReadOnly: true })
        {
            return false;
        }

        var any = false;

        foreach (var accessor in new[] { property.GetMethod, property.SetMethod })
        {
            if (accessor is null)
            {
                continue;
            }

            if (!accessor.IsReadOnly)
            {
                return false;
            }

            any = true;
        }

        return any;
    }

    // Roslyn also reports the getter of a get-only auto-property in a struct as readonly, though the
    // author never wrote the modifier; only the syntax tells the two apart.
    private static bool AccessorWritesReadOnly(IPropertySymbol property, SyntaxKind keyword)
    {
        foreach (var reference in property.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is not PropertyDeclarationSyntax declaration)
            {
                continue;
            }

            return declaration.AccessorList is { } list
                && list.Accessors.Any(a => a.Keyword.IsKind(keyword) && a.Modifiers.Any(SyntaxKind.ReadOnlyKeyword));
        }

        return false;
    }

    private static bool HasAccessModifier(IPropertySymbol property)
    {
        foreach (var reference in property.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is not PropertyDeclarationSyntax declaration)
            {
                continue;
            }

            return declaration.Modifiers.Any(m =>
                m.IsKind(SyntaxKind.PublicKeyword)
                || m.IsKind(SyntaxKind.PrivateKeyword)
                || m.IsKind(SyntaxKind.ProtectedKeyword)
                || m.IsKind(SyntaxKind.InternalKeyword));
        }

        return true;
    }
}
