// <auto-generated/>
#nullable enable

using Haitch.Roslyn.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Models;

internal sealed record SyntaxInfo(bool IsPartial, bool AreContainingTypesPartial, LocationInfo? Location)
{
    public static SyntaxInfo From(TypeDeclarationSyntax typeDeclaration)
    {
        var isPartial = typeDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword);
        var areContainingTypesPartial = true;
        SyntaxNode? current = typeDeclaration.Parent;

        while (current is TypeDeclarationSyntax type)
        {
            if (!type.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                areContainingTypesPartial = false;
                break;
            }

            current = type.Parent;
        }

        LocationInfo? location = LocationInfo.From(typeDeclaration.Identifier.GetLocation());

        return new SyntaxInfo(isPartial, areContainingTypesPartial, location);
    }
}
