// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal sealed record TypeRef(
    string FullyQualifiedName,
    NullableAnnotation NullableAnnotation,
    SpecialType SpecialType,
    TypeKind TypeKind,
    bool IsValueType)
{
    private static readonly SymbolDisplayFormat Format = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public static TypeRef From(ITypeSymbol type)
    {
        var fullyQualifiedName = type.ToDisplayString(Format);

        return new TypeRef(fullyQualifiedName, type.NullableAnnotation, type.SpecialType, type.TypeKind, type.IsValueType);
    }
}
