// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Haitch.Roslyn.Models;

internal enum TypeDeclarationKind
{
    Class,
    RecordClass,
    Struct,
    RecordStruct,
    Interface,
    Union
}

internal static class TypeDeclarationKindFactory
{
    public static TypeDeclarationKind From(INamedTypeSymbol type)
    {
        if (IsExtensionBlock(type))
        {
            throw new ArgumentException(
                $"TypeModel does not support extension blocks ('{type.Name}'); model the containing static class instead.",
                nameof(type));
        }

        return type.TypeKind switch
        {
            TypeKind.Struct when IsUnion(type) => TypeDeclarationKind.Union,
            TypeKind.Struct => type.IsRecord ? TypeDeclarationKind.RecordStruct : TypeDeclarationKind.Struct,
            TypeKind.Interface => TypeDeclarationKind.Interface,
            TypeKind.Class => type.IsRecord ? TypeDeclarationKind.RecordClass : TypeDeclarationKind.Class,
            _ => throw new ArgumentException(
                $"TypeModel does not support '{type.TypeKind}' declarations (e.g. enums and delegates); "
                    + "only classes, records, structs, record structs, and interfaces are modeled.",
                nameof(type)),
        };
    }

    // Compared by name because Roslyn 4.12 has no TypeKind.Extension; unlike the declaring syntax, the
    // kind is also reported for blocks loaded from metadata.
    public static bool IsExtensionBlock(INamedTypeSymbol type)
    {
        return type.TypeKind.ToString() == "Extension";
    }

    // Roslyn 4.12 has no TypeKind or symbol API for unions, so source types are read from the declaring
    // keyword and metadata types from UnionAttribute. IUnion is deliberately not used: hand-written structs
    // may implement it and must keep being written as `partial struct`.
    public static bool IsUnion(INamedTypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Struct && type.TypeKind != TypeKind.Class)
        {
            return false;
        }

        if (type.DeclaringSyntaxReferences.Length > 0)
        {
            foreach (var reference in type.DeclaringSyntaxReferences)
            {
                if (
                    reference.GetSyntax() is TypeDeclarationSyntax declaration
                    && declaration.Keyword.ValueText == "union"
                )
                {
                    return true;
                }
            }

            return false;
        }

        return type.GetAttributes()
            .Any(attribute =>
                attribute.AttributeClass is { Name: "UnionAttribute" } attributeClass
                && attributeClass.ContainingNamespace.ToDisplayString() == "System.Runtime.CompilerServices"
            );
    }
}

internal static class ClosedTypeDetector
{
    // Looked up on the interface because Roslyn's public symbol wrappers implement it explicitly.
    private static readonly PropertyInfo? IsClosedProperty = typeof(ITypeSymbol).GetProperty(
        "IsClosed",
        BindingFlags.Public | BindingFlags.Instance);

    // The compiler hides IsClosedTypeAttribute, and Roslyn 4.12 has no ITypeSymbol.IsClosed, so source
    // types are read from syntax and metadata types from the host symbol's IsClosed property by reflection.
    public static bool IsClosed(INamedTypeSymbol type)
    {
        foreach (var reference in type.DeclaringSyntaxReferences)
        {
            if (
                reference.GetSyntax() is TypeDeclarationSyntax declaration
                && declaration.Modifiers.Any(modifier => modifier.ValueText == "closed")
            )
            {
                return true;
            }
        }

        return IsClosedProperty?.PropertyType == typeof(bool) && IsClosedProperty.GetValue(type) is true;
    }
}

/// <summary>
/// Captures an <see cref="INamedTypeSymbol"/> declaration as value-equal data.
/// </summary>
/// <param name="Namespace">The containing namespace, or null for the global namespace.</param>
/// <param name="Name">The simple type name.</param>
/// <param name="Kind">The declaration kind (class, record, struct, record struct or interface).</param>
/// <param name="Accessibility">The declared accessibility.</param>
/// <param name="IsStatic">True when the type is declared static.</param>
/// <param name="IsAbstract">
/// True when the type is declared abstract. Interfaces always report <see langword="true"/> here even
/// though the <c>abstract</c> keyword is never written on an interface; a renderer emitting a partial
/// declaration must not echo this back for an interface.
/// </param>
/// <param name="IsSealed">
/// True when the type is sealed. Structs always report <see langword="true"/> here even though the
/// <c>sealed</c> keyword is never written on a struct; a renderer emitting a partial declaration must not
/// echo this back for a struct.
/// </param>
/// <param name="IsReadOnly">True when the type is a readonly struct.</param>
/// <param name="IsRefLikeType">True when the type is a ref struct.</param>
/// <param name="IsFileLocal">True when the type is declared with the file modifier.</param>
/// <param name="TypeParameters">The type's generic parameters.</param>
/// <param name="ContainingTypes">The enclosing types, outermost first.</param>
/// <param name="Attributes">The attributes applied to the type.</param>
/// <param name="Fields">The captured fields; empty unless members were included.</param>
/// <param name="Properties">The captured properties; empty unless members were included.</param>
/// <param name="Methods">The captured methods; empty unless members were included.</param>
internal sealed record TypeModel(
    string? Namespace,
    string Name,
    TypeDeclarationKind Kind,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsAbstract,
    bool IsSealed,
    bool IsReadOnly,
    bool IsRefLikeType,
    bool IsFileLocal,
    EquatableArray<TypeParameterModel> TypeParameters,
    EquatableArray<ContainingTypeModel> ContainingTypes,
    EquatableArray<AttributeModel> Attributes,
    EquatableArray<FieldModel> Fields,
    EquatableArray<PropertyModel> Properties,
    EquatableArray<MethodModel> Methods)
{
    /// <summary>
    /// The case types of a union, in declaration order; empty for every other kind.
    /// </summary>
    public EquatableArray<TypeRef> UnionCaseTypes { get; init; }

    /// <summary>
    /// True for a <c>closed</c> class or record. <see cref="IsAbstract"/> is also true for such a type, and
    /// a renderer emitting a partial declaration must echo neither modifier.
    /// </summary>
    public bool IsClosed { get; init; }

    /// <summary>
    /// Builds a <see cref="TypeModel"/> from <paramref name="type"/>. Member arrays are left empty
    /// unless <paramref name="includeMembers"/> is true, since capturing every member ties the model's
    /// equality (and so incremental generator cache validity) to any edit of any member.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is an enum, delegate, or other kind <see cref="TypeModel"/> does not model.
    /// </exception>
    public static TypeModel From(INamedTypeSymbol type, bool includeMembers = false)
    {
        var typeParameters = type.TypeParameters
            .Select(TypeParameterModel.From)
            .ToEquatableArray();

        var attributes = type.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        var fields = includeMembers
            ? type.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(field => !field.IsImplicitlyDeclared)
                .Select(FieldModel.From)
                .ToEquatableArray()
            : default;

        var properties = includeMembers
            ? type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(property => !property.IsImplicitlyDeclared && !property.IsIndexer)
                .Select(PropertyModel.From)
                .ToEquatableArray()
            : default;

        var methods = includeMembers
            ? type.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary && !method.IsImplicitlyDeclared)
                .Select(MethodModel.From)
                .ToEquatableArray()
            : default;

        var unionCaseTypes = TypeDeclarationKindFactory.IsUnion(type)
            ? type.InstanceConstructors
                .Where(constructor =>
                    constructor.Parameters.Length == 1
                    // Metadata symbols are never implicitly declared, so the filter only applies to source.
                    && (constructor.IsImplicitlyDeclared || type.DeclaringSyntaxReferences.Length == 0))
                .Select(constructor => TypeRef.From(constructor.Parameters[0].Type))
                .ToEquatableArray()
            : default;

        return new TypeModel(
            GetNamespace(type),
            type.Name,
            TypeDeclarationKindFactory.From(type),
            type.DeclaredAccessibility,
            type.IsStatic,
            type.IsAbstract,
            type.IsSealed,
            type.IsReadOnly,
            type.IsRefLikeType,
            type.IsFileLocal,
            typeParameters,
            GetContainingTypes(type),
            attributes,
            fields,
            properties,
            methods)
        {
            UnionCaseTypes = unionCaseTypes,
            IsClosed = ClosedTypeDetector.IsClosed(type),
        };
    }

    private static string? GetNamespace(INamedTypeSymbol type)
    {
        return type.ContainingNamespace is { IsGlobalNamespace: false } containingNamespace
            ? containingNamespace.ToDisplayString()
            : null;
    }

    private static EquatableArray<ContainingTypeModel> GetContainingTypes(INamedTypeSymbol type)
    {
        var containingTypes = new List<ContainingTypeModel>();
        INamedTypeSymbol? current = type.ContainingType;

        while (current is not null)
        {
            containingTypes.Add(ContainingTypeModel.From(current));
            current = current.ContainingType;
        }

        // Walked innermost-to-outermost; reverse so index 0 is the outermost containing type,
        // matching the order a writer opens nested type declarations.
        containingTypes.Reverse();

        return containingTypes.ToEquatableArray();
    }
}
