// <auto-generated/>
#nullable enable

using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal sealed record TypeParameterModel(
    string Name,
    EquatableArray<TypeRef> ConstraintTypes,
    bool HasReferenceTypeConstraint,
    NullableAnnotation ReferenceTypeConstraintNullableAnnotation,
    bool HasValueTypeConstraint,
    bool HasUnmanagedTypeConstraint,
    bool HasNotNullConstraint,
    bool HasConstructorConstraint)
{
    public VarianceKind Variance { get; init; }

    public static TypeParameterModel From(ITypeParameterSymbol typeParameter)
    {
        var constraintTypes = typeParameter.ConstraintTypes
            .Select(TypeRef.From)
            .ToEquatableArray();

        return new TypeParameterModel(
            typeParameter.Name,
            constraintTypes,
            typeParameter.HasReferenceTypeConstraint,
            typeParameter.ReferenceTypeConstraintNullableAnnotation,
            typeParameter.HasValueTypeConstraint,
            typeParameter.HasUnmanagedTypeConstraint,
            typeParameter.HasNotNullConstraint,
            typeParameter.HasConstructorConstraint)
        {
            Variance = typeParameter.Variance,
        };
    }
}
