// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Models;

internal enum TypeDeclarationKind
{
    Class,
    RecordClass,
    Struct,
    RecordStruct,
    Interface
}

internal static class TypeDeclarationKindFactory
{
    public static TypeDeclarationKind From(INamedTypeSymbol type)
    {
        return type.TypeKind switch
        {
            TypeKind.Struct => type.IsRecord ? TypeDeclarationKind.RecordStruct : TypeDeclarationKind.Struct,
            TypeKind.Interface => TypeDeclarationKind.Interface,
            TypeKind.Class => type.IsRecord ? TypeDeclarationKind.RecordClass : TypeDeclarationKind.Class,
            _ => throw new ArgumentException(
                $"TypeModel does not support '{type.TypeKind}' declarations (e.g. enums and delegates); "
                    + "only classes, records, structs, record structs, and interfaces are modeled.",
                nameof(type)),
        };
    }
}

/// <summary>
/// Captures an <see cref="INamedTypeSymbol"/> declaration as value-equal data.
/// </summary>
/// <param name="Namespace">The containing namespace, or null for the global namespace.</param>
/// <param name="Name">The simple type name.</param>
/// <param name="Kind">The declaration kind (class, record, struct, record struct or interface).</param>
/// <param name="Accessibility">The declared accessibility.</param>
/// <param name="IsStatic">True when the type is declared static.</param>
/// <param name="IsAbstract">
/// True when the type is declared abstract. Interfaces always report <see langword="true"/> here even
/// though the <c>abstract</c> keyword is never written on an interface; a renderer emitting a partial
/// declaration must not echo this back for an interface.
/// </param>
/// <param name="IsSealed">
/// True when the type is sealed. Structs always report <see langword="true"/> here even though the
/// <c>sealed</c> keyword is never written on a struct; a renderer emitting a partial declaration must not
/// echo this back for a struct.
/// </param>
/// <param name="IsReadOnly">True when the type is a readonly struct.</param>
/// <param name="IsRefLikeType">True when the type is a ref struct.</param>
/// <param name="IsFileLocal">True when the type is declared with the file modifier.</param>
/// <param name="TypeParameters">The type's generic parameters.</param>
/// <param name="ContainingTypes">The enclosing types, outermost first.</param>
/// <param name="Attributes">The attributes applied to the type.</param>
/// <param name="Fields">The captured fields; empty unless members were included.</param>
/// <param name="Properties">The captured properties; empty unless members were included.</param>
/// <param name="Methods">The captured methods; empty unless members were included.</param>
internal sealed record TypeModel(
    string? Namespace,
    string Name,
    TypeDeclarationKind Kind,
    Accessibility Accessibility,
    bool IsStatic,
    bool IsAbstract,
    bool IsSealed,
    bool IsReadOnly,
    bool IsRefLikeType,
    bool IsFileLocal,
    EquatableArray<TypeParameterModel> TypeParameters,
    EquatableArray<ContainingTypeModel> ContainingTypes,
    EquatableArray<AttributeModel> Attributes,
    EquatableArray<FieldModel> Fields,
    EquatableArray<PropertyModel> Properties,
    EquatableArray<MethodModel> Methods)
{
    /// <summary>
    /// Builds a <see cref="TypeModel"/> from <paramref name="type"/>. Member arrays are left empty
    /// unless <paramref name="includeMembers"/> is true, since capturing every member ties the model's
    /// equality (and so incremental generator cache validity) to any edit of any member.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is an enum, delegate, or other kind <see cref="TypeModel"/> does not model.
    /// </exception>
    public static TypeModel From(INamedTypeSymbol type, bool includeMembers = false)
    {
        var typeParameters = type.TypeParameters
            .Select(TypeParameterModel.From)
            .ToEquatableArray();

        var attributes = type.GetAttributes()
            .Select(AttributeModel.From)
            .OfType<AttributeModel>()
            .ToEquatableArray();

        var fields = includeMembers
            ? type.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(field => !field.IsImplicitlyDeclared)
                .Select(FieldModel.From)
                .ToEquatableArray()
            : default;

        var properties = includeMembers
            ? type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(property => !property.IsImplicitlyDeclared && !property.IsIndexer)
                .Select(PropertyModel.From)
                .ToEquatableArray()
            : default;

        var methods = includeMembers
            ? type.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary && !method.IsImplicitlyDeclared)
                .Select(MethodModel.From)
                .ToEquatableArray()
            : default;

        return new TypeModel(
            GetNamespace(type),
            type.Name,
            TypeDeclarationKindFactory.From(type),
            type.DeclaredAccessibility,
            type.IsStatic,
            type.IsAbstract,
            type.IsSealed,
            type.IsReadOnly,
            type.IsRefLikeType,
            type.IsFileLocal,
            typeParameters,
            GetContainingTypes(type),
            attributes,
            fields,
            properties,
            methods);
    }

    private static string? GetNamespace(INamedTypeSymbol type)
    {
        return type.ContainingNamespace is { IsGlobalNamespace: false } containingNamespace
            ? containingNamespace.ToDisplayString()
            : null;
    }

    private static EquatableArray<ContainingTypeModel> GetContainingTypes(INamedTypeSymbol type)
    {
        var containingTypes = new List<ContainingTypeModel>();
        INamedTypeSymbol? current = type.ContainingType;

        while (current is not null)
        {
            containingTypes.Add(ContainingTypeModel.From(current));
            current = current.ContainingType;
        }

        // Walked innermost-to-outermost; reverse so index 0 is the outermost containing type,
        // matching the order a writer opens nested type declarations.
        containingTypes.Reverse();

        return containingTypes.ToEquatableArray();
    }
}
