using Haitch.Roslyn.Writing;

namespace Haitch.Roslyn.Tests.Writing.Scopes;

public class FileAndNamespaceScopeTests
{
    [Test]
    public async Task Should_render_header_and_a_namespace_block()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using (file.Namespace("A.B")) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace A.B
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_render_using_directives_before_the_namespace()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            file.Using("System");
            using (file.Namespace("A")) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            using System;

            namespace A
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_render_sibling_namespaces_in_order()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using (file.Namespace("A")) { }

            using (file.Namespace("B")) { }
        }

        await Assert.That(writer.ToString()).Contains("namespace A\n{\n}\n\nnamespace B\n{\n}\n");
    }

    [Test]
    public async Task Should_close_a_namespace_only_once_when_disposed_twice()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            NamespaceScope scope = file.Namespace("A");
            scope.Dispose();
            scope.Dispose();
        }

        await Assert.That(writer.ToString()).EndsWith("namespace A\n{\n}\n");
    }

    [Test]
    public async Task Should_compile_a_legal_scope_snippet()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    using var file = writer.File();
                    using (file.Namespace("A.B"))
                    {
                    }
            """);

        await Assert.That(errors).IsEmpty();
    }

    [Test]
    public async Task Should_reject_a_namespace_nested_in_a_namespace()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    using var file = writer.File();
                    file.Namespace("A").Namespace("B");
            """);

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    [Arguments(null)]
    [Arguments("")]
    [Arguments("  ")]
    public async Task Should_reject_a_blank_namespace_name(string? name)
    {
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                file.Namespace(name!);
            })
            .Throws<ArgumentException>();
    }
}
