using System.Linq;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Tests.Models;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.Tests.Writing.Scopes;

public class MethodScopeTests
{
    private const string MethodSource =
        """
        public abstract class Source
        {
            public T Convert<T, U>(U input)
                where T : class, new()
                where U : struct
            {
                return new T();
            }

            public void Other()
            {
            }

            public abstract void Abstract();
        }

        public interface ISource
        {
            void Member();
        }
        """;

    private const string SampleSource = "public partial class Sample { }";

    private static MethodModel MethodFrom(string typeName, string methodName)
    {
        INamedTypeSymbol type = CompilationHelper.GetNamedTypeSymbol(MethodSource, typeName);

        return MethodModel.From(type.GetMembers(methodName).OfType<IMethodSymbol>().Single());
    }

    private static TypeModel Sample()
    {
        return TypeModel.From(CompilationHelper.GetNamedTypeSymbol(SampleSource, "Sample"));
    }

    [Test]
    public async Task Should_render_the_signature_without_a_semicolon_then_a_braced_body_with_a_nested_block()
    {
        MethodModel method = MethodFrom("Source", "Convert");

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var body = type.Method(method);
            body.Line("var copy = input;");

            using (var inner = body.Block("if (copy.Equals(default(U)))"))
            {
                inner.Line("return new T();");
            }

            body.Line("return new T();");
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            partial class Sample
            {
                public T Convert<T, U>(U input)
                    where T : class, new()
                    where U : struct
                {
                    var copy = input;
                    if (copy.Equals(default(U)))
                    {
                        return new T();
                    }
                    return new T();
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_render_the_same_signature_as_WriteMethodSignature_minus_the_semicolon()
    {
        MethodModel method = MethodFrom("Source", "Convert");

        SourceWriter signatureOnly = new();
        signatureOnly.WriteMethodSignature(method);

        SourceWriter scoped = new();

        using (var file = scoped.File())
        {
            using var type = file.Type(Sample());
            using (type.Method(method)) { }
        }

        string signature = signatureOnly.ToString().TrimEnd('\n');
        string header = signature.Substring(0, signature.Length - 1);

        await Assert.That(scoped.ToString()).Contains("    " + header.Replace("\n", "\n    ") + "\n    {\n    }\n");
    }

    [Test]
    public async Task Should_produce_source_that_compiles()
    {
        MethodModel method = MethodFrom("Source", "Convert");

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var body = type.Method(method);
            body.Line("var copy = input;");

            using (var inner = body.Block("if (copy.Equals(default(U)))"))
            {
                inner.Line("return new T();");
            }

            body.Line("return new T();");
        }

        CSharpCompilation compilation = CompilationHelper.Compile(SampleSource + "\n" + writer, allowErrors: true);

        await Assert.That(compilation.GetDiagnostics().Count(d => d.Severity == DiagnosticSeverity.Error)).IsEqualTo(0);
    }

    [Test]
    public async Task Should_compile_the_implementation_of_partial_methods_with_and_without_an_access_modifier()
    {
        const string userSource = "public partial class Sample { partial void OnX(); public partial int M(); }";
        INamedTypeSymbol sample = CompilationHelper.GetNamedTypeSymbol(userSource, "Sample", allowErrors: true);
        MethodModel onX = MethodModel.From(sample.GetMembers("OnX").OfType<IMethodSymbol>().Single());
        MethodModel m = MethodModel.From(sample.GetMembers("M").OfType<IMethodSymbol>().Single());

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(TypeModel.From(sample));
            using (type.Method(onX)) { }

            using var body = type.Method(m);
            body.Line("return 1;");
        }

        CSharpCompilation compilation = CompilationHelper.Compile(userSource + "\n" + writer, allowErrors: true);

        await Assert.That(compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error)
            .Select(d => d.Id)).IsEmpty();
        await Assert.That(writer.ToString()).Contains("    partial void OnX()\n");
        await Assert.That(writer.ToString()).Contains("    public partial int M()\n");
    }

    [Test]
    public async Task Should_return_the_same_scope_from_Line_for_chaining()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var body = type.Method(MethodFrom("Source", "Other"));
            body.Line("a();").Line("b();");
        }

        await Assert.That(writer.ToString()).Contains("    {\n        a();\n        b();\n    }\n");
    }

    [Test]
    public async Task Should_separate_sibling_members_with_a_blank_line()
    {
        MethodModel other = MethodFrom("Source", "Other");

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using (type.Method(other)) { }

            using (type.Method(other)) { }

            using (type.Type(Sample())) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            partial class Sample
            {
                public void Other()
                {
                }

                public void Other()
                {
                }

                partial class Sample
                {
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_close_a_method_only_once_when_disposed_twice()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            BodyScope body = type.Method(MethodFrom("Source", "Other"));
            body.Dispose();
            body.Dispose();
        }

        await Assert.That(writer.ToString()).EndsWith("    public void Other()\n    {\n    }\n}\n");
    }

    [Test]
    public async Task Should_reject_an_abstract_method()
    {
        MethodModel method = MethodFrom("Source", "Abstract");
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                type.Method(method);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_reject_an_extern_method()
    {
        MethodModel method = MethodFrom("Source", "Other") with { IsExtern = true };
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                type.Method(method);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_reject_an_interface_method()
    {
        MethodModel method = MethodFrom("ISource", "Member");
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                type.Method(method);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_reject_a_blank_block_header()
    {
        MethodModel method = MethodFrom("Source", "Other");
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var body = type.Method(method);
                body.Block(" ");
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_compile_a_legal_method_scope_snippet()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    body.Line("a();");
                    using (body.Block("if (x)"))
                    {
                        body.Line("b();");
                    }
            """);

        await Assert.That(errors).IsEmpty();
    }

    [Test]
    public async Task Should_reject_a_method_nested_in_a_body()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    body.Method(method);
            """);

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    public async Task Should_reject_a_method_on_a_namespace_scope()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var ns = file.Namespace("A");
                    ns.Method(method);
            """);

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }
}
