using System.Linq;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Tests.Models;
using Haitch.Roslyn.Types;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.Tests.Writing.Scopes;

public class NewTypeScopeTests
{
    private const string MemberSource =
        """
        public abstract class Source
        {
            public void M() { }
            public int Plain;
            public int Count { get; private set; }
            public int Prop { get; set; }
        }

        public interface ISource
        {
            void Default() { }
            int InstanceField => 0;
        }
        """;

    private static TypeModel TypeNamed(string name)
    {
        return TypeModel.From(CompilationHelper.GetNamedTypeSymbol($"public partial class {name} {{ }}", name));
    }

    private static MethodModel MethodFrom(string typeName, string name)
    {
        INamedTypeSymbol type = CompilationHelper.GetNamedTypeSymbol(MemberSource, typeName);

        return MethodModel.From(type.GetMembers(name).OfType<IMethodSymbol>().Single());
    }

    private static FieldModel FieldFrom(string name)
    {
        INamedTypeSymbol type = CompilationHelper.GetNamedTypeSymbol(MemberSource, "Source");

        return FieldModel.From(type.GetMembers(name).OfType<IFieldSymbol>().Single());
    }

    private static PropertyModel PropertyFrom(string name)
    {
        INamedTypeSymbol type = CompilationHelper.GetNamedTypeSymbol(MemberSource, "Source");

        return PropertyModel.From(type.GetMembers(name).OfType<IPropertySymbol>().Single());
    }

    private static async Task AssertCompiles(string output)
    {
        CSharpCompilation compilation = CompilationHelper.Compile(output, allowErrors: true);
        string[] problems = compilation
            .GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(diagnostic => diagnostic.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    public async Task Should_write_a_new_class_in_a_namespace_with_a_field_method_and_property()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace("Example");
            using var type = ns.NewType(new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Public));
            type.Field(FieldFrom("Plain"));
            using (type.Method(MethodFrom("Source", "M"))) { }

            type.AutoProperty(PropertyFrom("Count"));
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Example
            {
                public class Widget
                {
                    public int Plain;

                    public void M()
                    {
                    }

                    public int Count { get; private set; }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
        await AssertCompiles(writer.ToString());
    }

    [Test]
    public async Task Should_write_a_new_interface_with_a_default_method()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace("Example");
            using var type =
                ns.NewType(new NewTypeModel("IWidget", TypeDeclarationKind.Interface, Accessibility.Public));
            using (type.Method(MethodFrom("ISource", "Default"))) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Example
            {
                public interface IWidget
                {
                    public virtual void Default()
                    {
                    }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
        await AssertCompiles(writer.ToString());
    }

    [Test]
    public async Task Should_write_a_sealed_class_nested_in_a_partial_type_scope()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var outer = file.Type(TypeNamed("Outer"));
            outer.Field(FieldFrom("Plain"));
            using var inner = outer.NewType(
                new NewTypeModel("Inner", TypeDeclarationKind.Class, Accessibility.Private) { IsSealed = true });
            inner.AutoProperty(PropertyFrom("Count"));
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            partial class Outer
            {
                public int Plain;

                private sealed class Inner
                {
                    public int Count { get; private set; }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
        await AssertCompiles("public partial class Outer { }\n" + writer);
    }

    [Test]
    public async Task Should_write_a_static_class_at_file_level()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            file.Using("System");
            using var type = file.NewType(
                new NewTypeModel("Helpers", TypeDeclarationKind.Class, Accessibility.Public) { IsStatic = true });
            type.Field(FieldFrom("Plain") with { IsStatic = true });
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            using System;

            public static class Helpers
            {
                public static int Plain;
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
        await AssertCompiles(writer.ToString());
    }

    [Test]
    public async Task Should_write_a_new_type_nested_in_a_new_type_and_compile()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace("Example");
            ns.NewType(new NewTypeModel("A", TypeDeclarationKind.Class, Accessibility.Public)).Dispose();

            using var outer = ns.NewType(new NewTypeModel("Outer", TypeDeclarationKind.Class, Accessibility.Public));
            outer.Field(FieldFrom("Plain"));
            using var inner = outer.NewType(
                new NewTypeModel("Inner", TypeDeclarationKind.Struct, Accessibility.Protected));
            inner.AutoProperty(PropertyFrom("Count"));
            using (inner.Method(MethodFrom("Source", "M"))) { }

            using var innermost = inner.NewType(
                new NewTypeModel("Innermost", TypeDeclarationKind.Interface, Accessibility.Public));
            using (innermost.Method(MethodFrom("ISource", "Default"))) { }
        }

        await AssertCompiles(writer.ToString());
    }

    [Test]
    public async Task Should_attach_a_pending_attribute_to_the_new_type_without_a_blank_line()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            file.Using("System");
            file.Attribute(WellKnownAttributes.EditorBrowsableNever);
            using var type = file.NewType(new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Public));
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            using System;

            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            public class Widget
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_separate_consecutive_new_types_with_one_blank_line()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using (file.NewType(new NewTypeModel("A", TypeDeclarationKind.Class, Accessibility.Public))) { }

            using (file.NewType(new NewTypeModel("B", TypeDeclarationKind.Class, Accessibility.Public))) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            public class A
            {
            }

            public class B
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_reject_an_instance_field_in_a_new_interface()
    {
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.NewType(
                    new NewTypeModel("IWidget", TypeDeclarationKind.Interface, Accessibility.Public));
                type.Field(FieldFrom("Plain"));
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_reject_a_type_with_containing_types_in_a_nested_type_scope_of_a_new_type()
    {
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.NewType(
                    new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Public));
                using var other = type.Type(TypeNamed("Other") with
                {
                    ContainingTypes = new[]
                    {
                        new ContainingTypeModel(
                            TypeDeclarationKind.Class, "Elsewhere", default, Accessibility.Public, false, false),
                    }.ToEquatableArray(),
                });
            })
            .Throws<ArgumentException>();
    }

    [Test]
    [Arguments(Accessibility.Private)]
    [Arguments(Accessibility.Protected)]
    [Arguments(Accessibility.ProtectedOrInternal)]
    [Arguments(Accessibility.ProtectedAndInternal)]
    public async Task Should_reject_a_nested_only_accessibility_for_a_top_level_new_type(Accessibility accessibility)
    {
        NewTypeModel model = new("Widget", TypeDeclarationKind.Class, accessibility);

        SourceWriter fileWriter = new();
        string fileBefore;
        string fileAfter;
        var fileThrew = false;

        using (var file = fileWriter.File())
        {
            file.Using("System");
            fileBefore = fileWriter.ToString();

            try
            {
                file.NewType(model);
            }
            catch (ArgumentException)
            {
                fileThrew = true;
            }

            fileAfter = fileWriter.ToString();
        }

        SourceWriter namespaceWriter = new();
        string namespaceBefore;
        string namespaceAfter;
        var namespaceThrew = false;

        using (var file = namespaceWriter.File())
        {
            using var ns = file.Namespace("Example");
            using (ns.NewType(new NewTypeModel("First", TypeDeclarationKind.Class, Accessibility.Public))) { }

            namespaceBefore = namespaceWriter.ToString();

            try
            {
                ns.NewType(model);
            }
            catch (ArgumentException)
            {
                namespaceThrew = true;
            }

            namespaceAfter = namespaceWriter.ToString();
        }

        await Assert.That(fileThrew).IsTrue();
        await Assert.That(fileAfter).IsEqualTo(fileBefore);
        await Assert.That(namespaceThrew).IsTrue();
        await Assert.That(namespaceAfter).IsEqualTo(namespaceBefore);
    }

    [Test]
    public async Task Should_reject_a_file_local_new_type_nested_in_a_type()
    {
        SourceWriter writer = new();
        string before;
        string after;
        var threw = false;

        using (var file = writer.File())
        {
            using var outer = file.Type(TypeNamed("Outer"));
            outer.Field(FieldFrom("Plain"));
            before = writer.ToString();

            try
            {
                outer.NewType(
                    new NewTypeModel("Inner", TypeDeclarationKind.Class, Accessibility.NotApplicable)
                    {
                        IsFileLocal = true,
                    });
            }
            catch (ArgumentException)
            {
                threw = true;
            }

            after = writer.ToString();
        }

        await Assert.That(threw).IsTrue();
        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    public async Task Should_keep_the_pending_attribute_after_a_rejected_new_type()
    {
        SourceWriter writer = new();
        var threw = false;

        using (var file = writer.File())
        {
            file.Using("System");
            file.Attribute(WellKnownAttributes.EditorBrowsableNever);

            try
            {
                file.NewType(new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Private));
            }
            catch (ArgumentException)
            {
                threw = true;
            }

            using var type = file.NewType(new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Public));
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            using System;

            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            public class Widget
            {
            }

            """;

        await Assert.That(threw).IsTrue();
        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_write_a_partial_nested_type_whose_last_containing_type_is_the_new_type()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.NewType(
                new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.Public) { IsPartial = true });
            using var other = type.Type(TypeNamed("Other") with
            {
                ContainingTypes = new[]
                {
                    new ContainingTypeModel(
                        TypeDeclarationKind.Class, "Widget", default, Accessibility.Public, false, false),
                }.ToEquatableArray(),
            });
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            public partial class Widget
            {
                partial class Other
                {
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
        await AssertCompiles(writer.ToString());
    }

    [Test]
    [Arguments(Accessibility.Protected)]
    [Arguments(Accessibility.ProtectedOrInternal)]
    [Arguments(Accessibility.ProtectedAndInternal)]
    public async Task Should_reject_a_protected_new_type_inside_a_struct_or_a_static_class(Accessibility accessibility)
    {
        NewTypeModel[] containers =
        [
            new("S", TypeDeclarationKind.Struct, Accessibility.Public),
            new("R", TypeDeclarationKind.RecordStruct, Accessibility.Public),
            new("C", TypeDeclarationKind.Class, Accessibility.Public) { IsStatic = true },
        ];

        foreach (NewTypeModel container in containers)
        {
            SourceWriter writer = new();
            string before;
            string after;
            var threw = false;

            using (var file = writer.File())
            {
                using var scope = file.NewType(container);
                scope.Field(FieldFrom("Plain") with { IsStatic = true });
                before = writer.ToString();

                try
                {
                    scope.NewType(new NewTypeModel("Inner", TypeDeclarationKind.Class, accessibility));
                }
                catch (ArgumentException)
                {
                    threw = true;
                }

                after = writer.ToString();
            }

            await Assert.That(threw).IsTrue();
            await Assert.That(after).IsEqualTo(before);
        }
    }

    [Test]
    public async Task Should_accept_a_protected_new_type_inside_a_class()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var scope = file.NewType(new NewTypeModel("C", TypeDeclarationKind.Class, Accessibility.Public));
            using var inner = scope.NewType(
                new NewTypeModel("Inner", TypeDeclarationKind.Class, Accessibility.ProtectedOrInternal));
        }

        await AssertCompiles(writer.ToString());
    }

    [Test]
    public async Task Should_accept_a_file_local_new_type_at_file_level()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.NewType(
                new NewTypeModel("Widget", TypeDeclarationKind.Class, Accessibility.NotApplicable)
                {
                    IsFileLocal = true,
                });
        }

        await Assert.That(writer.ToString()).Contains("file class Widget");
    }

    [Test]
    public async Task Should_reject_a_new_type_on_a_body_scope()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    Haitch.Roslyn.Models.NewTypeModel model = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    body.NewType(model);
            """);

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    public async Task Should_compile_a_legal_new_type_chain_snippet()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.NewTypeModel model = null!;
                    using var file = writer.File();
                    using (file.NewType(model)) { }
                    using var ns = file.Namespace("A");
                    using (ns.NewType(model)) { }
                    using var t = ns.Type(type);
                    using (t.NewType(model)) { }
            """);

        await Assert.That(errors).IsEmpty();
    }
}
