using System.Linq;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Tests.Models;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.Tests.Writing.Scopes;

public class StatementScopeTests
{
    private const string SampleSource = "public partial class Sample { public void Other() { } }";

    private static TypeModel Sample()
    {
        return TypeModel.From(CompilationHelper.GetNamedTypeSymbol(SampleSource, "Sample"));
    }

    private static MethodModel Other()
    {
        INamedTypeSymbol type = CompilationHelper.GetNamedTypeSymbol(SampleSource, "Sample");

        return MethodModel.From(type.GetMembers("Other").OfType<IMethodSymbol>().Single());
    }

    private static string RenderMethod(Action<BodyScope> body)
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            body(method);
        }

        return writer.ToString();
    }

    private static string Expected(string body)
    {
        return "// <auto-generated/>\n#nullable enable\n\npartial class Sample\n{\n    public void Other()\n    {\n"
            + body
            + "    }\n}\n";
    }

    [Test]
    public async Task Should_render_a_lone_if()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("a > 0");
            branch.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(Expected("        if (a > 0)\n        {\n            x();\n        }\n"));
    }

    [Test]
    public async Task Should_render_if_else()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("a > 0");
            branch.Line("x();");

            using var otherwise = branch.Else();
            otherwise.Line("y();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a > 0)\n        {\n            x();\n        }\n        else\n        {\n            y();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_if_else_if_else()
    {
        string output = RenderMethod(body =>
        {
            using var first = body.If("a > 0");
            first.Line("x();");

            using var second = first.ElseIf("a < 0");
            second.Line("y();");

            using var third = second.ElseIf("a == 0");
            third.Line("z();");

            using var last = third.Else();
            last.Line("w();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a > 0)\n        {\n            x();\n        }\n"
                        + "        else if (a < 0)\n        {\n            y();\n        }\n"
                        + "        else if (a == 0)\n        {\n            z();\n        }\n"
                        + "        else\n        {\n            w();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_an_if_nested_in_an_else()
    {
        string output = RenderMethod(body =>
        {
            using var outer = body.If("a");
            outer.Line("x();");

            using var otherwise = outer.Else();

            using (var inner = otherwise.If("b"))
            {
                inner.Line("y();");
            }

            otherwise.Line("z();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a)\n        {\n            x();\n        }\n"
                        + "        else\n        {\n            if (b)\n            {\n                y();\n            }\n"
                        + "            z();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_write_the_condition_as_given()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("(a)");
        });

        await Assert.That(output).Contains("        if ((a))\n");
    }

    [Test]
    public async Task Should_close_a_branch_only_once_when_disposed_after_chaining()
    {
        string output = RenderMethod(body =>
        {
            IfScope branch = body.If("a");
            IfScope next = branch.ElseIf("b");
            branch.Dispose();
            next.Dispose();
            next.Dispose();
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a)\n        {\n        }\n        else if (b)\n        {\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_compile_every_form_inside_a_method_without_errors_or_warnings()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            method.Line("string? s = System.Environment.GetEnvironmentVariable(\"X\");");

            using (var lone = method.If("s is null"))
            {
                lone.Line("System.Console.WriteLine(1);");

                using (var each = lone.ForEach("var", "c", "\"ab\""))
                {
                    each.Line("System.Console.WriteLine(c);");
                }

                using (var loop = lone.For("var i = 0", "i < 2", "i++"))
                {
                    loop.Line("System.Console.WriteLine(i);");
                }

                using (var wh = lone.While("s is null && System.Environment.ProcessorCount < 0"))
                {
                    wh.Line("break;");
                }

                using (var us = lone.Using("var ms = new System.IO.MemoryStream()"))
                {
                    us.Line("ms.WriteByte(1);");
                }

                using (var inner = lone.If("System.Environment.ProcessorCount > 0"))
                {
                    inner.Line("System.Console.WriteLine(2);");
                }
            }

            using (var ifElse = method.If("s is null"))
            {
                ifElse.Line("System.Console.WriteLine(1);");

                using var otherwise = ifElse.Else();
                otherwise.Line("System.Console.WriteLine(s.Length);");
            }

            using (var chain = method.If("s is null"))
            {
                chain.Line("System.Console.WriteLine(1);");

                using var second = chain.ElseIf("s.Length == 0");
                second.Line("System.Console.WriteLine(2);");

                using var third = second.ElseIf("s.Length == 1");
                third.Line("System.Console.WriteLine(3);");

                using var last = third.Else();
                last.Line("System.Console.WriteLine(4);");

                using var nested = last.If("s.Length > 5");
                nested.Line("System.Console.WriteLine(5);");

                using var nestedElse = nested.Else();
                nestedElse.Line("System.Console.WriteLine(6);");
            }
        }

        CSharpCompilation compilation = CompilationHelper.Compile(
            "public partial class Sample { }\n" + writer,
            allowErrors: true
        );

        string[] problems = compilation
            .GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(d => d.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    [Arguments("")]
    [Arguments("   ")]
    public async Task Should_reject_a_blank_if_condition_without_writing(string condition)
    {
        SourceWriter writer = new();
        string before = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                before = writer.ToString();
                method.If(condition);
            })
            .Throws<ArgumentException>();

        await Assert.That(writer.ToString()).StartsWith(before);
        await Assert.That(writer.ToString()).DoesNotContain("if");
    }

    [Test]
    [Arguments("")]
    [Arguments("   ")]
    public async Task Should_reject_a_blank_else_if_condition_leaving_the_branch_open(
        string condition
    )
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                IfScope branch = method.If("a");
                before = writer.ToString();

                try
                {
                    branch.ElseIf(condition);
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<ArgumentException>();

        await Assert.That(before).EndsWith("        if (a)\n        {\n");
        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    public async Task Should_throw_when_a_branch_is_chained_twice()
    {
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                IfScope branch = method.If("a");
                branch.Else();
                branch.ElseIf("b");
            })
            .Throws<InvalidOperationException>();
    }

    [Test]
    public async Task Should_compile_a_legal_if_else_snippet()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    using var first = body.If("a");
                    using var second = first.ElseIf("b");
                    using var last = second.Else();
                    last.Line("c();");
            """
        );

        await Assert.That(errors).IsEmpty();
    }

    [Test]
    public async Task Should_reject_else_if_after_else()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    using var first = body.If("a");
                    using var last = first.Else();
                    last.ElseIf("b");
            """
        );

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    public async Task Should_reject_else_and_else_if_without_an_if()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    body.Else();
                    body.ElseIf("a");
            """
        );

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061", "CS1061" });
    }

    [Test]
    public async Task Should_render_foreach()
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.ForEach("var", "item", "items");
            loop.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        foreach (var item in items)\n        {\n            x();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_for()
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.For("var i = 0", "i < n", "i++");
            loop.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        for (var i = 0; i < n; i++)\n        {\n            x();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_an_infinite_for_from_empty_parts()
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.For("", "", "");
        });

        await Assert.That(output).IsEqualTo(Expected("        for (;;)\n        {\n        }\n"));
    }

    [Test]
    public async Task Should_render_a_for_with_only_some_parts()
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.For("", "i < n", "");
        });

        await Assert
            .That(output)
            .IsEqualTo(Expected("        for (; i < n;)\n        {\n        }\n"));
    }

    [Test]
    [Arguments("  ", "", "", "for (;;)")]
    [Arguments("", "  ", "", "for (;;)")]
    [Arguments("", "", "  ", "for (;;)")]
    [Arguments("  ", "i < n", "  ", "for (; i < n;)")]
    [Arguments(" i = 0 ", " i < n ", " i++ ", "for (i = 0; i < n; i++)")]
    public async Task Should_trim_for_parts_and_treat_whitespace_as_empty(
        string initializer,
        string condition,
        string iterator,
        string header
    )
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.For(initializer, condition, iterator);
        });

        await Assert
            .That(output)
            .IsEqualTo(Expected($"        {header}\n        {{\n        }}\n"));
    }

    [Test]
    public async Task Should_render_while()
    {
        string output = RenderMethod(body =>
        {
            using var loop = body.While("x > 0");
            loop.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(Expected("        while (x > 0)\n        {\n            x();\n        }\n"));
    }

    [Test]
    public async Task Should_render_using_as_a_block()
    {
        string output = RenderMethod(body =>
        {
            using var scope = body.Using("var stream = Open()");
            scope.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        using (var stream = Open())\n        {\n            x();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_a_loop_nested_in_a_loop()
    {
        string output = RenderMethod(body =>
        {
            using var outer = body.ForEach("var", "row", "rows");
            using var inner = outer.ForEach("var", "cell", "row");
            inner.Line("x();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        foreach (var row in rows)\n        {\n            foreach (var cell in row)\n            {\n"
                        + "                x();\n            }\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_compile_every_loop_and_using_inside_one_method_without_errors_or_warnings()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            method.Line("int[] items = { 1, 2 };");
            method.Line("int n = 3;");
            method.Line("int x = 2;");

            using (var each = method.ForEach("var", "item", "items"))
            {
                using var inner = each.For("var i = 0", "i < n", "i++");
                inner.Line("System.Console.WriteLine(item + i);");
            }

            using (var infinite = method.For("", "", ""))
            {
                infinite.Line("break;");
            }

            using (var loop = method.While("x > 0"))
            {
                loop.Line("x--;");
            }

            using (var scope = method.Using("var stream = new System.IO.MemoryStream()"))
            {
                scope.Line("stream.WriteByte(1);");
            }
        }

        CSharpCompilation compilation = CompilationHelper.Compile(
            "public partial class Sample { }\n" + writer,
            allowErrors: true
        );

        string[] problems = compilation
            .GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(d => d.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    [Arguments("", "item", "items")]
    [Arguments("  ", "item", "items")]
    [Arguments("var", "", "items")]
    [Arguments("var", " ", "items")]
    [Arguments("var", "item", "")]
    [Arguments("var", "item", "  ")]
    public async Task Should_reject_a_blank_foreach_argument_without_writing(
        string type,
        string identifier,
        string collection
    )
    {
        await AssertRejectedWithoutWriting(body => body.ForEach(type, identifier, collection));
    }

    [Test]
    [Arguments("")]
    [Arguments("   ")]
    public async Task Should_reject_a_blank_while_condition_without_writing(string condition)
    {
        await AssertRejectedWithoutWriting(body => body.While(condition));
    }

    [Test]
    [Arguments("")]
    [Arguments("   ")]
    public async Task Should_reject_a_blank_using_resource_without_writing(string resource)
    {
        await AssertRejectedWithoutWriting(body => body.Using(resource));
    }

    [Test]
    public async Task Should_render_statements_written_directly_inside_an_if_branch()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("a");
            using (var each = branch.ForEach("var", "item", "items"))
            {
                each.Line("x();");
            }

            using (var loop = branch.For("var i = 0", "i < n", "i++")) { }

            using (var wh = branch.While("b")) { }

            using (var us = branch.Using("var s = Open()")) { }

            using (var inner = branch.If("c")) { }
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a)\n        {\n            foreach (var item in items)\n            {\n                x();\n            }\n"
                        + "            for (var i = 0; i < n; i++)\n            {\n            }\n"
                        + "            while (b)\n            {\n            }\n"
                        + "            using (var s = Open())\n            {\n            }\n"
                        + "            if (c)\n            {\n            }\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_reject_blank_arguments_on_if_branch_statements_without_writing()
    {
        SourceWriter writer = new();
        string before = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                using var branch = method.If("a");
                before = writer.ToString();
                branch.While(" ");
            })
            .Throws<ArgumentException>();

        await Assert.That(writer.ToString()).StartsWith(before);
        await Assert.That(writer.ToString()).DoesNotContain("while");
    }

    [Test]
    public async Task Should_render_try_catch()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            attempt.Line("x();");

            using var handler = attempt.Catch();
            handler.Line("y();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        try\n        {\n            x();\n        }\n        catch\n        {\n            y();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_try_finally()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            attempt.Line("x();");

            using var cleanup = attempt.Finally();
            cleanup.Line("z();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        try\n        {\n            x();\n        }\n        finally\n        {\n            z();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_try_catch_with_type_identifier_and_filter_then_general_catch_and_finally()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            attempt.Line("x();");

            using var first = attempt.Catch(
                "global::System.IO.IOException",
                "ex",
                "ex.HResult != 0"
            );
            first.Line("y();");

            using var second = first.Catch();
            second.Line("w();");

            using var cleanup = second.Finally();
            cleanup.Line("z();");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        try\n        {\n            x();\n        }\n"
                        + "        catch (global::System.IO.IOException ex) when (ex.HResult != 0)\n        {\n            y();\n        }\n"
                        + "        catch\n        {\n            w();\n        }\n"
                        + "        finally\n        {\n            z();\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_each_catch_shape()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            using var a = attempt.Catch("System.ArgumentException");
            using var b = a.Catch("System.IO.IOException", "ex");
            using var c = b.Catch(filter: "flag");
            using var d = c.Catch("System.Exception", filter: "flag");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        try\n        {\n        }\n"
                        + "        catch (System.ArgumentException)\n        {\n        }\n"
                        + "        catch (System.IO.IOException ex)\n        {\n        }\n"
                        + "        catch when (flag)\n        {\n        }\n"
                        + "        catch (System.Exception) when (flag)\n        {\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_try_nested_in_if_and_in_try()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("a");
            using var attempt = branch.Try();
            using (var inner = attempt.Try())
            {
                using var innerCleanup = inner.Finally();
            }

            using var handler = attempt.Catch();
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a)\n        {\n            try\n            {\n                try\n                {\n                }\n"
                        + "                finally\n                {\n                }\n            }\n"
                        + "            catch\n            {\n            }\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_compile_try_forms_inside_a_method_without_errors_or_warnings()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());

            using (var attempt = method.Try())
            {
                attempt.Line("System.Console.WriteLine(1);");

                using var handler = attempt.Catch();
                handler.Line("System.Console.WriteLine(2);");
            }

            using (var attempt = method.Try())
            {
                attempt.Line("System.Console.WriteLine(1);");

                using var cleanup = attempt.Finally();
                cleanup.Line("System.Console.WriteLine(3);");
            }

            using (var attempt = method.Try())
            {
                attempt.Line("System.Console.WriteLine(1);");

                using var first = attempt.Catch(
                    "global::System.IO.IOException",
                    "ex",
                    "ex.HResult != 0"
                );
                first.Line("System.Console.WriteLine(ex.HResult);");

                using var second = first.Catch("System.ArgumentException");
                second.Line("System.Console.WriteLine(2);");

                using var third = second.Catch();
                third.Line("System.Console.WriteLine(4);");

                using var cleanup = third.Finally();
                cleanup.Line("System.Console.WriteLine(3);");
            }
        }

        CSharpCompilation compilation = CompilationHelper.Compile(
            "public partial class Sample { }\n" + writer,
            allowErrors: true
        );

        string[] problems = compilation
            .GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(d => d.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    public async Task Should_render_try_inside_a_catch_body_and_a_finally_body()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            using var handler = attempt.Catch();
            using (var inCatch = handler.Try())
            {
                using var inCatchCleanup = inCatch.Finally();
            }

            using var cleanup = handler.Finally();
            using var inFinally = cleanup.Try();
            using var inFinallyHandler = inFinally.Catch();
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        try\n        {\n        }\n"
                        + "        catch\n        {\n            try\n            {\n            }\n"
                        + "            finally\n            {\n            }\n        }\n"
                        + "        finally\n        {\n            try\n            {\n            }\n"
                        + "            catch\n            {\n            }\n        }\n"
                )
            );
    }

    [Test]
    public async Task Should_compile_try_catch_variants_without_errors_or_warnings()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());

            // Every catch identifier is used: an unused one would add warning CS0168.
            using var attempt = method.Try();

            using (var nested = attempt.Try())
            {
                nested.Line("System.Console.WriteLine(1);");

                using var nestedHandler = nested.Catch("System.Exception", "inner");
                nestedHandler.Line("System.Console.WriteLine(inner);");
            }

            using var typed = attempt.Catch("System.ArgumentException", "ex");
            typed.Line("System.Console.WriteLine(ex);");

            using var filtered = typed.Catch(filter: "System.Environment.TickCount > 0");
            filtered.Line("System.Console.WriteLine(5);");
        }

        CSharpCompilation compilation = CompilationHelper.Compile(
            "public partial class Sample { }\n" + writer,
            allowErrors: true
        );

        string[] problems = compilation
            .GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(d => d.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    public async Task Should_reject_catch_after_finally()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    using var attempt = body.Try();
                    using var cleanup = attempt.Finally();
                    cleanup.Catch();
            """
        );

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    public async Task Should_throw_when_a_catch_follows_a_general_catch()
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                TryScope attempt = method.Try();
                TryScope general = attempt.Catch();
                before = writer.ToString();

                try
                {
                    general.Catch("System.Exception");
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<InvalidOperationException>();

        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    public async Task Should_allow_a_catch_after_a_filtered_general_catch()
    {
        string output = RenderMethod(body =>
        {
            using var attempt = body.Try();
            using var filtered = attempt.Catch(filter: "flag");
            using var general = filtered.Catch();
        });

        await Assert.That(output).Contains("catch when (flag)").And.Contains("        catch\n");
    }

    [Test]
    public async Task Should_throw_when_a_try_scope_is_chained_twice()
    {
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                TryScope attempt = method.Try();
                attempt.Finally();
                attempt.Catch();
            })
            .Throws<InvalidOperationException>();
    }

    [Test]
    [Arguments(null, "ex", null)]
    [Arguments("", null, null)]
    [Arguments("  ", "ex", null)]
    [Arguments("T", "", null)]
    [Arguments("T", " ", null)]
    [Arguments("T", null, "")]
    [Arguments(null, null, "  ")]
    public async Task Should_reject_invalid_catch_arguments_leaving_the_try_open(
        string? type,
        string? identifier,
        string? filter
    )
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var t = file.Type(Sample());
                using var method = t.Method(Other());
                TryScope attempt = method.Try();
                before = writer.ToString();

                try
                {
                    attempt.Catch(type, identifier, filter);
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<ArgumentException>();

        await Assert.That(before).EndsWith("        try\n        {\n");
        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    public async Task Should_render_a_switch_with_two_constant_cases()
    {
        string output = RenderMethod(body =>
        {
            using var sw = body.Switch("n");

            using (var one = sw.Case("1"))
            {
                one.Line("x();").Line("break;");
            }

            using var two = sw.Case("2");
            two.Line("break;");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        switch (n)\n        {\n"
                        + "            case 1:\n            {\n                x();\n                break;\n            }\n"
                        + "            case 2:\n            {\n                break;\n            }\n"
                        + "        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_multi_label_pattern_and_default_sections()
    {
        string output = RenderMethod(body =>
        {
            using var sw = body.Switch("o");

            using (var many = sw.Case("1", "2"))
            {
                many.Line("break;");
            }

            using (var pattern = sw.Case("int i when i > 0"))
            {
                pattern.Line("break;");
            }

            using var fallback = sw.Default();
            fallback.Line("break;");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        switch (o)\n        {\n"
                        + "            case 1:\n            case 2:\n            {\n                break;\n            }\n"
                        + "            case int i when i > 0:\n            {\n                break;\n            }\n"
                        + "            default:\n            {\n                break;\n            }\n"
                        + "        }\n"
                )
            );
    }

    [Test]
    public async Task Should_render_a_switch_inside_an_if_branch_and_a_try_block()
    {
        string output = RenderMethod(body =>
        {
            using var branch = body.If("a");

            using (var inIf = branch.Switch("n"))
            {
                using var section = inIf.Default();
                section.Line("break;");
            }

            using var attempt = branch.Try();

            using (var inTry = attempt.Switch("n"))
            {
                using var tail = inTry.Default();
                tail.Line("break;");
            }

            attempt.Finally().Dispose();
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        if (a)\n        {\n"
                        + "            switch (n)\n            {\n                default:\n                {\n                    break;\n                }\n            }\n"
                        + "            try\n            {\n"
                        + "                switch (n)\n                {\n                    default:\n                    {\n                        break;\n                    }\n                }\n"
                        + "            }\n"
                        + "            finally\n            {\n            }\n"
                        + "        }\n"
                )
            );
    }

    [Test]
    public async Task Should_compile_a_switch_with_every_section_kind_without_errors_or_warnings()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            method.Line("object o = 1;");

            using var sw = method.Switch("o");

            using (var constants = sw.Case("0"))
            {
                constants.Line("System.Console.WriteLine(0);").Line("break;");
            }

            using (var many = sw.Case("1", "2"))
            {
                many.Line("break;");
            }

            using (var pattern = sw.Case("int i when i > 0"))
            {
                pattern.Line("System.Console.WriteLine(i);").Line("break;");
            }

            using var fallback = sw.Default();
            fallback.Line("break;");
        }

        CSharpCompilation compilation = CompilationHelper.Compile(
            "public partial class Sample { }\n" + writer,
            allowErrors: true
        );

        string[] problems = compilation
            .GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Select(d => d.ToString())
            .ToArray();

        await Assert.That(problems).IsEmpty();
    }

    [Test]
    public async Task Should_reject_line_directly_on_a_switch_scope()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel type = null!;
                    Haitch.Roslyn.Models.MethodModel method = null!;
                    using var file = writer.File();
                    using var t = file.Type(type);
                    using var body = t.Method(method);
                    using var sw = body.Switch("n");
                    sw.Line("x();");
            """
        );

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }

    [Test]
    public async Task Should_throw_on_the_next_case_after_a_section_that_falls_through_without_writing_it()
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                using var sw = method.Switch("n");

                using (var falling = sw.Case("1"))
                {
                    falling.Line("System.Console.WriteLine(1);");
                }

                before = writer.ToString();

                try
                {
                    sw.Case("2");
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<InvalidOperationException>();

        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    public async Task Should_render_each_jump_method_exactly()
    {
        string output = RenderMethod(body =>
        {
            using var sw = body.Switch("n");

            using (var one = sw.Case("1"))
            {
                one.Return();
            }

            using (var two = sw.Case("2"))
            {
                two.Return("n");
            }

            using (var three = sw.Case("3"))
            {
                three.Throw();
            }

            using (var four = sw.Case("4"))
            {
                four.Throw("new System.Exception()");
            }

            using var fallback = sw.Default();
            fallback.GotoCase("1");
        });

        await Assert
            .That(output)
            .IsEqualTo(
                Expected(
                    "        switch (n)\n        {\n"
                        + "            case 1:\n            {\n                return;\n            }\n"
                        + "            case 2:\n            {\n                return n;\n            }\n"
                        + "            case 3:\n            {\n                throw;\n            }\n"
                        + "            case 4:\n            {\n                throw new System.Exception();\n            }\n"
                        + "            default:\n            {\n                goto case 1;\n            }\n"
                        + "        }\n"
                )
            );
    }

    [Test]
    [Arguments(" ")]
    [Arguments("")]
    public async Task Should_reject_a_blank_goto_case_label(string label)
    {
        await Assert
            .That(() =>
                RenderMethod(body =>
                {
                    using var sw = body.Switch("n");
                    using var section = sw.Case("1");
                    section.GotoCase(label);
                })
            )
            .Throws<ArgumentException>();
    }

    [Test]
    [Arguments("break;")]
    [Arguments("return x;")]
    [Arguments("throw new System.Exception();")]
    [Arguments("continue;")]
    [Arguments("goto case 1;")]
    [Arguments("  return;")]
    [Arguments("yield break;")]
    [Arguments("  yield   break;")]
    public async Task Should_accept_a_section_ending_in_a_raw_jump_line(string jump)
    {
        string output = RenderMethod(body =>
        {
            using var sw = body.Switch("n");

            using (var first = sw.Case("1"))
            {
                first.Line("x();").Line(jump);
            }

            using var last = sw.Case("2");
            last.Line(jump);
        });

        await Assert.That(output).Contains("case 2:");
    }

    [Test]
    [Arguments("empty")]
    [Arguments("statement")]
    [Arguments("jump then statement")]
    [Arguments("keyword prefix")]
    [Arguments("nested block")]
    public async Task Should_throw_on_the_next_case_or_default_after_a_section_without_a_jump(
        string shape
    )
    {
        foreach (bool useDefault in new[] { false, true })
        {
            await Assert
                .That(() =>
                    RenderMethod(body =>
                    {
                        using var sw = body.Switch("n");

                        using (var section = sw.Case("1"))
                        {
                            switch (shape)
                            {
                                case "statement":
                                    section.Line("x();");
                                    break;
                                case "jump then statement":
                                    section.Break().Line("x();");
                                    break;
                                case "keyword prefix":
                                    section.Line("returnValue = 1;");
                                    break;
                                case "nested block":
                                    using (var inner = section.If("a"))
                                    {
                                        inner.Line("break;");
                                    }

                                    break;
                            }
                        }

                        if (useDefault)
                        {
                            sw.Default();
                        }
                        else
                        {
                            sw.Case("2");
                        }
                    })
                )
                .Throws<InvalidOperationException>();
        }
    }

    [Test]
    public async Task Should_make_to_string_throw_for_a_last_section_without_a_jump_while_dispose_does_not()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            using var sw = method.Switch("n");
            using var last = sw.Case("1");
            last.Line("x();");
        }

        await Assert.That(() => writer.ToString()).Throws<InvalidOperationException>();
        await Assert.That(() => writer.ToSourceText()).Throws<InvalidOperationException>();
    }

    [Test]
    public async Task Should_make_to_string_throw_for_an_empty_last_section()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(Sample());
            using var method = type.Method(Other());
            using var sw = method.Switch("n");
            sw.Default().Dispose();
        }

        await Assert.That(() => writer.ToString()).Throws<InvalidOperationException>();
    }

    [Test]
    public async Task Should_throw_on_a_second_default_without_writing_it()
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                using var sw = method.Switch("n");
                using (var first = sw.Default())
                {
                    first.Line("break;");
                }

                before = writer.ToString();

                try
                {
                    sw.Default();
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<InvalidOperationException>();

        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    [Arguments("")]
    [Arguments("  ")]
    [Arguments(null)]
    public async Task Should_reject_a_blank_switch_expression_without_writing(string? expression)
    {
        await AssertRejectedWithoutWriting(body => body.Switch(expression!));
    }

    [Test]
    [Arguments("null array")]
    [Arguments("empty array")]
    [Arguments("blank label")]
    public async Task Should_reject_invalid_case_labels_leaving_the_switch_open(string shape)
    {
        SourceWriter writer = new();
        string before = null!;
        string after = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                using var sw = method.Switch("n");
                before = writer.ToString();

                try
                {
                    switch (shape)
                    {
                        case "null array":
                            sw.Case(null!);
                            break;
                        case "empty array":
                            sw.Case();
                            break;
                        default:
                            sw.Case("1", " ");
                            break;
                    }
                }
                finally
                {
                    after = writer.ToString();
                }
            })
            .Throws<ArgumentException>();

        await Assert.That(before).EndsWith("        switch (n)\n        {\n");
        await Assert.That(after).IsEqualTo(before);
    }

    [Test]
    [Arguments("")]
    [Arguments("   ")]
    [Arguments("// trailing note")]
    [Arguments("  // indented note")]
    [Arguments("#pragma warning disable CS0168")]
    [Arguments("return;\n// note")]
    [Arguments("return;\n\n#region r")]
    public async Task Should_keep_a_jump_when_a_neutral_line_follows_it(string neutral)
    {
        string output = RenderMethod(body =>
        {
            using var sw = body.Switch("n");

            using (var first = sw.Case("1"))
            {
                first.Break().Line(neutral);
            }

            using var last = sw.Case("2");
            last.Break().Line(neutral);
        });

        await Assert.That(output).Contains("case 2:");
    }

    [Test]
    [Arguments("// return;")]
    [Arguments("#if X")]
    [Arguments("")]
    [Arguments("x();\n// return;")]
    public async Task Should_not_count_a_neutral_line_as_a_jump_in_an_empty_or_non_jumping_section(
        string text
    )
    {
        await Assert
            .That(() =>
                RenderMethod(body =>
                {
                    using var sw = body.Switch("n");

                    using (var first = sw.Case("1"))
                    {
                        first.Line(text);
                    }

                    using var next = sw.Case("2");
                })
            )
            .Throws<InvalidOperationException>();
    }

    private static async Task AssertRejectedWithoutWriting(Action<BodyScope> open)
    {
        SourceWriter writer = new();
        string before = null!;

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Sample());
                using var method = type.Method(Other());
                before = writer.ToString();
                open(method);
            })
            .Throws<ArgumentException>();

        await Assert.That(writer.ToString()).StartsWith(before);
        await Assert.That(writer.ToString()).DoesNotContain("stub");
        await Assert.That(writer.ToString()).DoesNotContain("foreach");
        await Assert.That(writer.ToString()).DoesNotContain("while");
        await Assert.That(writer.ToString()).DoesNotContain("using (");
        await Assert.That(writer.ToString()).DoesNotContain("for (");
    }
}
