using Haitch.Roslyn.Models;
using Haitch.Roslyn.Tests.Models;
using Haitch.Roslyn.Writing;

namespace Haitch.Roslyn.Tests.Writing.Scopes;

public class TypeScopeTests
{
    private const string NestedGenericSource =
        """
        namespace Example
        {
            public class Outer<T>
            {
                public class Inner<U> where U : class
                {
                }
            }
        }
        """;

    private static TypeModel NestedGeneric()
    {
        return TypeModel.From(CompilationHelper.GetNamedTypeSymbol(NestedGenericSource, "Example.Outer`1+Inner`1"));
    }

    private static TypeModel Plain(string name)
    {
        return TypeModel.From(
            CompilationHelper.GetNamedTypeSymbol($"namespace Example {{ public class {name} {{ }} }}",
                $"Example.{name}"));
    }

    [Test]
    public async Task Should_match_WriteTypeDeclaration_byte_for_byte_on_a_file_scope()
    {
        TypeModel model = NestedGeneric();

        SourceWriter actual = new();

        using (var file = actual.File())
        {
            using (file.Type(model)) { }
        }

        SourceWriter expected = new();
        expected.WriteAutoGeneratedHeader();

        using (expected.WriteTypeDeclaration(model)) { }

        await Assert.That(actual.ToString()).IsEqualTo(expected.ToString());
    }

    [Test]
    public async Task Should_render_a_namespaced_nested_generic_type_inside_a_namespace_block()
    {
        TypeModel model = NestedGeneric();

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace(model.Namespace!);
            using (ns.Type(model)) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Example
            {
                partial class Outer<T>
                {
                    partial class Inner<U>
                        where U : class
                    {
                    }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_write_only_the_own_declaration_for_a_type_opened_inside_a_type_scope()
    {
        TypeModel model = NestedGeneric();
        TypeModel child = Plain("Child");

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace("Example");
            using var type = ns.Type(model);
            using (type.Type(child)) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Example
            {
                partial class Outer<T>
                {
                    partial class Inner<U>
                        where U : class
                    {
                        partial class Child
                        {
                        }
                    }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_ignore_containing_types_that_end_in_the_enclosing_type_scope()
    {
        TypeModel inner = NestedGeneric();
        TypeModel outer = TypeModel.From(CompilationHelper.GetNamedTypeSymbol(NestedGenericSource, "Example.Outer`1"));

        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var type = file.Type(outer);
            using (type.Type(inner)) { }
        }

        string expected =
            """
            // <auto-generated/>
            #nullable enable

            partial class Outer<T>
            {
                partial class Inner<U>
                    where U : class
                {
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);
    }

    [Test]
    public async Task Should_reject_a_nested_type_whose_containing_types_end_elsewhere()
    {
        TypeModel inner = NestedGeneric();
        TypeModel parent = Plain("Parent");
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(parent);
                type.Type(inner);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_reject_a_file_local_nested_type()
    {
        TypeModel child = Plain("Child") with { IsFileLocal = true };
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                using var type = file.Type(Plain("Parent"));
                type.Type(child);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_separate_sibling_types_with_a_blank_line()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            using var ns = file.Namespace("Example");
            using (ns.Type(Plain("A"))) { }

            using (ns.Type(Plain("B"))) { }
        }

        await Assert.That(writer.ToString()).Contains("    }\n\n    partial class B\n");
    }

    [Test]
    public async Task Should_close_a_type_only_once_when_disposed_twice()
    {
        SourceWriter writer = new();

        using (var file = writer.File())
        {
            TypeScope scope = file.Type(Plain("A"));
            scope.Dispose();
            scope.Dispose();
        }

        await Assert.That(writer.ToString()).EndsWith("partial class A\n{\n}\n");
    }

    [Test]
    public async Task Should_reject_a_file_local_type()
    {
        TypeModel model = Plain("A") with { IsFileLocal = true };
        SourceWriter writer = new();

        await Assert
            .That(() =>
            {
                using var file = writer.File();
                file.Type(model);
            })
            .Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_compile_a_legal_type_scope_snippet()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel model = null!;
                    using var file = writer.File();
                    using var ns = file.Namespace("A");
                    using var type = ns.Type(model);
                    using (type.Type(model))
                    {
                    }
            """);

        await Assert.That(errors).IsEmpty();
    }

    [Test]
    public async Task Should_reject_a_namespace_nested_in_a_type()
    {
        string[] errors = ScopeCompileCheck.Compile(
            """
                    Haitch.Roslyn.Models.TypeModel model = null!;
                    using var file = writer.File();
                    file.Type(model).Namespace("A");
            """);

        await Assert.That(errors).IsEquivalentTo(new[] { "CS1061" });
    }
}
