// <auto-generated/>
#nullable enable

using System;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open braced body: a method body, or a nested block inside one. It exposes only
/// <see cref="Line"/> and <see cref="Block"/>, so a member or type inside a body does not compile.
/// Shares the accepted copy/parent-reuse limitation documented on <see cref="FileScope"/>.
/// Disposing the same instance twice is a no-op.
/// </summary>
internal ref struct BodyScope
{
    private readonly SourceWriter _writer;
    private SourceWriter.BlockScope _block;

    internal BodyScope(SourceWriter writer, SourceWriter.BlockScope block)
    {
        _writer = writer;
        _block = block;
    }

    /// <summary>Writes <paramref name="text"/> as one or more lines and returns this scope for chaining.</summary>
    public readonly BodyScope Line(string text)
    {
        _writer.WriteLine(text);

        return this;
    }

    /// <summary>
    /// Writes <paramref name="header"/> as a line, opens a braced block under it, and returns the
    /// block's scope; disposing that scope closes the brace.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="header"/> is null, empty or whitespace.</exception>
    public readonly BodyScope Block(string header)
    {
        if (string.IsNullOrWhiteSpace(header))
        {
            throw new ArgumentException("A block header is required.", nameof(header));
        }

        _writer.WriteLine(header);

        return new BodyScope(_writer, _writer.Block());
    }

    /// <summary>Closes the body's brace.</summary>
    public void Dispose()
    {
        _block.Dispose();
    }
}
