// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// The top level of the typed scoped writer: the generated-file header, <c>using</c> directives and
/// namespaces. Each scope is a <c>ref struct</c> so it cannot be stored, boxed or captured, and exposes
/// only the children that are legal at its position, so illegal nesting fails to compile.
/// </summary>
/// <remarks>
/// Writing to a scope while one of its child scopes is still open throws <see cref="InvalidOperationException"/>,
/// checked against the writer's open-block depth. Disposing a copy of a scope after the original is a
/// no-op. Calling <see cref="Using"/> after a namespace has been closed writes the directive after that
/// namespace, which is invalid C# (CS1529); write all usings first.
/// An <c>Attribute</c> call is buffered until the next type or member is accepted, so a rejected write
/// leaves no attribute behind. Disposing a scope with an attribute still buffered would leave it unwritten,
/// so the writer's <c>ToString()</c> throws instead (<c>Dispose</c> itself never throws).
/// </remarks>
internal readonly ref struct FileScope
{
    private readonly SourceWriter _writer;
    private readonly int _blockId;

    // Shared across copies of this ref struct; a readonly struct held by a `using` variable cannot
    // hold mutable state itself.
    private readonly State _state;

    internal FileScope(SourceWriter writer)
    {
        _writer = writer;
        _blockId = writer.InnermostBlockId;
        _state = new State();
    }

    /// <summary>Writes <c>using <paramref name="namespaceName"/>;</c>.</summary>
    /// <exception cref="InvalidOperationException">An <see cref="Attribute"/> is still waiting for its type.</exception>
    public void Using(string namespaceName)
    {
        RequireInnermost();
        ThrowIfAttributePending("a using directive");

        _writer.WriteLine($"using {namespaceName};");
        _state.NeedsBlankLine = true;
    }

    /// <summary>
    /// Writes <c>namespace <paramref name="name"/></c> and opens its block; disposing the returned scope
    /// closes the block. A blank line separates it from preceding usings or namespaces. There is no
    /// global-namespace scope: write global-namespace code directly on the file scope's writer.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="name"/> is null, empty or whitespace.</exception>
    /// <exception cref="InvalidOperationException">An <see cref="Attribute"/> is still waiting for its type.</exception>
    public NamespaceScope Namespace(string name)
    {
        RequireInnermost();
        ThrowIfAttributePending("a namespace");

        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("A namespace name is required.", nameof(name));
        }

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;
        _writer.WriteLine($"namespace {name}");

        return new NamespaceScope(_writer, _writer.Block());
    }

    /// <summary>
    /// Writes <paramref name="type"/>'s partial declaration (containing types included) at file level, for
    /// the global namespace, and returns the scope of its innermost block. A blank line separates it from
    /// preceding usings, namespaces or types.
    /// <paramref name="type"/>'s <see cref="TypeModel.Namespace"/> is ignored: the enclosing
    /// scope is the source of truth for the namespace.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is file-local, or has containing types while an <see cref="Attribute"/> is
    /// pending (it would land on the outermost containing type).
    /// </exception>
    public TypeScope Type(TypeModel type)
    {
        try
        {
            RequireInnermost();

            if (_state.Pending.Count > 0 && type.ContainingTypes.Count > 0)
            {
                throw new ArgumentException(
                    $"A pending attribute would land on the outermost containing type of '{type.Name}'.",
                    nameof(type));
            }

            TypeScope.ThrowIfFileLocal(type);
            BeginMember();

            return new TypeScope(_writer, type, _writer.WriteTypeDeclaration(type));
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes a brand-new, non-partial top-level type and opens its block; the returned scope takes members
    /// like any <see cref="TypeScope"/>. A blank line separates it from preceding usings, namespaces or
    /// types, unless an <see cref="Attribute"/> is pending.
    /// </summary>
    /// <remarks>
    /// Instance members in a new static class are not rejected (CS0708 is the caller's error). Primary
    /// constructors and records' positional parameters are not supported.
    /// </remarks>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is an illegal combination (see
    /// <see cref="SourceWriterExtensions.WriteNewTypeDeclaration"/>), or private or protected (CS1527).
    /// </exception>
    public TypeScope NewType(NewTypeModel type)
    {
        try
        {
            RequireInnermost();
            TypeScope.ThrowIfNestedOnlyAccessibility(type);
            SourceWriterExtensions.ValidateNewType(type);
            BeginMember();

            return TypeScope.OpenNewType(_writer, type);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Buffers <paramref name="attribute"/> to be written on its own line directly above the next type this
    /// scope writes, after a blank line when one is due. Call it again to stack attributes. Returns this
    /// scope for chaining. Nothing is written if that type is rejected.
    /// A rejected type consumes the pending attributes, so retry with fresh <c>Attribute</c> calls.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// An argument of <paramref name="attribute"/> is an error constant; nothing is written.
    /// </exception>
    public FileScope Attribute(AttributeModel attribute)
    {
        RequireInnermost();

        var line = SourceWriterExtensions.RenderAttribute(attribute);
        _state.Pending.Add(line);

        return this;
    }

    /// <summary>Nothing is open at file level; disposing only records a still-buffered attribute as an error.</summary>
    public void Dispose()
    {
        if (_state.Pending.Count > 0)
        {
            _state.Pending.Clear();
            _writer.RecordError("An attribute was written on a FileScope with no type after it.");
        }
    }

    private void ThrowIfAttributePending(string what)
    {
        if (_state.Pending.Count > 0)
        {
            throw new InvalidOperationException($"Cannot write {what} while an attribute is waiting for its type.");
        }
    }

    // Called only after the member passed validation, so buffered attributes never precede a rejected write.
    private readonly void BeginMember()
    {
        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        for (var i = 0; i < _state.Pending.Count; i++)
        {
            _writer.WriteLine(_state.Pending[i]);
        }

        _state.Pending.Clear();
        _state.NeedsBlankLine = true;
    }

    private readonly void RequireInnermost()
    {
        if (_writer.InnermostBlockId == _blockId)
        {
            return;
        }

        if (_writer.IsBlockOpen(_blockId))
        {
            throw new InvalidOperationException(
                "FileScope was used while a nested block opened from it is still open; dispose the nested scope first.");
        }

        throw new InvalidOperationException(
            "FileScope was used after the block it was created in was closed.");
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
        public readonly List<string> Pending = new();
    }
}

internal static class FileScopeExtensions
{
    /// <summary>
    /// Writes the auto-generated header and <c>#nullable enable</c>, and returns the file-level scope.
    /// </summary>
    public static FileScope File(this SourceWriter writer)
    {
        writer.WriteAutoGeneratedHeader();

        return new FileScope(writer);
    }
}
