// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// The top level of the typed scoped writer: the generated-file header, <c>using</c> directives and
/// namespaces. Each scope is a <c>ref struct</c> so it cannot be stored, boxed or captured, and exposes
/// only the children that are legal at its position, so illegal nesting fails to compile.
/// </summary>
/// <remarks>
/// Known limitation, accepted: a parent scope stays usable while a child is open, so text written to the
/// parent lands inside the child's block; and copying a scope then disposing both copies closes the block
/// twice. A ref struct cannot track borrow state without an allocation or a runtime check, so neither is
/// guarded. Calling <see cref="Using"/> after a namespace has been opened writes the directive inside or
/// after that namespace, which is invalid C# (CS1529); write all usings first.
/// </remarks>
internal readonly ref struct FileScope
{
    private readonly SourceWriter _writer;

    // Shared across copies of this ref struct; a readonly struct held by a `using` variable cannot
    // hold mutable state itself.
    private readonly State _state;

    internal FileScope(SourceWriter writer)
    {
        _writer = writer;
        _state = new State();
    }

    /// <summary>Writes <c>using <paramref name="namespaceName"/>;</c>.</summary>
    public void Using(string namespaceName)
    {
        _writer.WriteLine($"using {namespaceName};");
        _state.NeedsBlankLine = true;
    }

    /// <summary>
    /// Writes <c>namespace <paramref name="name"/></c> and opens its block; disposing the returned scope
    /// closes the block. A blank line separates it from preceding usings or namespaces. There is no
    /// global-namespace scope: write global-namespace code directly on the file scope's writer.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="name"/> is null, empty or whitespace.</exception>
    public NamespaceScope Namespace(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("A namespace name is required.", nameof(name));
        }

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;
        _writer.WriteLine($"namespace {name}");

        return new NamespaceScope(_writer, _writer.Block());
    }

    /// <summary>
    /// Writes <paramref name="type"/>'s partial declaration (containing types included) at file level, for
    /// the global namespace, and returns the scope of its innermost block. A blank line separates it from
    /// preceding usings, namespaces or types.
    /// <paramref name="type"/>'s <see cref="TypeModel.Namespace"/> is ignored: the enclosing
    /// scope is the source of truth for the namespace.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="type"/> is file-local.</exception>
    public TypeScope Type(TypeModel type)
    {
        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;

        return new TypeScope(_writer, type, _writer.WriteTypeDeclaration(type));
    }

    /// <summary>Nothing is open at file level, so disposing is a no-op that exists for <c>using</c>.</summary>
    public void Dispose()
    {
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
    }
}

internal static class FileScopeExtensions
{
    /// <summary>
    /// Writes the auto-generated header and <c>#nullable enable</c>, and returns the file-level scope.
    /// </summary>
    public static FileScope File(this SourceWriter writer)
    {
        writer.WriteAutoGeneratedHeader();

        return new FileScope(writer);
    }
}
