// <auto-generated/>
#nullable enable

using System.Collections.Generic;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open <c>namespace</c> block. It exposes no <c>Namespace</c> member, so nesting a namespace in a
/// namespace does not compile. Writing to it while a child scope is open throws; see
/// <see cref="FileScope"/>. Disposing the same instance twice, or a copy, is a no-op.
/// </summary>
internal ref struct NamespaceScope
{
    private readonly SourceWriter _writer;
    private readonly int _blockId;
    private SourceWriter.BlockScope _block;

    // Shared across copies; see FileScope.
    private readonly State _state;

    internal NamespaceScope(SourceWriter writer, SourceWriter.BlockScope block)
    {
        _writer = writer;
        _block = block;
        _blockId = writer.InnermostBlockId;
        _state = new State();
    }

    /// <summary>
    /// Writes <paramref name="type"/>'s partial declaration (containing types included) and returns the
    /// scope of its innermost block. A blank line separates it from a preceding sibling type.
    /// <paramref name="type"/>'s <see cref="TypeModel.Namespace"/> is ignored: the enclosing
    /// scope is the source of truth for the namespace.
    /// </summary>
    /// <param name="type">The type to declare.</param>
    /// <param name="baseTypes">
    /// Extra base types written on the innermost declaration only, never on its containing types, and
    /// not validated: the compiler reports conflicts with the other declarations of the type.
    /// </param>
    /// <exception cref="System.ArgumentException">
    /// <paramref name="type"/> is file-local, or has containing types while an <see cref="Attribute"/> is
    /// pending (it would land on the outermost containing type).
    /// </exception>
    public TypeScope Type(TypeModel type, EquatableArray<TypeRef> baseTypes = default)
    {
        try
        {
            RequireInnermost();

            if (_state.Pending.Count > 0 && type.ContainingTypes.Count > 0)
            {
                throw new System.ArgumentException(
                    $"A pending attribute would land on the outermost containing type of '{type.Name}'.",
                    nameof(type));
            }

            TypeScope.ThrowIfFileLocal(type);
            BeginMember();

            return new TypeScope(_writer, type, _writer.WriteTypeDeclaration(type, baseTypes));
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes a brand-new, non-partial type and opens its block; the returned scope takes members like any
    /// <see cref="TypeScope"/>. A blank line separates it from a preceding sibling type, unless an
    /// <see cref="Attribute"/> is pending.
    /// </summary>
    /// <remarks>
    /// Instance members in a new static class are not rejected (CS0708 is the caller's error). Primary
    /// constructors and records' positional parameters are not supported.
    /// </remarks>
    /// <exception cref="System.ArgumentException">
    /// <paramref name="type"/> is an illegal combination (see
    /// <see cref="SourceWriterExtensions.WriteNewTypeDeclaration"/>), or private or protected (CS1527).
    /// </exception>
    public TypeScope NewType(NewTypeModel type)
    {
        try
        {
            RequireInnermost();
            TypeScope.ThrowIfNestedOnlyAccessibility(type);
            SourceWriterExtensions.ValidateNewType(type);
            BeginMember();

            return TypeScope.OpenNewType(_writer, type);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Buffers <paramref name="attribute"/> to be written on its own line directly above the next type this
    /// scope writes, after a blank line when one is due. Call it again to stack attributes. Returns this
    /// scope for chaining. Nothing is written if that type is rejected.
    /// A rejected type consumes the pending attributes, so retry with fresh <c>Attribute</c> calls.
    /// </summary>
    /// <exception cref="System.ArgumentException">
    /// An argument of <paramref name="attribute"/> is an error constant; nothing is written.
    /// </exception>
    public NamespaceScope Attribute(AttributeModel attribute)
    {
        RequireInnermost();

        var line = SourceWriterExtensions.RenderAttribute(attribute);
        _state.Pending.Add(line);

        return this;
    }

    /// <summary>Closes the namespace block, recording a still-buffered attribute as an error.</summary>
    public void Dispose()
    {
        if (_state.Pending.Count > 0)
        {
            _state.Pending.Clear();
            _writer.RecordError("An attribute was written on a NamespaceScope with no type after it.");
        }

        _block.Dispose();
    }

    // Called only after the member passed validation, so buffered attributes never precede a rejected write.
    private readonly void BeginMember()
    {
        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        for (var i = 0; i < _state.Pending.Count; i++)
        {
            _writer.WriteLine(_state.Pending[i]);
        }

        _state.Pending.Clear();
        _state.NeedsBlankLine = true;
    }

    private readonly void RequireInnermost()
    {
        if (_writer.InnermostBlockId == _blockId)
        {
            return;
        }

        if (_writer.IsBlockOpen(_blockId))
        {
            throw new System.InvalidOperationException(
                "NamespaceScope was used while a nested block opened from it is still open; dispose the nested scope first.");
        }

        throw new System.InvalidOperationException(
            "NamespaceScope was used after its block was closed, likely through a copy that was disposed.");
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
        public readonly List<string> Pending = new();
    }
}
