// <auto-generated/>
#nullable enable

using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open <c>namespace</c> block. It exposes no <c>Namespace</c> member, so nesting a namespace in a
/// namespace does not compile. Shares the accepted copy/parent-reuse limitation documented on
/// <see cref="FileScope"/>; disposing the same instance twice is a no-op.
/// </summary>
internal ref struct NamespaceScope
{
    private readonly SourceWriter _writer;
    private SourceWriter.BlockScope _block;

    // Shared across copies; see FileScope.
    private readonly State _state;

    internal NamespaceScope(SourceWriter writer, SourceWriter.BlockScope block)
    {
        _writer = writer;
        _block = block;
        _state = new State();
    }

    /// <summary>
    /// Writes <paramref name="type"/>'s partial declaration (containing types included) and returns the
    /// scope of its innermost block. A blank line separates it from a preceding sibling type.
    /// <paramref name="type"/>'s <see cref="TypeModel.Namespace"/> is ignored: the enclosing
    /// scope is the source of truth for the namespace.
    /// </summary>
    /// <exception cref="System.ArgumentException">
    /// <paramref name="type"/> is file-local, or has containing types while an <see cref="Attribute"/> is
    /// pending (it would land on the outermost containing type).
    /// </exception>
    public TypeScope Type(TypeModel type)
    {
        if (_state.AfterAttribute && type.ContainingTypes.Count > 0)
        {
            throw new System.ArgumentException(
                $"A pending attribute would land on the outermost containing type of '{type.Name}'.",
                nameof(type));
        }

        if (_state.NeedsBlankLine && !_state.AfterAttribute)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;
        _state.AfterAttribute = false;

        return new TypeScope(_writer, type, _writer.WriteTypeDeclaration(type));
    }

    /// <summary>
    /// Writes a brand-new, non-partial type and opens its block; the returned scope takes members like any
    /// <see cref="TypeScope"/>. A blank line separates it from a preceding sibling type, unless an
    /// <see cref="Attribute"/> is pending.
    /// </summary>
    /// <remarks>
    /// Instance members in a new static class are not rejected (CS0708 is the caller's error). Primary
    /// constructors and records' positional parameters are not supported.
    /// </remarks>
    /// <exception cref="System.ArgumentException">
    /// <paramref name="type"/> is an illegal combination (see
    /// <see cref="SourceWriterExtensions.WriteNewTypeDeclaration"/>), or private or protected (CS1527).
    /// </exception>
    public TypeScope NewType(NewTypeModel type)
    {
        TypeScope.ThrowIfNestedOnlyAccessibility(type);
        SourceWriterExtensions.ValidateNewType(type);

        if (_state.NeedsBlankLine && !_state.AfterAttribute)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;
        _state.AfterAttribute = false;

        return TypeScope.OpenNewType(_writer, type);
    }

    /// <summary>
    /// Writes <paramref name="attribute"/> on its own line directly above the next type this scope writes,
    /// after a blank line when one is due; the type then adds no blank line of its own. Call it again to
    /// stack attributes. Returns this scope for chaining.
    /// </summary>
    /// <exception cref="System.ArgumentException">
    /// An argument of <paramref name="attribute"/> is an error constant; nothing is written.
    /// </exception>
    public NamespaceScope Attribute(AttributeModel attribute)
    {
        var line = SourceWriterExtensions.RenderAttribute(attribute);

        if (_state.NeedsBlankLine && !_state.AfterAttribute)
        {
            _writer.WriteLine();
        }

        _state.AfterAttribute = true;
        _writer.WriteLine(line);

        return this;
    }

    /// <summary>Closes the namespace block.</summary>
    public void Dispose()
    {
        _block.Dispose();
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
        public bool AfterAttribute;
    }
}
