// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open property block. It exposes only <see cref="Get"/>, <see cref="Set"/> and <see cref="Init"/>, so a
/// line or a member directly inside a property does not compile.
/// Opening an accessor while a previous accessor's body is still open throws, so dispose each accessor
/// scope before opening the next; see <see cref="FileScope"/>. Disposing the same instance twice, or a
/// copy, is a no-op.
/// </summary>
internal ref struct PropertyScope
{
    private readonly SourceWriter _writer;
    private readonly int _blockId;
    private readonly PropertyModel _model;
    private SourceWriter.BlockScope _block;

    // Shared across copies: a using local is readonly, so flags on the struct would be lost on a defensive copy.
    private readonly State _state;

    internal PropertyScope(SourceWriter writer, PropertyModel model, SourceWriter.BlockScope block)
    {
        _writer = writer;
        _model = model;
        _block = block;
        _blockId = writer.InnermostBlockId;
        _state = new State();
    }

    /// <summary>Writes the <c>get</c> accessor line and opens its braced body.</summary>
    /// <exception cref="ArgumentException">The model has no get accessor.</exception>
    /// <exception cref="InvalidOperationException">Called a second time on this scope, or while an accessor body is open.</exception>
    public readonly BodyScope Get()
    {
        return Open(PropertyAccessorKind.Get);
    }

    /// <summary>Writes the <c>set</c> accessor line and opens its braced body.</summary>
    /// <exception cref="ArgumentException">The model has no set accessor (an init accessor does not count).</exception>
    /// <exception cref="InvalidOperationException">Called a second time on this scope, or while an accessor body is open.</exception>
    public readonly BodyScope Set()
    {
        return Open(PropertyAccessorKind.Set);
    }

    /// <summary>Writes the <c>init</c> accessor line and opens its braced body.</summary>
    /// <exception cref="ArgumentException">The model has no init accessor.</exception>
    /// <exception cref="InvalidOperationException">Called a second time on this scope, or while an accessor body is open.</exception>
    public readonly BodyScope Init()
    {
        return Open(PropertyAccessorKind.Init);
    }

    // Resolves the accessor before writing so a rejected request leaves the writer untouched.
    private readonly BodyScope Open(PropertyAccessorKind kind)
    {
        PropertyAccessorModel? accessor = null;

        for (var i = 0; i < _model.Accessors.Count; i++)
        {
            if (_model.Accessors[i].Kind == kind)
            {
                accessor = _model.Accessors[i];
            }
        }

        if (accessor is null)
        {
            throw new ArgumentException($"'{_model.Name}' has no {kind.ToString().ToLowerInvariant()} accessor.");
        }

        RequireInnermost();
        MarkOpened(kind);

        _writer.WriteLine(SourceWriterExtensions.RenderAccessorKeyword(accessor, _model.Accessibility));

        return new BodyScope(_writer, _writer.Block());
    }

    private readonly void MarkOpened(PropertyAccessorKind kind)
    {
        var alreadyOpened = kind switch
        {
            PropertyAccessorKind.Get => _state.OpenedGet,
            PropertyAccessorKind.Set => _state.OpenedSet,
            _ => _state.OpenedInit,
        };

        if (alreadyOpened)
        {
            throw new InvalidOperationException(
                $"The {kind.ToString().ToLowerInvariant()} accessor of '{_model.Name}' was already written.");
        }

        switch (kind)
        {
            case PropertyAccessorKind.Get:
                _state.OpenedGet = true;
                break;
            case PropertyAccessorKind.Set:
                _state.OpenedSet = true;
                break;
            default:
                _state.OpenedInit = true;
                break;
        }
    }

    private readonly void RequireInnermost()
    {
        if (_writer.InnermostBlockId == _blockId)
        {
            return;
        }

        if (_writer.IsBlockOpen(_blockId))
        {
            throw new InvalidOperationException(
                "PropertyScope was used while an accessor body opened from it is still open; dispose the accessor scope first.");
        }

        throw new InvalidOperationException(
            "PropertyScope was used after its block was closed, likely through a copy that was disposed.");
    }

    /// <summary>Closes the property's brace.</summary>
    public void Dispose()
    {
        _block.Dispose();
    }

    private sealed class State
    {
        public bool OpenedGet;
        public bool OpenedSet;
        public bool OpenedInit;
    }
}
