// <auto-generated/>
#nullable enable

using System;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open <c>switch</c> statement. It exposes only <see cref="Case"/> and <see cref="Default"/>, so a statement
/// directly inside a switch, outside any section, does not compile. Each section is a braced <see cref="BodyScope"/>.
/// Shares the accepted copy/parent-reuse limitation documented on <see cref="FileScope"/>.
/// Disposing the same instance twice is a no-op.
/// The caller writes each section's <c>break;</c> or <c>return</c>: a section that can fall through renders
/// output that does not compile (CS0163, or CS8070 for the final section); this is a caller error and nothing detects it.
/// Calling <see cref="Case"/> or <see cref="Default"/> while the previous section's <see cref="BodyScope"/> is still
/// open misnests the output, so dispose each section before opening the next.
/// Switch expressions are not supported.
/// </summary>
internal ref struct SwitchScope
{
    private readonly SourceWriter _writer;

    // Shared across copies: a using local is readonly, so a flag on the struct would be lost on a defensive copy.
    private readonly State _state;

    private SourceWriter.BlockScope _block;

    internal SwitchScope(SourceWriter writer, SourceWriter.BlockScope block)
    {
        _writer = writer;
        _block = block;
        _state = new State();
    }

    /// <summary>
    /// Writes one <c>case label:</c> line per label, then opens a braced section body under them. Labels are
    /// written verbatim between <c>case </c> and <c>:</c>, so a pattern label such as <c>int i when i &gt; 0</c> works
    /// and <c>_</c> gives <c>case _:</c> (the discard pattern). Do not include <c>case</c> or the colon: <c>"1:"</c> writes <c>case 1::</c>.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="labels"/> is null or empty, or a label is null, empty or whitespace.</exception>
    public readonly BodyScope Case(params string[] labels)
    {
        if (labels is null || labels.Length == 0)
        {
            throw new ArgumentException("At least one case label is required.", nameof(labels));
        }

        foreach (string label in labels)
        {
            if (string.IsNullOrWhiteSpace(label))
            {
                throw new ArgumentException("A case label is required.", nameof(labels));
            }
        }

        foreach (string label in labels)
        {
            _writer.WriteLine($"case {label}:");
        }

        return new BodyScope(_writer, _writer.Block());
    }

    /// <summary>Writes <c>default:</c> and opens a braced section body under it.</summary>
    /// <exception cref="InvalidOperationException">This switch already has a default section.</exception>
    public readonly BodyScope Default()
    {
        if (_state.DefaultWritten)
        {
            throw new InvalidOperationException("A switch can have only one default section.");
        }

        _state.DefaultWritten = true;
        _writer.WriteLine("default:");

        return new BodyScope(_writer, _writer.Block());
    }

    /// <summary>Closes the switch's brace.</summary>
    public void Dispose()
    {
        _block.Dispose();
    }

    private sealed class State
    {
        public bool DefaultWritten;
    }
}
