// <auto-generated/>
#nullable enable

using System;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open <c>try</c> or <c>catch</c> block. Like <see cref="BodyScope"/> it exposes statement members, plus
/// <see cref="Catch"/> and <see cref="Finally"/>, which close this block and open the next.
/// <see cref="Finally"/> returns a <see cref="BodyScope"/>, so nothing can follow it in the chain.
/// Shares the accepted copy/parent-reuse limitation documented on <see cref="FileScope"/>.
/// Disposing the same instance twice, or disposing a block that was already chained, is a no-op.
/// A <c>try</c> with neither <see cref="Catch"/> nor <see cref="Finally"/> renders a lone <c>try</c> block that
/// does not compile (CS1524); this is a caller error and <see cref="Dispose"/> never throws for it.
/// Catch ordering is also the caller's job: a more-derived exception type after a less-derived one does not
/// compile (CS0160), and the scope does not check it.
/// A catch identifier the body never uses compiles with warning CS0168.
/// Writing through a block after chaining it lands in the newest open block, so write each block's
/// content before opening the next.
/// Calling <see cref="Catch"/> or <see cref="Finally"/> while a nested block opened from this block is still
/// open closes that innermost brace first, misnesting the output, so dispose nested scopes before chaining.
/// </summary>
internal ref struct TryScope
{
    private readonly SourceWriter _writer;

    // Shared across copies: a using local is readonly, so flags on the struct would be lost on a defensive copy.
    private readonly State _state;

    internal TryScope(SourceWriter writer, SourceWriter.BlockScope block, bool generalCatch = false)
    {
        _writer = writer;
        _state = new State { Block = block, GeneralCatch = generalCatch };
    }

    /// <summary>Writes <paramref name="text"/> as one or more lines and returns this scope for chaining.</summary>
    public readonly TryScope Line(string text)
    {
        _writer.WriteLine(text);

        return this;
    }

    /// <summary>
    /// Writes <paramref name="header"/> as a line, opens a braced block under it, and returns the
    /// block's scope; disposing that scope closes the brace.
    /// </summary>
    /// <exception cref="ArgumentException"><paramref name="header"/> is null, empty or whitespace.</exception>
    public readonly BodyScope Block(string header)
    {
        return BodyScope.OpenBlock(_writer, header);
    }

    public readonly BodyScope ForEach(string type, string identifier, string collection)
    {
        return BodyScope.OpenForEach(_writer, type, identifier, collection);
    }

    public readonly BodyScope For(string initializer, string condition, string iterator)
    {
        return BodyScope.OpenFor(_writer, initializer, condition, iterator);
    }

    public readonly BodyScope While(string condition)
    {
        return BodyScope.OpenWhile(_writer, condition);
    }

    public readonly SwitchScope Switch(string expression)
    {
        return BodyScope.OpenSwitch(_writer, expression);
    }

    public readonly BodyScope Using(string resource)
    {
        return BodyScope.OpenUsing(_writer, resource);
    }

    public readonly IfScope If(string condition)
    {
        return BodyScope.OpenIf(_writer, condition);
    }

    public readonly TryScope Try()
    {
        return BodyScope.OpenTry(_writer);
    }

    /// <summary>
    /// Closes this block and writes <c>catch</c>, optionally followed by <c>(type identifier)</c> and
    /// <c>when (filter)</c>, then opens its braced body. A null argument is omitted; a blank one is rejected.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// A given argument is empty or whitespace, or <paramref name="identifier"/> is given without <paramref name="type"/>.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// This block was already chained, or an unfiltered general <c>catch</c> already precedes it.
    /// </exception>
    public readonly TryScope Catch(string? type = null, string? identifier = null, string? filter = null)
    {
        RequireTextIfGiven(type, nameof(type));
        RequireTextIfGiven(identifier, nameof(identifier));
        RequireTextIfGiven(filter, nameof(filter));

        if (identifier is not null && type is null)
        {
            throw new ArgumentException("A catch identifier requires a type.", nameof(identifier));
        }

        if (_state.GeneralCatch)
        {
            throw new InvalidOperationException("A catch cannot follow a general catch.");
        }

        string header = "catch";

        if (type is not null)
        {
            header += identifier is null ? $" ({type})" : $" ({type} {identifier})";
        }

        if (filter is not null)
        {
            header += $" when ({filter})";
        }

        CloseForChain();
        _writer.WriteLine(header);

        return new TryScope(_writer, _writer.Block(), generalCatch: type is null && filter is null);
    }

    /// <summary>Closes this block, writes <c>finally</c> and opens its braced body.</summary>
    /// <exception cref="InvalidOperationException">This block was already chained.</exception>
    public readonly BodyScope Finally()
    {
        CloseForChain();
        _writer.WriteLine("finally");

        return new BodyScope(_writer, _writer.Block());
    }

    private static void RequireTextIfGiven(string? value, string name)
    {
        if (value is not null && string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("A value is required when given.", name);
        }
    }

    private readonly void CloseForChain()
    {
        if (_state.Chained)
        {
            throw new InvalidOperationException("This block was already followed by a catch or finally.");
        }

        _state.Chained = true;
        _state.Block.Dispose();
    }

    /// <summary>Closes the block's brace unless it was already closed by chaining.</summary>
    public void Dispose()
    {
        _state.Block.Dispose();
    }

    private sealed class State
    {
        public SourceWriter.BlockScope Block;
        public bool Chained;
        public bool GeneralCatch;
    }
}
