// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open type block. It exposes no <c>Namespace</c> member, so a namespace inside a type does not
/// compile. Writing to it while a child scope is open throws; see <see cref="FileScope"/>.
/// Disposing the same instance twice, or a copy, is a no-op.
/// </summary>
internal ref struct TypeScope
{
    private readonly SourceWriter _writer;
    private readonly int _blockId;
    private readonly TypeModel _model;
    private SourceWriterExtensions.TypeDeclarationScope _declaration;

    // Shared across copies; see FileScope.
    private readonly State _state;

    internal TypeScope(SourceWriter writer, TypeModel model, SourceWriterExtensions.TypeDeclarationScope declaration)
    {
        _writer = writer;
        _blockId = writer.InnermostBlockId;
        _model = model;
        _declaration = declaration;
        _state = new State();
    }

    /// <summary>
    /// Writes a nested partial declaration of <paramref name="type"/> alone and opens its block. Its
    /// <see cref="TypeModel.ContainingTypes"/> are ignored: this scope already wrote the enclosing types.
    /// A blank line separates it from a preceding sibling.
    /// </summary>
    /// <param name="type">The type to declare.</param>
    /// <param name="baseTypes">
    /// Extra base types written on this declaration only, and not validated: the compiler reports
    /// conflicts with the other declarations of the type.
    /// </param>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is file-local, or has containing types whose last entry is not this scope's
    /// type. An empty containing-type chain is accepted.
    /// </exception>
    public TypeScope Type(TypeModel type, EquatableArray<TypeRef> baseTypes = default)
    {
        try
        {
            ThrowIfFileLocal(type);

            if (type.ContainingTypes.Count > 0 && !IsThisType(type.ContainingTypes[type.ContainingTypes.Count - 1]))
            {
                throw new ArgumentException(
                    $"'{type.Name}' is not nested in '{_model.Name}': its innermost containing type is different.",
                    nameof(type));
            }

            BeginMember();

            SourceWriterExtensions.WriteTypeDeclarationLine(
                _writer,
                type.IsReadOnly,
                type.IsRefLikeType,
                type.Kind,
                type.Name,
                type.TypeParameters,
                baseTypes);

            return new TypeScope(_writer, type, new SourceWriterExtensions.TypeDeclarationScope([_writer.Block()]));
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes a brand-new, non-partial nested type and opens its block; the returned scope takes members
    /// like any <see cref="TypeScope"/>. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <remarks>
    /// Instance members in a new static class are not rejected (CS0708 is the caller's error). Primary
    /// constructors and records' positional parameters are not supported.
    /// </remarks>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is an illegal combination (see
    /// <see cref="SourceWriterExtensions.WriteNewTypeDeclaration"/>), is file-local (CS9054), or is
    /// protected in any form while this scope is a struct (CS0666) or a static class (CS1057).
    /// </exception>
    public TypeScope NewType(NewTypeModel type)
    {
        try
        {
            if (type.IsFileLocal)
            {
                throw new ArgumentException($"'{type.Name}' is file-local, which is illegal on a nested type.", nameof(type));
            }

            if (type.Accessibility is Accessibility.Protected or Accessibility.ProtectedOrInternal
                    or Accessibility.ProtectedAndInternal
                && (_model.IsStatic || _model.Kind is TypeDeclarationKind.Struct or TypeDeclarationKind.RecordStruct))
            {
                throw new ArgumentException(
                    $"'{type.Name}' is {type.Accessibility}, which is illegal inside struct or static class '{_model.Name}'.",
                    nameof(type));
            }

            SourceWriterExtensions.ValidateNewType(type);
            BeginMember();

            return OpenNewType(_writer, type);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    internal static void ThrowIfFileLocal(TypeModel type)
    {
        if (type.IsFileLocal)
        {
            throw new ArgumentException(
                "Cannot write a partial declaration for a file-local type: file-local types cannot be split "
                    + "across a generated partial declaration in a different file.",
                nameof(type));
        }
    }

    internal static void ThrowIfNestedOnlyAccessibility(NewTypeModel type)
    {
        if (type.Accessibility
            is Accessibility.Private
                or Accessibility.Protected
                or Accessibility.ProtectedOrInternal
                or Accessibility.ProtectedAndInternal)
        {
            throw new ArgumentException(
                $"'{type.Name}' is {type.Accessibility}, which is illegal on a top-level type.",
                nameof(type));
        }
    }

    // TypeScope works from a TypeModel, so the new type is described as one with no containing types.
    internal static TypeScope OpenNewType(SourceWriter writer, NewTypeModel type)
    {
        var model = new TypeModel(
            null,
            type.Name,
            type.Kind,
            type.Accessibility,
            type.IsStatic,
            type.IsAbstract,
            type.IsSealed,
            type.IsReadOnly,
            type.IsRefLikeType,
            type.IsFileLocal,
            type.TypeParameters,
            default,
            default,
            default,
            default,
            default);

        var declaration = new SourceWriterExtensions.TypeDeclarationScope(
            [SourceWriterExtensions.WriteNewTypeDeclaration(writer, type)]);

        return new TypeScope(writer, model, declaration);
    }

    /// <summary>
    /// Writes <paramref name="method"/>'s signature (without <c>;</c>) and opens its braced body. A blank
    /// line separates it from a preceding sibling member or type.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="method"/> is abstract (including interface members) or extern, so a body is illegal;
    /// write its signature with <see cref="SourceWriterExtensions.WriteMethodSignature"/> instead.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// <paramref name="method"/>'s kind is neither Ordinary nor ExplicitInterfaceImplementation
    /// (for example a constructor, destructor, operator or conversion).
    /// </exception>
    public BodyScope Method(MethodModel method)
    {
        try
        {
            if (method.IsAbstract || method.IsExtern)
            {
                throw new ArgumentException(
                    $"'{method.Name}' is abstract or extern and cannot have a body; use WriteMethodSignature.",
                    nameof(method));
            }

            // Rendered first: a model that cannot be rendered must not leave attributes behind.
            var header = SourceWriterExtensions.RenderMethodHeader(method);

            BeginMember();

            _writer.WriteLine(header);

            return new BodyScope(_writer, _writer.Block());
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes one field declaration line. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <param name="field">The field to declare; a const field is written from its constant value.</param>
    /// <param name="initializer">An optional raw initializer expression; not allowed for a const field.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="field"/> is const and has an <paramref name="initializer"/> or no constant value, or
    /// <paramref name="initializer"/> is blank, or this scope is an interface and the field is neither static nor const.
    /// </exception>
    public void Field(FieldModel field, string? initializer = null)
    {
        try
        {
            if (_model.Kind == TypeDeclarationKind.Interface && !field.IsStatic && !field.IsConst)
            {
                throw new ArgumentException($"'{field.Name}' is an instance field; interfaces cannot declare them.", nameof(field));
            }

            var line = SourceWriterExtensions.RenderField(field, initializer);

            WriteMember(line);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes one auto-property declaration line such as <c>public int X { get; private set; }</c>, whatever
    /// the source property's shape (accessor bodies, expression bodies and <c>field</c>-keyword accessors all
    /// become auto accessors). A ref-returning model is rejected because a ref property cannot be an auto
    /// property. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="property"/> is abstract (including interface members), an explicit interface
    /// implementation (<see cref="PropertyModel.ExplicitInterface"/> is set), returns by ref, or has no get
    /// accessor; or this scope is an interface and the property is not static.
    /// </exception>
    public void AutoProperty(PropertyModel property)
    {
        try
        {
            if (_model.Kind == TypeDeclarationKind.Interface && !property.IsStatic)
            {
                throw new ArgumentException(
                    $"'{property.Name}' is an instance property; interfaces cannot declare auto-properties.",
                    nameof(property));
            }

            var line = SourceWriterExtensions.RenderAutoProperty(property);

            WriteMember(line);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes <paramref name="property"/>'s header and opens its braced accessor list; the returned scope's
    /// <see cref="PropertyScope.Get"/>, <see cref="PropertyScope.Set"/> and <see cref="PropertyScope.Init"/>
    /// open the accessor bodies. A ref or <c>ref readonly</c> model is written with that modifier. A blank
    /// line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="property"/> is abstract (including interface members without a default body), an
    /// explicit interface implementation (<see cref="PropertyModel.ExplicitInterface"/> is set), has no
    /// accessors, or returns by ref yet has a <c>set</c> or <c>init</c> accessor (CS8147).
    /// </exception>
    public PropertyScope Property(PropertyModel property)
    {
        try
        {
            if (property.IsAbstract)
            {
                throw new ArgumentException(
                    $"'{property.Name}' is abstract (or an interface member) and cannot have accessor bodies.",
                    nameof(property));
            }

            if (property.ExplicitInterface is not null)
            {
                throw new ArgumentException(
                    $"'{property.Name}' is an explicit interface implementation, which cannot be written with a public header.",
                    nameof(property));
            }

            if (property.Accessors.Count == 0)
            {
                throw new ArgumentException($"'{property.Name}' has no accessors.", nameof(property));
            }

            if (property.ReturnRefKind != ReturnRefKind.None && HasSetOrInit(property))
            {
                throw new ArgumentException(
                    $"'{property.Name}' returns by ref and cannot have a set or init accessor.",
                    nameof(property));
            }

            var header = SourceWriterExtensions.RenderPropertyHeader(property);

            BeginMember();

            _writer.WriteLine(header);

            return new PropertyScope(_writer, property, _writer.Block());
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>
    /// Writes one field-like event declaration line such as <c>public event global::System.EventHandler? Changed;</c>.
    /// A blank line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="evt"/> is not field-like (it has written-out accessors) or is an explicit interface
    /// implementation (<see cref="EventModel.ExplicitInterface"/> is set).
    /// </exception>
    public void Event(EventModel evt)
    {
        try
        {
            var line = SourceWriterExtensions.RenderEvent(evt);

            WriteMember(line);
        }
        catch
        {
            _state.Pending.Clear();

            throw;
        }
    }

    /// <summary>Writes <paramref name="text"/> as one or more lines and returns this scope for chaining.</summary>
    /// <remarks>A buffered attribute is written after the line, above the next member.</remarks>
    public readonly TypeScope Line(string text = "")
    {
        RequireInnermost();
        _writer.WriteLine(text);

        return this;
    }

    private static bool HasSetOrInit(PropertyModel property)
    {
        for (var i = 0; i < property.Accessors.Count; i++)
        {
            if (property.Accessors[i].Kind is PropertyAccessorKind.Set or PropertyAccessorKind.Init)
            {
                return true;
            }
        }

        return false;
    }

    // Renders before writing so a rejected model leaves the writer untouched.
    private void WriteMember(string line)
    {
        BeginMember();

        _writer.WriteLine(line);
    }

    // Called only after the member passed validation, so buffered attributes never precede a rejected write.
    private readonly void BeginMember()
    {
        RequireInnermost();

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        for (var i = 0; i < _state.Pending.Count; i++)
        {
            _writer.WriteLine(_state.Pending[i]);
        }

        _state.Pending.Clear();
        _state.NeedsBlankLine = true;
    }

    /// <summary>
    /// Buffers <paramref name="attribute"/> to be written on its own line directly above the next type or
    /// member this scope writes, after a blank line when one is due. Call it again to stack attributes.
    /// Returns this scope for chaining. Nothing is written if that member is rejected.
    /// A rejected member consumes the pending attributes, so retry with fresh <c>Attribute</c> calls.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// An argument of <paramref name="attribute"/> is an error constant; nothing is written.
    /// </exception>
    public TypeScope Attribute(AttributeModel attribute)
    {
        RequireInnermost();

        var line = SourceWriterExtensions.RenderAttribute(attribute);
        _state.Pending.Add(line);

        return this;
    }

    /// <summary>
    /// Closes the type's block, and those of its containing types when it opened them, recording a
    /// still-buffered attribute as an error.
    /// </summary>
    public void Dispose()
    {
        if (_state.Pending.Count > 0)
        {
            _state.Pending.Clear();
            _writer.RecordError($"An attribute was written on TypeScope '{_model.Name}' with no member after it.");
        }

        _declaration.Dispose();
    }

    private bool IsThisType(ContainingTypeModel containingType)
    {
        return containingType.Name == _model.Name
            && containingType.Kind == _model.Kind
            && containingType.TypeParameters.Equals(_model.TypeParameters);
    }

    private readonly void RequireInnermost()
    {
        if (_writer.InnermostBlockId == _blockId)
        {
            return;
        }

        if (_writer.IsBlockOpen(_blockId))
        {
            throw new InvalidOperationException(
                "TypeScope was used while a nested block opened from it is still open; dispose the nested scope first.");
        }

        throw new InvalidOperationException(
            "TypeScope was used after its block was closed, likely through a copy that was disposed.");
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
        public readonly List<string> Pending = new();
    }
}
