// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Models;

namespace Haitch.Roslyn.Writing;

/// <summary>
/// An open type block. It exposes no <c>Namespace</c> member, so a namespace inside a type does not
/// compile. Shares the accepted copy/parent-reuse limitation documented on <see cref="FileScope"/>.
/// Disposing the same instance twice is a no-op.
/// </summary>
internal ref struct TypeScope
{
    private readonly SourceWriter _writer;
    private readonly TypeModel _model;
    private SourceWriterExtensions.TypeDeclarationScope _declaration;

    // Shared across copies; see FileScope.
    private readonly State _state;

    internal TypeScope(SourceWriter writer, TypeModel model, SourceWriterExtensions.TypeDeclarationScope declaration)
    {
        _writer = writer;
        _model = model;
        _declaration = declaration;
        _state = new State();
    }

    /// <summary>
    /// Writes a nested partial declaration of <paramref name="type"/> alone and opens its block. Its
    /// <see cref="TypeModel.ContainingTypes"/> are ignored: this scope already wrote the enclosing types.
    /// A blank line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="type"/> is file-local, or has containing types whose last entry is not this scope's
    /// type. An empty containing-type chain is accepted.
    /// </exception>
    public TypeScope Type(TypeModel type)
    {
        if (type.IsFileLocal)
        {
            throw new ArgumentException(
                "Cannot write a partial declaration for a file-local type: file-local types cannot be split "
                    + "across a generated partial declaration in a different file.",
                nameof(type));
        }

        if (type.ContainingTypes.Count > 0 && !IsThisType(type.ContainingTypes[type.ContainingTypes.Count - 1]))
        {
            throw new ArgumentException(
                $"'{type.Name}' is not nested in '{_model.Name}': its innermost containing type is different.",
                nameof(type));
        }

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;

        SourceWriterExtensions.WriteTypeDeclarationLine(
            _writer,
            type.IsReadOnly,
            type.IsRefLikeType,
            type.Kind,
            type.Name,
            type.TypeParameters);

        return new TypeScope(_writer, type, new SourceWriterExtensions.TypeDeclarationScope([_writer.Block()]));
    }

    /// <summary>
    /// Writes <paramref name="method"/>'s signature (without <c>;</c>) and opens its braced body. A blank
    /// line separates it from a preceding sibling member or type.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="method"/> is abstract (including interface members) or extern, so a body is illegal;
    /// write its signature with <see cref="SourceWriterExtensions.WriteMethodSignature"/> instead.
    /// </exception>
    public BodyScope Method(MethodModel method)
    {
        if (method.IsAbstract || method.IsExtern)
        {
            throw new ArgumentException(
                $"'{method.Name}' is abstract or extern and cannot have a body; use WriteMethodSignature.",
                nameof(method));
        }

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;

        SourceWriterExtensions.WriteMethodHeader(_writer, method);

        return new BodyScope(_writer, _writer.Block());
    }

    /// <summary>
    /// Writes one field declaration line. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <param name="field">The field to declare; a const field is written from its constant value.</param>
    /// <param name="initializer">An optional raw initializer expression; not allowed for a const field.</param>
    /// <exception cref="ArgumentException">
    /// <paramref name="field"/> is const and has an <paramref name="initializer"/> or no constant value, or
    /// <paramref name="initializer"/> is blank, or this scope is an interface and the field is neither static nor const.
    /// </exception>
    public void Field(FieldModel field, string? initializer = null)
    {
        if (_model.Kind == TypeDeclarationKind.Interface && !field.IsStatic && !field.IsConst)
        {
            throw new ArgumentException($"'{field.Name}' is an instance field; interfaces cannot declare them.", nameof(field));
        }

        var line = SourceWriterExtensions.RenderField(field, initializer);

        WriteMember(line);
    }

    /// <summary>
    /// Writes one auto-property declaration line such as <c>public int X { get; private set; }</c>, whatever
    /// the source property's shape (accessor bodies, expression bodies and <c>field</c>-keyword accessors all
    /// become auto accessors). Ref returns, <c>volatile</c> and ref fields are not represented by the models
    /// and are not written. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="property"/> is abstract (including interface members), an explicit interface
    /// implementation (its name contains '.'), or has no get accessor; or this scope is an interface and the
    /// property is not static.
    /// </exception>
    public void AutoProperty(PropertyModel property)
    {
        if (_model.Kind == TypeDeclarationKind.Interface && !property.IsStatic)
        {
            throw new ArgumentException(
                $"'{property.Name}' is an instance property; interfaces cannot declare auto-properties.",
                nameof(property));
        }

        var line = SourceWriterExtensions.RenderAutoProperty(property);

        WriteMember(line);
    }

    /// <summary>
    /// Writes <paramref name="property"/>'s header and opens its braced accessor list; the returned scope's
    /// <see cref="PropertyScope.Get"/>, <see cref="PropertyScope.Set"/> and <see cref="PropertyScope.Init"/>
    /// open the accessor bodies. A blank line separates it from a preceding sibling.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="property"/> is abstract (including interface members without a default body), an
    /// explicit interface implementation (its name contains '.'), or has no accessors.
    /// </exception>
    public PropertyScope Property(PropertyModel property)
    {
        if (property.IsAbstract)
        {
            throw new ArgumentException(
                $"'{property.Name}' is abstract (or an interface member) and cannot have accessor bodies.",
                nameof(property));
        }

        // The model carries an explicit interface implementation's name as "IFoo.Member".
        if (property.Name.IndexOf('.') >= 0)
        {
            throw new ArgumentException(
                $"'{property.Name}' is an explicit interface implementation, which cannot be written with a public header.",
                nameof(property));
        }

        if (property.Accessors.Count == 0)
        {
            throw new ArgumentException($"'{property.Name}' has no accessors.", nameof(property));
        }

        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;

        _writer.WriteLine(SourceWriterExtensions.RenderPropertyHeader(property));

        return new PropertyScope(_writer, property, _writer.Block());
    }

    // Renders before writing so a rejected model leaves the writer untouched.
    private void WriteMember(string line)
    {
        if (_state.NeedsBlankLine)
        {
            _writer.WriteLine();
        }

        _state.NeedsBlankLine = true;

        _writer.WriteLine(line);
    }

    /// <summary>Closes the type's block, and those of its containing types when it opened them.</summary>
    public void Dispose()
    {
        _declaration.Dispose();
    }

    private bool IsThisType(ContainingTypeModel containingType)
    {
        return containingType.Name == _model.Name
            && containingType.Kind == _model.Kind
            && containingType.TypeParameters.Equals(_model.TypeParameters);
    }

    private sealed class State
    {
        public bool NeedsBlankLine;
    }
}
