namespace Haitch.Roslyn.Tests;

public class SourceHeaderTests
{
    private const string AutoGeneratedLine = "// <auto-generated/>";
    private const string NullableEnableLine = "#nullable enable";

    [Test]
    public async Task Should_start_every_shipped_source_file_with_the_auto_generated_header()
    {
        IReadOnlyList<string> filesWithoutHeader = FindShippedSourceFiles()
            .Where(path => !StartsWithHeader(path))
            .ToList();

        await Assert.That(filesWithoutHeader).IsEmpty();
    }

    private static IEnumerable<string> FindShippedSourceFiles()
    {
        string sourceDirectory = Path.Combine(RepoPaths.Root, "src", "Haitch.Roslyn");

        return Directory
            .EnumerateFiles(sourceDirectory, "*.cs", SearchOption.AllDirectories)
            .Where(path => !IsInBinOrObj(sourceDirectory, path));
    }

    private static bool IsInBinOrObj(string sourceDirectory, string filePath)
    {
        string relativePath = Path.GetRelativePath(sourceDirectory, filePath);
        string[] segments = relativePath.Split(
            Path.DirectorySeparatorChar,
            Path.AltDirectorySeparatorChar
        );

        return segments.Contains("bin", StringComparer.OrdinalIgnoreCase)
            || segments.Contains("obj", StringComparer.OrdinalIgnoreCase);
    }

    private static bool StartsWithHeader(string filePath)
    {
        using StreamReader reader = new(filePath);

        string? firstLine = reader.ReadLine();
        string? secondLine = reader.ReadLine();

        return firstLine == AutoGeneratedLine && secondLine == NullableEnableLine;
    }
}
