using Haitch.Roslyn.Models;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.CSharp15.Tests;

public class ClosedModelTests
{
    private const string ShapeSource = """
                                       #nullable enable
                                       namespace App;
                                       public closed record Shape;
                                       """;

    private static readonly MetadataReference[] References = CreateReferences();

    [Test]
    public async Task From_ClosedRecord_IsClosed()
    {
        var compilation = Compile(ShapeSource);

        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Shape")!);

        await Assert.That(model.IsClosed).IsTrue();
        await Assert.That(model.IsAbstract).IsTrue();
    }

    [Test]
    public async Task From_ClosedClassWithOneClosedPart_IsClosed()
    {
        var compilation = Compile(
            """
            namespace App;
            public closed partial class Shape;
            """,
            """
            namespace App;
            public partial class Shape;
            """
        );

        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Shape")!);

        await Assert.That(model.IsClosed).IsTrue();
    }

    [Test]
    public async Task From_ClosedClassWithClosedOnlyOnLaterPart_IsClosed()
    {
        var compilation = Compile(
            """
            namespace App;
            public partial class Shape;
            """,
            """
            namespace App;
            public closed partial class Shape;
            """
        );

        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Shape")!);

        await Assert.That(model.IsClosed).IsTrue();
    }

    [Test]
    public async Task From_AbstractClass_IsNotClosed()
    {
        var compilation = Compile("public abstract class Plain;");

        var model = TypeModel.From(compilation.GetTypeByMetadataName("Plain")!);

        await Assert.That(model.IsAbstract).IsTrue();
        await Assert.That(model.IsClosed).IsFalse();
    }

    [Test]
    public async Task From_ClosedTypeFromMetadata_IsClosed()
    {
        var reference = CompileToReference(ShapeSource);
        var consumer = Compile("public class Consumer;", references: [reference]);

        var model = TypeModel.From(consumer.GetTypeByMetadataName("App.Shape")!);

        await Assert.That(model.IsClosed).IsTrue();
    }

    [Test]
    public async Task From_AbstractClassFromMetadata_IsNotClosed()
    {
        var reference = CompileToReference("public abstract class Plain;");
        var consumer = Compile("public class Consumer;", references: [reference]);

        var model = TypeModel.From(consumer.GetTypeByMetadataName("Plain")!);

        await Assert.That(model.IsClosed).IsFalse();
    }

    [Test]
    public async Task WriteTypeDeclaration_PartOfClosedClass_DoesNotEchoModifiersAndCompiles()
    {
        const string source = """
                              #nullable enable
                              namespace App;
                              public closed partial class Shape;
                              """;
        var compilation = Compile(source);
        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Shape")!);

        var writer = new SourceWriter();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);
        using (writer.WriteTypeDeclaration(model))
        {
            writer.WriteLine("public string Describe() => \"shape\";");
        }

        var generated = writer.ToString();
        var diagnostics = Compile(source, generated).GetDiagnostics();

        await Assert.That(generated).DoesNotContain("closed");
        await Assert.That(generated).DoesNotContain("abstract");
        await Assert.That(diagnostics.Select(d => d.ToString()).ToArray()).IsEmpty();
    }

    private static CSharpCompilation Compile(params string[] sources)
    {
        return Compile(sources, []);
    }

    private static CSharpCompilation Compile(string source, MetadataReference[] references)
    {
        return Compile([source], references);
    }

    private static CSharpCompilation Compile(string[] sources, MetadataReference[] references)
    {
        var trees = sources
            .Append(CSharp15Polyfills.Source)
            .Select(source => CSharpSyntaxTree.ParseText(source, CSharp15.ParseOptions));

        return CSharpCompilation.Create(
            "ClosedModelTests" + Guid.NewGuid().ToString("N"),
            trees,
            [.. References, .. references],
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );
    }

    private static MetadataReference CompileToReference(string source)
    {
        var compilation = Compile(source);
        using var stream = new MemoryStream();
        var result = compilation.Emit(stream);
        if (!result.Success)
        {
            throw new InvalidOperationException(string.Join(Environment.NewLine, result.Diagnostics));
        }

        return MetadataReference.CreateFromImage(stream.ToArray());
    }

    private static MetadataReference[] CreateReferences()
    {
        var trustedPlatformAssemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;

        return trustedPlatformAssemblies
            .Split(Path.PathSeparator)
            .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
            .ToArray();
    }
}
