using Haitch.Roslyn.Models;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Haitch.Roslyn.CSharp15.Tests;

public class UnionModelTests
{
    private const string PetSource = """
                                     #nullable enable
                                     namespace App;
                                     public record Cat(string Name);
                                     public record Dog(string Name);
                                     public partial union Pet(Cat, Dog);
                                     """;

    private static readonly MetadataReference[] References = CreateReferences();

    [Test]
    public async Task From_UnionDeclaration_RecordsKindAndCaseTypesInOrder()
    {
        var compilation = Compile(PetSource);

        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Pet")!);

        await Assert.That(model.Kind).IsEqualTo(TypeDeclarationKind.Union);
        await Assert
            .That(string.Join(",", model.UnionCaseTypes.Select(t => t.FullyQualifiedName)))
            .IsEqualTo("global::App.Cat,global::App.Dog");
    }

    [Test]
    public async Task From_HandWrittenStructImplementingIUnion_StaysStructAndGeneratedPartCompiles()
    {
        const string source = """
                              #nullable enable
                              public partial struct Manual : System.Runtime.CompilerServices.IUnion
                              {
                                  public object? Value => null;
                              }
                              """;
        var compilation = Compile(source);

        var model = TypeModel.From(compilation.GetTypeByMetadataName("Manual")!);

        var writer = new SourceWriter();
        writer.WriteAutoGeneratedHeader();
        using (writer.WriteTypeDeclaration(model))
        {
            writer.WriteLine("public string Describe() => \"manual\";");
        }

        var diagnostics = Compile(source, writer.ToString()).GetDiagnostics();

        await Assert.That(model.Kind).IsEqualTo(TypeDeclarationKind.Struct);
        await Assert.That(model.UnionCaseTypes.Count).IsEqualTo(0);
        await Assert.That(diagnostics.Select(d => d.ToString()).ToArray()).IsEmpty();
    }

    [Test]
    public async Task From_UnionFromMetadata_ModelsAsUnionWithCaseTypes()
    {
        var producer = CSharpCompilation.Create(
            "UnionProducer",
            [
                CSharpSyntaxTree.ParseText(PetSource, CSharp15.ParseOptions),
                CSharpSyntaxTree.ParseText(CSharp15Polyfills.Source, CSharp15.ParseOptions),
            ],
            References,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );
        using var stream = new MemoryStream();
        var emitted = producer.Emit(stream);
        await Assert.That(emitted.Success).IsTrue();
        stream.Position = 0;
        var consumer = CSharpCompilation.Create(
            "UnionConsumer",
            [CSharpSyntaxTree.ParseText("class C { }", CSharp15.ParseOptions)],
            References.Append(MetadataReference.CreateFromStream(stream)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );

        var model = TypeModel.From(consumer.GetTypeByMetadataName("App.Pet")!);

        await Assert.That(model.Kind).IsEqualTo(TypeDeclarationKind.Union);
        await Assert
            .That(string.Join(",", model.UnionCaseTypes.Select(t => t.FullyQualifiedName)))
            .IsEqualTo("global::App.Cat,global::App.Dog");
    }

    [Test]
    public async Task From_UserWrittenOneParameterConstructorInUnion_IsNotACaseType()
    {
        var compilation = Compile(
            """
            #nullable enable
            namespace App;
            public record Cat(string Name);
            public record Dog(string Name);
            public partial union Pet(Cat, Dog)
            {
                public Pet(int legs) : this(new Cat("x")) { }
            }
            """
        );

        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Pet")!);

        await Assert.That(model.Kind).IsEqualTo(TypeDeclarationKind.Union);
        await Assert
            .That(string.Join(",", model.UnionCaseTypes.Select(t => t.FullyQualifiedName)))
            .IsEqualTo("global::App.Cat,global::App.Dog");
    }

    [Test]
    public async Task From_PlainStruct_IsNotAUnion()
    {
        var compilation = Compile("public struct Plain { }");

        var model = TypeModel.From(compilation.GetTypeByMetadataName("Plain")!);

        await Assert.That(model.Kind).IsEqualTo(TypeDeclarationKind.Struct);
        await Assert.That(model.UnionCaseTypes.Count).IsEqualTo(0);
    }

    [Test]
    public async Task WriteTypeDeclaration_PartialUnionPart_CompilesWithZeroDiagnostics()
    {
        var compilation = Compile(PetSource);
        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Pet")!);

        var writer = new SourceWriter();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);
        using (writer.WriteTypeDeclaration(model))
        {
            writer.WriteLine("public string Describe() => \"pet\";");
        }

        var diagnostics = Compile(PetSource, writer.ToString()).GetDiagnostics();

        await Assert.That(diagnostics.Select(d => d.ToString()).ToArray()).IsEmpty();
    }

    [Test]
    public async Task WriteTypeDeclaration_NestedPartialClassInUnion_CompilesWithZeroDiagnostics()
    {
        const string source = """
                              #nullable enable
                              namespace App;
                              public record Cat(string Name);
                              public record Dog(string Name);
                              public partial union Pet(Cat, Dog)
                              {
                                  public partial class Inner { }
                              }
                              """;
        var compilation = Compile(source);
        var model = TypeModel.From(compilation.GetTypeByMetadataName("App.Pet+Inner")!);

        var writer = new SourceWriter();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);
        using (writer.WriteTypeDeclaration(model))
        {
            writer.WriteLine("public string Describe() => \"inner\";");
        }

        var diagnostics = Compile(source, writer.ToString()).GetDiagnostics();

        await Assert.That(model.ContainingTypes[0].Kind).IsEqualTo(TypeDeclarationKind.Union);
        await Assert.That(diagnostics.Select(d => d.ToString()).ToArray()).IsEmpty();
    }

    private static CSharpCompilation Compile(params string[] sources)
    {
        var trees = sources
            .Append(CSharp15Polyfills.Source)
            .Select(source => CSharpSyntaxTree.ParseText(source, CSharp15.ParseOptions));

        return CSharpCompilation.Create(
            "UnionModelTests",
            trees,
            References,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );
    }

    private static MetadataReference[] CreateReferences()
    {
        var trustedPlatformAssemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;

        return trustedPlatformAssemblies
            .Split(Path.PathSeparator)
            .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
            .ToArray();
    }
}
