// <auto-generated/>
#nullable enable

using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Diagnostics;

internal sealed record DiagnosticInfo
{
    public DiagnosticInfo(DiagnosticDescriptor descriptor, LocationInfo? location, params string[] messageArgs)
    {
        Descriptor = descriptor;
        Location = location;
        MessageArgs = new EquatableArray<string>(messageArgs);
    }

    public DiagnosticDescriptor Descriptor { get; }

    public LocationInfo? Location { get; }

    public EquatableArray<string> MessageArgs { get; }

    public static DiagnosticInfo Create(DiagnosticDescriptor descriptor, Location? location, params string[] messageArgs)
    {
        return new DiagnosticInfo(descriptor, location is null ? null : LocationInfo.From(location), messageArgs);
    }

    public Diagnostic ToDiagnostic()
    {
        return Diagnostic.Create(Descriptor, Location?.ToLocation() ?? Microsoft.CodeAnalysis.Location.None, MessageArgs.AsSpan().ToArray());
    }
}
