// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Haitch.Roslyn.Diagnostics;

internal sealed record LocationInfo(string FilePath, TextSpan Span, LinePositionSpan LineSpan)
{
    public static LocationInfo? From(Location location)
    {
        if (location.Kind != LocationKind.SourceFile && location.Kind != LocationKind.ExternalFile)
        {
            return null;
        }

        // Unmapped span: preserves what the compiler actually saw, at the cost of
        // not reflecting #line/pragma remapping.
        FileLinePositionSpan lineSpan = location.GetLineSpan();

        return new LocationInfo(lineSpan.Path, location.SourceSpan, lineSpan.Span);
    }

    // For locations outside the compilation's syntax trees (such as additional files), which have no tree to bind to.
    public Location ToLocation()
    {
        return Location.Create(FilePath, Span, LineSpan);
    }

    // Binding to the compilation's own tree is what lets #pragma warning disable suppress the diagnostic (and,
    // in a compiler build, [SuppressMessage]); an ambiguous or stale path falls back to the unbound location
    // rather than guessing.
    public Location ToLocation(Compilation compilation)
    {
        SyntaxTree? match = null;

        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            if (tree.FilePath != FilePath)
            {
                continue;
            }

            if (match is not null)
            {
                return ToLocation();
            }

            match = tree;
        }

        if (match is null)
        {
            return ToLocation();
        }

        return Span.End > match.GetText().Length ? ToLocation() : Location.Create(match, Span);
    }
}
