// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Haitch.Roslyn.Diagnostics;

internal sealed record LocationInfo(string FilePath, TextSpan Span, LinePositionSpan LineSpan)
{
    public static LocationInfo? From(Location location)
    {
        if (location.Kind != LocationKind.SourceFile && location.Kind != LocationKind.ExternalFile)
        {
            return null;
        }

        // Unmapped span: preserves what the compiler actually saw, at the cost of
        // not reflecting #line/pragma remapping.
        FileLinePositionSpan lineSpan = location.GetLineSpan();

        return new LocationInfo(lineSpan.Path, location.SourceSpan, lineSpan.Span);
    }

    public Location ToLocation()
    {
        return Location.Create(FilePath, Span, LineSpan);
    }
}
