// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Diagnostics;

// Generator configuration (hold in a static readonly field), never a pipeline value:
// DiagnosticDescriptor has no value equality.
internal sealed record PartialTypeDiagnostics(
    DiagnosticDescriptor NotPartial,
    DiagnosticDescriptor ContainingTypeNotPartial,
    DiagnosticDescriptor FileLocal);

internal static class PartialTypeValidation
{
    /// <summary>
    /// Checks that the declaration can be extended with a partial declaration: the type and its containing
    /// types are partial and the type is not file-local. Every failed check is reported, not just the first.
    /// </summary>
    /// <param name="type">The type to validate; returned unchanged on success.</param>
    /// <param name="syntax">The declaration's syntax facts and location.</param>
    /// <param name="diagnostics">The descriptors to report with.</param>
    public static Result<TypeModel> Validate(TypeModel type, SyntaxInfo syntax, PartialTypeDiagnostics diagnostics)
    {
        var failures = new List<DiagnosticInfo>();

        if (!syntax.IsPartial)
        {
            failures.Add(new DiagnosticInfo(diagnostics.NotPartial, syntax.Location, type.Name));
        }

        if (!syntax.AreContainingTypesPartial)
        {
            failures.Add(new DiagnosticInfo(diagnostics.ContainingTypeNotPartial, syntax.Location, type.Name));
        }

        if (type.IsFileLocal)
        {
            failures.Add(new DiagnosticInfo(diagnostics.FileLocal, syntax.Location, type.Name));
        }

        return failures.Count == 0
            ? type
            : Result<TypeModel>.Failure(EquatableArray<DiagnosticInfo>.FromOwnedArray(failures.ToArray()));
    }

    /// <summary>
    /// Checks only that the containing types are partial (the member's own <c>partial</c> modifier is not
    /// examined), for a generator that validates a value other than a <see cref="TypeModel"/> or reports
    /// a single descriptor.
    /// </summary>
    /// <param name="value">The value to pass through on success.</param>
    /// <param name="syntax">The declaration's syntax facts and location.</param>
    /// <param name="containingTypeNotPartial">The descriptor reported when the chain is not partial.</param>
    /// <param name="messageArgument">The single argument formatted into the descriptor's message.</param>
    public static Result<T> ValidateContainingTypes<T>(
        T value,
        SyntaxInfo syntax,
        DiagnosticDescriptor containingTypeNotPartial,
        string messageArgument)
        where T : IEquatable<T>
    {
        return syntax.AreContainingTypesPartial
            ? value
            : new DiagnosticInfo(containingTypeNotPartial, syntax.Location, messageArgument);
    }
}
