// <auto-generated/>
#nullable enable

using System.Collections.Generic;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Diagnostics;

// Generator configuration (hold in a static readonly field), never a pipeline value:
// DiagnosticDescriptor has no value equality.
internal sealed record PartialTypeDiagnostics(
    DiagnosticDescriptor NotPartial,
    DiagnosticDescriptor ContainingTypeNotPartial,
    DiagnosticDescriptor FileLocal);

internal static class PartialTypeValidation
{
    public static Result<TypeModel> Validate(TypeModel type, SyntaxInfo syntax, PartialTypeDiagnostics diagnostics)
    {
        var failures = new List<DiagnosticInfo>();

        if (!syntax.IsPartial)
        {
            failures.Add(new DiagnosticInfo(diagnostics.NotPartial, syntax.Location, type.Name));
        }

        if (!syntax.AreContainingTypesPartial)
        {
            failures.Add(new DiagnosticInfo(diagnostics.ContainingTypeNotPartial, syntax.Location, type.Name));
        }

        if (type.IsFileLocal)
        {
            failures.Add(new DiagnosticInfo(diagnostics.FileLocal, syntax.Location, type.Name));
        }

        return failures.Count == 0
            ? type
            : Result<TypeModel>.Failure(EquatableArray<DiagnosticInfo>.FromOwnedArray(failures.ToArray()));
    }
}
