// <auto-generated/>
#nullable enable

using System;
using Haitch.Roslyn.Types;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Diagnostics;

// Splits a Result<T> pipeline into two independent outputs: a diagnostics half that is
// registered for reporting here, and a values-only half the caller registers its own output
// for. Splitting via Select/Where (rather than filtering inside one RegisterSourceOutput) lets
// the incremental engine cache the value step per-item, independent of unrelated failures.
internal static class ResultPipelineExtensions
{
    public static void ReportDiagnostics(this SourceProductionContext context, EquatableArray<DiagnosticInfo> diagnostics)
    {
        foreach (DiagnosticInfo diagnostic in diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }
    }

    public static IncrementalValuesProvider<T> ReportDiagnostics<T>(
        this IncrementalValuesProvider<Result<T>> results,
        IncrementalGeneratorInitializationContext context,
        string trackingName)
        where T : IEquatable<T>
    {
        IncrementalValuesProvider<Result<T>> trackedResults = results.WithTrackingName(trackingName);

        IncrementalValuesProvider<EquatableArray<DiagnosticInfo>> diagnostics = trackedResults
            .Where(static result => !result.IsSuccess)
            .Select(static (result, _) => result.Diagnostics)
            .WithTrackingName($"{trackingName}.Diagnostics");

        context.RegisterSourceOutput(
            diagnostics,
            static (productionContext, diagnosticsForResult) => productionContext.ReportDiagnostics(diagnosticsForResult));

        return trackedResults
            .Where(static result => result.IsSuccess)
            .Select(static (result, _) => result.TryGetValue(out T? value) ? value : default!);
    }
}
