using System.Linq;
using Haitch.Roslyn.Models;
using Haitch.Roslyn.Tests.Models;
using Haitch.Roslyn.Types;
using Haitch.Roslyn.Writing;
using Microsoft.CodeAnalysis;

namespace Haitch.Roslyn.Tests.Writing;

public class SourceWriterExtensionsTests
{
    [Test]
    public async Task Should_write_the_auto_generated_header()
    {
        SourceWriter writer = new();

        writer.WriteAutoGeneratedHeader();

        string expected = """
            // <auto-generated/>
            #nullable enable


            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        CompilationHelper.Compile(writer.ToString());
    }

    [Test]
    public async Task Should_write_a_file_scoped_namespace_and_a_simple_type_declaration()
    {
        TypeModel model = new(
            Namespace: "Example",
            Name: "Sample",
            Kind: TypeDeclarationKind.Class,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: false,
            IsSealed: false,
            IsReadOnly: false,
            IsRefLikeType: false,
            IsFileLocal: false,
            TypeParameters: default,
            ContainingTypes: default,
            Attributes: default,
            Fields: default,
            Properties: default,
            Methods: default
        );

        SourceWriter writer = new();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);

        using (writer.WriteTypeDeclaration(model)) { }

        string expected = """
            // <auto-generated/>
            #nullable enable

            namespace Example;

            partial class Sample
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial class Sample
            {
            }
            """;

        // Compile only the type declaration alongside the original source: the full writer
        // output above also carries "namespace Example;", and a file can declare a file-scoped
        // namespace only once (CS8940), so a second copy from the original source would collide.
        SourceWriter typeOnlyWriter = new();
        using (typeOnlyWriter.WriteTypeDeclaration(model)) { }

        CompilationHelper.Compile(originalSource + "\n" + typeOnlyWriter.ToString());
    }

    [Test]
    public async Task Should_write_nothing_for_the_global_namespace()
    {
        TypeModel model = new(
            Namespace: null,
            Name: "Sample",
            Kind: TypeDeclarationKind.Class,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: false,
            IsSealed: false,
            IsReadOnly: false,
            IsRefLikeType: false,
            IsFileLocal: false,
            TypeParameters: default,
            ContainingTypes: default,
            Attributes: default,
            Fields: default,
            Properties: default,
            Methods: default
        );

        SourceWriter writer = new();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);

        using (writer.WriteTypeDeclaration(model)) { }

        string expected = """
            // <auto-generated/>
            #nullable enable

            partial class Sample
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public partial class Sample
            {
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + writer.ToString());
    }

    [Test]
    public async Task Should_write_a_partial_declaration_nested_two_levels_deep()
    {
        ContainingTypeModel outer = new(
            Kind: TypeDeclarationKind.Class,
            Name: "Outer",
            TypeParameters: default,
            Accessibility: Accessibility.Public,
            IsReadOnly: false,
            IsRefLikeType: false
        );

        ContainingTypeModel inner = new(
            Kind: TypeDeclarationKind.Struct,
            Name: "Inner",
            TypeParameters: default,
            Accessibility: Accessibility.Public,
            IsReadOnly: true,
            IsRefLikeType: false
        );

        TypeModel model = new(
            Namespace: "Example",
            Name: "Innermost",
            Kind: TypeDeclarationKind.Class,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: false,
            IsSealed: false,
            IsReadOnly: false,
            IsRefLikeType: false,
            IsFileLocal: false,
            TypeParameters: default,
            ContainingTypes: new[] { outer, inner }.ToEquatableArray(),
            Attributes: default,
            Fields: default,
            Properties: default,
            Methods: default
        );

        SourceWriter writer = new();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);

        using (writer.WriteTypeDeclaration(model)) { }

        string expected = """
            // <auto-generated/>
            #nullable enable

            namespace Example;

            partial class Outer
            {
                readonly partial struct Inner
                {
                    partial class Innermost
                    {
                    }
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial class Outer
            {
                public readonly partial struct Inner
                {
                    public partial class Innermost
                    {
                    }
                }
            }
            """;

        // See the file-scoped-namespace test above for why only the type declaration (and not
        // the full header+namespace output) is compiled alongside the original source.
        SourceWriter typeOnlyWriter = new();
        using (typeOnlyWriter.WriteTypeDeclaration(model)) { }

        CompilationHelper.Compile(originalSource + "\n" + typeOnlyWriter.ToString());
    }

    [Test]
    public async Task Should_write_a_generic_type_with_constraints()
    {
        TypeParameterModel typeParameter = new(
            Name: "T",
            ConstraintTypes: default,
            HasReferenceTypeConstraint: true,
            ReferenceTypeConstraintNullableAnnotation: NullableAnnotation.None,
            HasValueTypeConstraint: false,
            HasUnmanagedTypeConstraint: false,
            HasNotNullConstraint: false,
            HasConstructorConstraint: true
        );

        TypeModel model = new(
            Namespace: "Example",
            Name: "Sample",
            Kind: TypeDeclarationKind.Class,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: false,
            IsSealed: false,
            IsReadOnly: false,
            IsRefLikeType: false,
            IsFileLocal: false,
            TypeParameters: new[] { typeParameter }.ToEquatableArray(),
            ContainingTypes: default,
            Attributes: default,
            Fields: default,
            Properties: default,
            Methods: default
        );

        SourceWriter writer = new();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);

        using (writer.WriteTypeDeclaration(model)) { }

        string expected = """
            // <auto-generated/>
            #nullable enable

            namespace Example;

            partial class Sample<T>
                where T : class, new()
            {
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial class Sample<T>
            {
            }
            """;

        // See the file-scoped-namespace test above for why only the type declaration (and not
        // the full header+namespace output) is compiled alongside the original source.
        SourceWriter typeOnlyWriter = new();
        using (typeOnlyWriter.WriteTypeDeclaration(model)) { }

        CompilationHelper.Compile(originalSource + "\n" + typeOnlyWriter.ToString());
    }

    [Test]
    public async Task Should_write_a_method_signature_from_a_method_model()
    {
        ParameterModel parameter = new(
            Name: "name",
            Type: TypeRef.From(StringSymbol()),
            RefKind: RefKind.None,
            ScopedKind: ScopedKind.None,
            IsParams: false,
            DefaultValue: null,
            IsDefaultLiteral: false,
            Attributes: default
        );

        MethodModel method = new(
            Name: "DoWork",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(VoidSymbol()),
            ReturnRefKind: ReturnRefKind.None,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: true,
            IsVirtual: false,
            IsOverride: false,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: new[] { parameter }.ToEquatableArray(),
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        string expected = """
            public abstract void DoWork(string name);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        // The method is abstract, so no implementation is required anywhere: the generated
        // partial can add it to the type without a corresponding member in the original source.
        const string originalSource = """
            namespace Example;

            public abstract partial class Sample
            {
            }
            """;

        string generatedSource = $$"""
            partial class Sample
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_render_default_parameter_values()
    {
        ParameterModel[] parameters =
        [
            new ParameterModel(
                Name: "flag",
                Type: TypeRef.From(BoolSymbol()),
                RefKind: RefKind.None,
                ScopedKind: ScopedKind.None,
                IsParams: false,
                DefaultValue: ConstantValue.ForPrimitive(true),
                IsDefaultLiteral: false,
                Attributes: default
            ),
            new ParameterModel(
                Name: "text",
                Type: TypeRef.From(StringSymbol()),
                RefKind: RefKind.None,
                ScopedKind: ScopedKind.None,
                IsParams: false,
                DefaultValue: ConstantValue.ForString("a\"b"),
                IsDefaultLiteral: false,
                Attributes: default
            ),
            new ParameterModel(
                Name: "count",
                Type: TypeRef.From(LongSymbol()),
                RefKind: RefKind.None,
                ScopedKind: ScopedKind.None,
                IsParams: false,
                DefaultValue: ConstantValue.ForPrimitive(5L),
                IsDefaultLiteral: false,
                Attributes: default
            ),
            new ParameterModel(
                Name: "value",
                Type: TypeRef.From(IntSymbol()),
                RefKind: RefKind.None,
                ScopedKind: ScopedKind.None,
                IsParams: false,
                // ParameterModel.GetDefaultValue always returns ConstantValue.ForNull for a value
                // type's `= default`; DefaultValue is null only when there is no default at all.
                DefaultValue: ConstantValue.ForNull(TypeRef.From(IntSymbol())),
                IsDefaultLiteral: true,
                Attributes: default
            ),
        ];

        // Accessibility.NotApplicable renders no keyword, matching an interface member, which is
        // the simplest declaration-only (no body) shape that doesn't also require "abstract",
        // "extern" or "partial" on the method itself.
        MethodModel method = new(
            Name: "DoWork",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(VoidSymbol()),
            ReturnRefKind: ReturnRefKind.None,
            Accessibility: Accessibility.NotApplicable,
            IsStatic: false,
            IsAbstract: false,
            IsVirtual: false,
            IsOverride: false,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: parameters.ToEquatableArray(),
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        string expected = """
            void DoWork(bool flag = true, string text = "a\"b", long count = 5L, int value = default);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial interface ISample
            {
            }
            """;

        string generatedSource = $$"""
            partial interface ISample
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_render_a_negative_enum_default_with_parentheses()
    {
        const string enumSource = """
            public enum Sign
            {
                Negative = -1,
                Positive = 1,
            }
            """;

        TypeRef signType = TypeRef.From(CompilationHelper.GetNamedTypeSymbol(enumSource, "Sign"));

        ParameterModel parameter = new(
            Name: "sign",
            Type: signType,
            RefKind: RefKind.None,
            ScopedKind: ScopedKind.None,
            IsParams: false,
            DefaultValue: ConstantValue.ForEnum(signType, -1),
            IsDefaultLiteral: false,
            Attributes: default
        );

        MethodModel method = new(
            Name: "DoWork",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(VoidSymbol()),
            ReturnRefKind: ReturnRefKind.None,
            Accessibility: Accessibility.NotApplicable,
            IsStatic: false,
            IsAbstract: false,
            IsVirtual: false,
            IsOverride: false,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: new[] { parameter }.ToEquatableArray(),
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        // Without the fix this renders "(global::Sign)-1", which the compiler parses as
        // "(global::Sign) - 1" (subtraction), not a cast, and fails to compile (CS0119).
        string expected = """
            void DoWork(global::Sign sign = (global::Sign)(-1));

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public enum Sign
            {
                Negative = -1,
                Positive = 1,
            }

            public partial interface ISample
            {
            }
            """;

        string generatedSource = $$"""
            partial interface ISample
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_render_NaN_and_infinity_default_values()
    {
        const string source = """
            public interface ISample
            {
                void DoWork(float f1 = float.NaN, float f2 = float.PositiveInfinity, double d1 = double.NegativeInfinity);
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "ISample")
            .GetMembers("DoWork")
            .OfType<IMethodSymbol>()
            .Single();

        MethodModel method = new(
            Name: "DoWork",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(VoidSymbol()),
            ReturnRefKind: ReturnRefKind.None,
            Accessibility: Accessibility.NotApplicable,
            IsStatic: false,
            IsAbstract: false,
            IsVirtual: false,
            IsOverride: false,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: methodSymbol.Parameters.Select(ParameterModel.From).ToEquatableArray(),
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        // Without the fix, ToString("R") renders these as "NaNf" / "Infinityf" / "-Infinityd",
        // none of which are valid C# tokens.
        string expected = """
            void DoWork(float f1 = float.NaN, float f2 = float.PositiveInfinity, double d1 = double.NegativeInfinity);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial interface ISample2
            {
            }
            """;

        string generatedSource = $$"""
            partial interface ISample2
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_omit_the_where_clause_for_an_override()
    {
        const string source = """
            public class Base
            {
                public virtual void Generic<T>(T value) where T : class
                {
                }
            }

            public class Derived : Base
            {
                public override void Generic<T>(T value)
                {
                }
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "Derived")
            .GetMembers("Generic")
            .OfType<IMethodSymbol>()
            .Single();

        // The override's own type parameter still reports the base member's constraint (it is
        // inherited, not re-declared), which is exactly what makes writing it back out illegal.
        await Assert.That(methodSymbol.TypeParameters[0].HasReferenceTypeConstraint).IsTrue();

        MethodModel method = MethodModel.From(methodSymbol);

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        // Without the fix this renders a "where T : class" clause, which is a compile error
        // (CS0460) on an override.
        string expected = """
            public override void Generic<T>(T value);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public abstract class Base2
            {
                public abstract void Generic<T>(T value) where T : class;
            }

            public partial class Derived2 : Base2
            {
            }
            """;

        // WriteMethodSignature never writes a body (out of scope for this API); the trailing
        // ";" is swapped for "{ }" only so the override below has the body a non-abstract
        // override requires to compile.
        string signature = writer.ToString().TrimEnd();
        string signatureWithBody = signature[..^1] + " { }";

        string generatedSource = $$"""
            partial class Derived2
            {
                {{signatureWithBody}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_omit_the_where_clause_for_an_explicit_interface_implementation()
    {
        const string source = """
            public interface IGeneric
            {
                void Generic<T>(T value) where T : class;
            }

            public class Impl : IGeneric
            {
                void IGeneric.Generic<T>(T value)
                {
                }
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "Impl")
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Single(candidate =>
                candidate.MethodKind == MethodKind.ExplicitInterfaceImplementation
            );

        await Assert.That(methodSymbol.TypeParameters[0].HasReferenceTypeConstraint).IsTrue();

        MethodModel method = MethodModel.From(methodSymbol);

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        // Without the fix this renders a "where T : class" clause, which is a compile error
        // (CS0460) on an explicit interface implementation.
        string expected = """
            void global::IGeneric.Generic<T>(T value);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public interface IGeneric2
            {
                void Generic<T>(T value) where T : class;
            }

            public partial class Impl2 : IGeneric2
            {
            }
            """;

        string signature = writer.ToString().TrimEnd();
        string signatureWithBody = signature[..^1].Replace("IGeneric.", "IGeneric2.") + " { }";

        string generatedSource = $$"""
            partial class Impl2
            {
                {{signatureWithBody}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_keep_static_on_an_explicit_implementation_of_a_static_abstract_member()
    {
        const string source = """
            public interface IMaker
            {
                static abstract int Make();
            }

            public class Impl : IMaker
            {
                static int IMaker.Make() => 1;
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "Impl")
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Single(candidate =>
                candidate.MethodKind == MethodKind.ExplicitInterfaceImplementation
            );

        MethodModel method = MethodModel.From(methodSymbol);

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        string expected = """
            static int global::IMaker.Make();

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public interface IMaker2
            {
                static abstract int Make();
            }

            public partial class Impl2 : IMaker2
            {
            }
            """;

        string signature = writer.ToString().TrimEnd();
        string signatureWithBody = signature[..^1].Replace("IMaker.", "IMaker2.") + " => 1;";

        string generatedSource = $$"""
            partial class Impl2
            {
                {{signatureWithBody}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_keep_async_on_an_explicit_implementation()
    {
        const string source = """
            public interface IRunner
            {
                System.Threading.Tasks.Task<int> RunAsync();
            }

            public class Impl : IRunner
            {
                async System.Threading.Tasks.Task<int> IRunner.RunAsync()
                {
                    await System.Threading.Tasks.Task.Yield();
                    return 1;
                }
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "Impl")
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Single(candidate =>
                candidate.MethodKind == MethodKind.ExplicitInterfaceImplementation
            );

        MethodModel method = MethodModel.From(methodSymbol);

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        string expected = """
            async global::System.Threading.Tasks.Task<int> global::IRunner.RunAsync();

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public interface IRunner2
            {
                System.Threading.Tasks.Task<int> RunAsync();
            }

            public partial class Impl2 : IRunner2
            {
            }
            """;

        string signature = writer.ToString().TrimEnd();
        string signatureWithBody =
            signature[..^1].Replace("IRunner.", "IRunner2.")
            + " { await global::System.Threading.Tasks.Task.Yield(); return 1; }";

        string generatedSource = $$"""
            partial class Impl2
            {
                {{signatureWithBody}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_prefix_the_first_parameter_with_this_for_an_extension_method()
    {
        const string source = """
            public static partial class Extensions
            {
                public static partial void DoWork(this string value, int count);
                public static partial void DoWork(this string value, int count) { }
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "Extensions")
            .GetMembers("DoWork")
            .OfType<IMethodSymbol>()
            .Single(candidate => candidate.IsPartialDefinition);

        await Assert.That(methodSymbol.IsExtensionMethod).IsTrue();

        MethodModel method = MethodModel.From(methodSymbol);

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        // Without the fix, IsExtensionMethod is ignored and "this " is never written, so the
        // parameter list below would read "(string value, int count)".
        string expected = """
            public static partial void DoWork(this string value, int count);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public static partial class Extensions2
            {
                public static partial void DoWork(this string value, int count)
                {
                }
            }
            """;

        string generatedSource = $$"""
            partial class Extensions2
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_throw_for_a_file_local_type()
    {
        TypeModel model = new(
            Namespace: "Example",
            Name: "Sample",
            Kind: TypeDeclarationKind.Class,
            Accessibility: Accessibility.NotApplicable,
            IsStatic: false,
            IsAbstract: false,
            IsSealed: false,
            IsReadOnly: false,
            IsRefLikeType: false,
            IsFileLocal: true,
            TypeParameters: default,
            ContainingTypes: default,
            Attributes: default,
            Fields: default,
            Properties: default,
            Methods: default
        );

        SourceWriter writer = new();

        await Assert.That(() => writer.WriteTypeDeclaration(model)).Throws<ArgumentException>();
    }

    [Test]
    public async Task Should_write_a_nested_generic_type_declaration_from_real_source()
    {
        const string source = """
            public class Outer<T>
            {
                public class Inner<U>
                {
                }
            }
            """;

        INamedTypeSymbol innerSymbol = CompilationHelper.GetNamedTypeSymbol(
            source,
            "Outer`1+Inner`1"
        );
        TypeModel model = TypeModel.From(innerSymbol);

        SourceWriter writer = new();
        writer.WriteAutoGeneratedHeader();
        writer.WriteNamespace(model.Namespace);

        using (writer.WriteTypeDeclaration(model)) { }

        string expected = """
            // <auto-generated/>
            #nullable enable

            partial class Outer<T>
            {
                partial class Inner<U>
                {
                }
            }

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            public partial class Outer<T>
            {
                public partial class Inner<U>
                {
                }
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + writer.ToString());
    }

    [Test]
    public async Task Should_write_a_partial_part_of_a_variant_interface_that_compiles_with_the_original()
    {
        const string originalSource = "public partial interface IFoo<out T> { }";

        INamedTypeSymbol symbol = CompilationHelper.GetNamedTypeSymbol(originalSource, "IFoo`1");
        TypeModel model = TypeModel.From(symbol);

        SourceWriter writer = new();

        using (writer.WriteTypeDeclaration(model)) { }

        await Assert.That(writer.ToString()).Contains("partial interface IFoo<out T>");

        // CS1067 (partial declarations must have the same variance) would surface as an error here.
        CompilationHelper.Compile(originalSource + "\n" + writer.ToString());
    }

    [Test]
    public async Task Should_reject_a_variant_method_type_parameter_and_leave_the_writer_empty()
    {
        const string source = "public interface ISample { void M<T>(); }";

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "ISample")
            .GetMembers("M")
            .OfType<IMethodSymbol>()
            .Single();
        MethodModel model = MethodModel.From(methodSymbol);
        MethodModel variant = model with
        {
            TypeParameters = model
                .TypeParameters.Select(parameter => parameter with { Variance = VarianceKind.Out })
                .ToEquatableArray(),
        };
        SourceWriter writer = new();

        await Assert.That(() => writer.WriteMethodSignature(variant)).Throws<ArgumentException>();
        await Assert.That(writer.ToString()).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task Should_write_a_method_signature_with_ref_return_and_various_parameter_shapes()
    {
        const string source = """
            public interface ISample
            {
                ref int GetValue(scoped ref int input, char c = 'x', decimal amount = 1.5m, float ratio = 1.5f, params int[] extra);
            }
            """;

        IMethodSymbol methodSymbol = CompilationHelper
            .GetNamedTypeSymbol(source, "ISample")
            .GetMembers("GetValue")
            .OfType<IMethodSymbol>()
            .Single();

        MethodModel method = new(
            Name: "GetValue",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(methodSymbol.ReturnType),
            ReturnRefKind: methodSymbol.ReturnsByRef ? ReturnRefKind.Ref : ReturnRefKind.None,
            Accessibility: Accessibility.NotApplicable,
            IsStatic: false,
            IsAbstract: false,
            IsVirtual: false,
            IsOverride: false,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: methodSymbol.Parameters.Select(ParameterModel.From).ToEquatableArray(),
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        string expected = """
            ref int GetValue(scoped ref int input, char c = 'x', decimal amount = 1.5m, float ratio = 1.5f, params int[] extra);

            """;

        await Assert.That(writer.ToString()).IsEqualTo(expected);

        const string originalSource = """
            namespace Example;

            public partial interface ISample2
            {
            }
            """;

        string generatedSource = $$"""
            partial interface ISample2
            {
                {{writer}}
            }
            """;

        CompilationHelper.Compile(originalSource + "\n" + generatedSource);
    }

    [Test]
    public async Task Should_keep_override_on_an_abstract_override_method()
    {
        MethodModel method = new(
            Name: "M",
            MethodKind: MethodKind.Ordinary,
            ReturnType: TypeRef.From(VoidSymbol()),
            ReturnRefKind: ReturnRefKind.None,
            Accessibility: Accessibility.Public,
            IsStatic: false,
            IsAbstract: true,
            IsVirtual: false,
            IsOverride: true,
            IsSealed: false,
            IsAsync: false,
            IsExtern: false,
            IsExtensionMethod: false,
            IsPartialDefinition: false,
            IsReadOnly: false,
            ExplicitInterface: null,
            ExplicitInterfaceMemberName: null,
            TypeParameters: default,
            Parameters: default,
            Attributes: default
        );

        SourceWriter writer = new();
        writer.WriteMethodSignature(method);

        await Assert.That(writer.ToString()).IsEqualTo("public abstract override void M();\n");
    }

    private static ITypeSymbol StringSymbol()
    {
        return FieldType("string");
    }

    private static ITypeSymbol BoolSymbol()
    {
        return FieldType("bool");
    }

    private static ITypeSymbol IntSymbol()
    {
        return FieldType("int");
    }

    private static ITypeSymbol LongSymbol()
    {
        return FieldType("long");
    }

    private static ITypeSymbol VoidSymbol()
    {
        return CompilationHelper
            .Compile("class C { void F() { } }")
            .GetTypeByMetadataName("C")!
            .GetMembers("F")
            .OfType<IMethodSymbol>()
            .Single()
            .ReturnType;
    }

    private static ITypeSymbol FieldType(string typeName)
    {
        return CompilationHelper
            .Compile($"class C {{ {typeName} F; }}")
            .GetTypeByMetadataName("C")!
            .GetMembers("F")
            .OfType<IFieldSymbol>()
            .Single()
            .Type;
    }
}
