// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Haitch.Roslyn.Types;

/// <summary>Collection-expression entry point for <see cref="EquatableArray{T}"/>.</summary>
internal static class EquatableArray
{
    /// <summary>Copies <paramref name="items"/> into a new <see cref="EquatableArray{T}"/>; an empty span yields <c>default</c>.</summary>
    /// <typeparam name="T">The element type.</typeparam>
    /// <param name="items">The elements to copy.</param>
    /// <returns>The populated array.</returns>
    public static EquatableArray<T> Create<T>(ReadOnlySpan<T> items)
        where T : IEquatable<T>?
    {
        return EquatableArray<T>.FromOwnedArray(items.ToArray());
    }
}

[CollectionBuilder(typeof(EquatableArray), nameof(EquatableArray.Create))]
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>, IReadOnlyList<T>
    where T : IEquatable<T>?
{
    private readonly T[] _array;

    public EquatableArray()
    {
        _array = Array.Empty<T>();
    }

    public EquatableArray(T[] array)
    {
        if (array is null || array.Length == 0)
        {
            _array = Array.Empty<T>();
        }
        else
        {
            _array = new T[array.Length];
            Array.Copy(array, _array, array.Length);
        }
    }

    // Adopts `array` without copying. Callers must own `array` exclusively (e.g. one they just
    // produced via ToArray()) so no other reference can mutate it after EquatableArray adopts it.
    private EquatableArray(T[] array, bool _)
    {
        _array = array;
    }

    internal static EquatableArray<T> FromOwnedArray(T[] array)
    {
        return array.Length == 0 ? default : new EquatableArray<T>(array, true);
    }

    public int Count => (_array ?? Array.Empty<T>()).Length;

    public bool IsEmpty => Count == 0;

    public T this[int index] => (_array ?? Array.Empty<T>())[index];

    public ReadOnlySpan<T> AsSpan()
    {
        return (_array ?? Array.Empty<T>()).AsSpan();
    }

    public Enumerator GetEnumerator()
    {
        return new Enumerator(_array ?? Array.Empty<T>());
    }

    // LINQ Count()/ElementAt on netstandard2.0 have no IReadOnlyList fast path and walk this boxed enumerator; prefer Count and the indexer.
    IEnumerator<T> IEnumerable<T>.GetEnumerator()
    {
        return ((IEnumerable<T>)(_array ?? Array.Empty<T>())).GetEnumerator();
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return ((IEnumerable<T>)this).GetEnumerator();
    }

    public bool Equals(EquatableArray<T> other)
    {
        var self = _array ?? Array.Empty<T>();
        var otherArray = other._array ?? Array.Empty<T>();

        if (self.Length != otherArray.Length)
        {
            return false;
        }

        for (var i = 0; i < self.Length; i++)
        {
            if (!EqualityComparer<T>.Default.Equals(self[i], otherArray[i]))
            {
                return false;
            }
        }

        return true;
    }

    public override bool Equals(object? obj)
    {
        return obj is EquatableArray<T> other && Equals(other);
    }

    public override int GetHashCode()
    {
        var self = _array ?? Array.Empty<T>();

        unchecked
        {
            var hash = 17;

            foreach (var item in self)
            {
                // GetHashCode is annotated DisallowNull on newer TFMs, but the default comparer
                // returns 0 for a null item, which nullable-element arrays rely on.
                hash = (hash * 31) + EqualityComparer<T>.Default.GetHashCode(item!);
            }

            return hash;
        }
    }

    public static bool operator ==(EquatableArray<T> left, EquatableArray<T> right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(EquatableArray<T> left, EquatableArray<T> right)
    {
        return !left.Equals(right);
    }

    public struct Enumerator
    {
        private readonly T[] _array;
        private int _index;

        internal Enumerator(T[] array)
        {
            _array = array;
            _index = -1;
        }

        public T Current => (_array ?? Array.Empty<T>())[_index];

        public bool MoveNext()
        {
            var array = _array ?? Array.Empty<T>();
            _index++;
            return _index < array.Length;
        }
    }
}
